//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACADEMIC_TRACK_GRADE
    {
        public string ATG_OID { get; set; }
        public string ATG_ATR_OID { get; set; }
        public string ATG_GRADE_LEVEL { get; set; }
        public string ATG_INSTRUCTION { get; set; }
        public Nullable<System.DateTime> ATG_START_DATE { get; set; }
        public Nullable<System.DateTime> ATG_END_DATE { get; set; }
        public Nullable<decimal> ATG_LAST_MODIFIED { get; set; }
    }
}
