//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALYTIC_COLUMN_DEFINITION
    {
        public string ANC_OID { get; set; }
        public string ANC_AND_OID { get; set; }
        public string ANC_FDD_OID { get; set; }
        public string ANC_ENABLED_IND { get; set; }
        public Nullable<decimal> ANC_FIELD_INDEX { get; set; }
        public string ANC_USER_NAME_LONG { get; set; }
        public string ANC_USER_NAME_SHORT { get; set; }
        public string ANC_USER_TYPE { get; set; }
        public Nullable<decimal> ANC_USER_LENGTH { get; set; }
        public Nullable<decimal> ANC_USER_DECIMAL { get; set; }
        public string ANC_CUSTOM_IND { get; set; }
        public string ANC_FIELDA_001 { get; set; }
        public string ANC_FIELDA_002 { get; set; }
        public string ANC_FIELDA_003 { get; set; }
        public string ANC_FIELDA_004 { get; set; }
        public string ANC_FIELDA_005 { get; set; }
        public string ANC_FIELDA_006 { get; set; }
        public string ANC_FIELDA_007 { get; set; }
        public string ANC_FIELDA_008 { get; set; }
        public string ANC_FIELDA_009 { get; set; }
        public string ANC_FIELDA_010 { get; set; }
        public string ANC_FIELDB_001 { get; set; }
        public string ANC_FIELDB_002 { get; set; }
        public string ANC_FIELDB_003 { get; set; }
        public string ANC_FIELDB_004 { get; set; }
        public string ANC_FIELDB_005 { get; set; }
        public string ANC_FIELDC_001 { get; set; }
        public string ANC_FIELDC_002 { get; set; }
        public string ANC_FIELDC_003 { get; set; }
        public Nullable<decimal> ANC_LAST_MODIFIED { get; set; }
        public Nullable<decimal> ANC_AUDIT_TYPE { get; set; }
    }
}
