//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSESSMENT_COLUMN_DEFINITION
    {
        public string ACD_OID { get; set; }
        public string ACD_ASD_OID { get; set; }
        public string ACD_FDD_OID { get; set; }
        public string ACD_ENABLED_IND { get; set; }
        public Nullable<decimal> ACD_FIELD_INDEX { get; set; }
        public string ACD_USER_NAME_LONG { get; set; }
        public string ACD_USER_NAME_SHORT { get; set; }
        public string ACD_USER_TYPE { get; set; }
        public Nullable<decimal> ACD_USER_LENGTH { get; set; }
        public Nullable<decimal> ACD_USER_DECIMAL { get; set; }
        public string ACD_CUSTOM_IND { get; set; }
        public string ACD_FIELDA_001 { get; set; }
        public string ACD_FIELDA_002 { get; set; }
        public string ACD_FIELDA_003 { get; set; }
        public string ACD_FIELDA_004 { get; set; }
        public string ACD_FIELDA_005 { get; set; }
        public string ACD_FIELDA_006 { get; set; }
        public string ACD_FIELDA_007 { get; set; }
        public string ACD_FIELDA_008 { get; set; }
        public string ACD_FIELDA_009 { get; set; }
        public string ACD_FIELDA_010 { get; set; }
        public string ACD_FIELDB_001 { get; set; }
        public string ACD_FIELDB_002 { get; set; }
        public string ACD_FIELDB_003 { get; set; }
        public string ACD_FIELDB_004 { get; set; }
        public string ACD_FIELDB_005 { get; set; }
        public string ACD_FIELDC_001 { get; set; }
        public string ACD_FIELDC_002 { get; set; }
        public string ACD_FIELDC_003 { get; set; }
        public Nullable<decimal> ACD_LAST_MODIFIED { get; set; }
        public string ACD_RTB_OID { get; set; }
        public string ACD_ALIAS { get; set; }
        public string ACD_DETAIL_CONTROL { get; set; }
        public string ACD_READ_ONLY_IND { get; set; }
        public string ACD_REQUIRED_IND { get; set; }
        public string ACD_LIST_EDIT_IND { get; set; }
        public string ACD_UPDATE_IND { get; set; }
        public string ACD_VALID_REF_ONLY_IND { get; set; }
        public string ACD_CBT_OID { get; set; }
        public Nullable<decimal> ACD_AUDIT_TYPE { get; set; }
    }
}
