//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSESSMENT_DEFINITION
    {
        public string ASD_OID { get; set; }
        public string ASD_ORG_OID_1 { get; set; }
        public string ASD_ORG_OID_2 { get; set; }
        public string ASD_ORG_OID_3 { get; set; }
        public string ASD_ORG_OID_4 { get; set; }
        public string ASD_ORG_OID_5 { get; set; }
        public string ASD_NAME { get; set; }
        public string ASD_SUBJECT { get; set; }
        public string ASD_LEVEL { get; set; }
        public string ASD_HIDE_IN_PORTAL_IND { get; set; }
        public string ASD_TYPE { get; set; }
        public Nullable<decimal> ASD_SCORE_COUNT { get; set; }
        public string ASD_FIELDA_001 { get; set; }
        public string ASD_FIELDA_002 { get; set; }
        public string ASD_FIELDA_003 { get; set; }
        public string ASD_FIELDA_004 { get; set; }
        public string ASD_FIELDA_005 { get; set; }
        public string ASD_FIELDA_006 { get; set; }
        public string ASD_FIELDA_007 { get; set; }
        public string ASD_FIELDA_008 { get; set; }
        public string ASD_FIELDA_009 { get; set; }
        public string ASD_FIELDA_010 { get; set; }
        public string ASD_FIELDB_001 { get; set; }
        public string ASD_FIELDB_002 { get; set; }
        public string ASD_FIELDB_003 { get; set; }
        public string ASD_FIELDB_004 { get; set; }
        public string ASD_FIELDB_005 { get; set; }
        public string ASD_FIELDB_006 { get; set; }
        public string ASD_FIELDB_007 { get; set; }
        public string ASD_FIELDB_008 { get; set; }
        public string ASD_FIELDB_009 { get; set; }
        public string ASD_FIELDB_010 { get; set; }
        public string ASD_FIELDB_011 { get; set; }
        public string ASD_FIELDB_012 { get; set; }
        public string ASD_FIELDB_013 { get; set; }
        public string ASD_FIELDB_014 { get; set; }
        public string ASD_FIELDB_015 { get; set; }
        public string ASD_FIELDC_001 { get; set; }
        public string ASD_FIELDC_002 { get; set; }
        public string ASD_FIELDC_003 { get; set; }
        public string ASD_FIELDC_004 { get; set; }
        public string ASD_FIELDC_005 { get; set; }
        public string ASD_FIELDD_001 { get; set; }
        public Nullable<decimal> ASD_LAST_MODIFIED { get; set; }
        public string ASD_ID { get; set; }
        public Nullable<decimal> ASD_AUDIT_TYPE { get; set; }
    }
}
