//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR_STAFF_DATE
    {
        public string CFD_OID { get; set; }
        public string CFD_CAF_OID { get; set; }
        public Nullable<System.DateTime> CFD_DATE { get; set; }
        public string CFD_IN_SESSION_IND { get; set; }
        public string CFD_SCHEDULE_DAY_TYPE { get; set; }
        public string CFD_FIELDA_001 { get; set; }
        public string CFD_FIELDA_002 { get; set; }
        public string CFD_FIELDA_003 { get; set; }
        public string CFD_FIELDA_004 { get; set; }
        public string CFD_FIELDA_005 { get; set; }
        public string CFD_FIELDB_001 { get; set; }
        public string CFD_FIELDB_002 { get; set; }
        public string CFD_FIELDB_003 { get; set; }
        public Nullable<decimal> CFD_LAST_MODIFIED { get; set; }
    }
}
