//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT_FOLDER
    {
        public string CFR_OID { get; set; }
        public string CFR_NAME { get; set; }
        public string CFR_DESC { get; set; }
        public string CFR_CFR_OID_PARENT { get; set; }
        public string CFR_CFR_OID_ROOT { get; set; }
        public Nullable<decimal> CFR_ITEM_ORDER { get; set; }
        public Nullable<decimal> CFR_LAST_MODIFIED { get; set; }
        public string CFR_TYPE { get; set; }
    }
}
