//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT_PROPERTY_DESCRIPTOR
    {
        public string CPD_OID { get; set; }
        public string CPD_NAME { get; set; }
        public string CPD_IDENTIFIER { get; set; }
        public string CPD_DATA_TYPE { get; set; }
        public string CPD_INDEXED { get; set; }
        public Nullable<decimal> CPD_LAST_MODIFIED { get; set; }
    }
}
