//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT_WEB_LINK
    {
        public string CWL_OID { get; set; }
        public string CWL_URL { get; set; }
        public Nullable<decimal> CWL_LAST_MODIFIED { get; set; }
    }
}
