//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public string CRS_OID { get; set; }
        public string CRS_ORG_OID_1 { get; set; }
        public string CRS_ORG_OID_2 { get; set; }
        public string CRS_ORG_OID_3 { get; set; }
        public string CRS_ORG_OID_4 { get; set; }
        public string CRS_ORG_OID_5 { get; set; }
        public string CRS_CTX_OID { get; set; }
        public string CRS_COURSE_NUMBER { get; set; }
        public string CRS_COURSE_DESCRIPTION { get; set; }
        public string CRS_SHORT_DESCRIPTION { get; set; }
        public string CRS_SUMMARY { get; set; }
        public string CRS_MASTER_TYPE { get; set; }
        public string CRS_DEPARTMENT_CODE { get; set; }
        public string CRS_SCHOOL_LEVEL { get; set; }
        public string CRS_ACADEMIC_LEVEL { get; set; }
        public string CRS_GRADE_LEVEL { get; set; }
        public Nullable<decimal> CRS_CREDIT { get; set; }
        public Nullable<decimal> CRS_WEIGHT { get; set; }
        public string CRS_GPA_IND { get; set; }
        public string CRS_GRADE_INPUT_HIDE_IND { get; set; }
        public string CRS_TRANSCRIPT_HIDE_IND { get; set; }
        public string CRS_REPORT_CARD_HIDE_IND { get; set; }
        public string CRS_HONOR_ROLL_TYPE { get; set; }
        public string CRS_TEACHER_PREP_CODE { get; set; }
        public string CRS_ALTERNATE_GROUP_CODE { get; set; }
        public Nullable<decimal> CRS_SCHOOL_VISIBILITY_TYPE { get; set; }
        public string CRS_EQUIVALANT_CONTENT_CODE { get; set; }
        public string CRS_ALLOW_REPEAT_IND { get; set; }
        public Nullable<decimal> CRS_TOTAL_MINUTES_PER_CYCLE { get; set; }
        public Nullable<decimal> CRS_MIN_MINUTES_PER_SESSION { get; set; }
        public string CRS_PROGRAM { get; set; }
        public string CRS_FIELDA_001 { get; set; }
        public string CRS_FIELDA_002 { get; set; }
        public string CRS_FIELDA_003 { get; set; }
        public string CRS_FIELDA_004 { get; set; }
        public string CRS_FIELDA_005 { get; set; }
        public string CRS_FIELDA_006 { get; set; }
        public string CRS_FIELDA_007 { get; set; }
        public string CRS_FIELDA_008 { get; set; }
        public string CRS_FIELDA_009 { get; set; }
        public string CRS_FIELDA_010 { get; set; }
        public string CRS_FIELDA_011 { get; set; }
        public string CRS_FIELDA_012 { get; set; }
        public string CRS_FIELDA_013 { get; set; }
        public string CRS_FIELDA_014 { get; set; }
        public string CRS_FIELDA_015 { get; set; }
        public string CRS_FIELDB_001 { get; set; }
        public string CRS_FIELDB_002 { get; set; }
        public string CRS_FIELDB_003 { get; set; }
        public string CRS_FIELDB_004 { get; set; }
        public string CRS_FIELDB_005 { get; set; }
        public string CRS_FIELDB_006 { get; set; }
        public string CRS_FIELDB_007 { get; set; }
        public string CRS_FIELDB_008 { get; set; }
        public string CRS_FIELDB_009 { get; set; }
        public string CRS_FIELDB_010 { get; set; }
        public string CRS_FIELDB_011 { get; set; }
        public string CRS_FIELDB_012 { get; set; }
        public string CRS_FIELDB_013 { get; set; }
        public string CRS_FIELDB_014 { get; set; }
        public string CRS_FIELDB_015 { get; set; }
        public string CRS_FIELDC_001 { get; set; }
        public string CRS_FIELDC_002 { get; set; }
        public string CRS_FIELDC_003 { get; set; }
        public string CRS_FIELDC_004 { get; set; }
        public string CRS_FIELDC_005 { get; set; }
        public Nullable<decimal> CRS_LAST_MODIFIED { get; set; }
        public string CRS_CMP_OID { get; set; }
        public string CRS_GUID { get; set; }
    }
}
