//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_SCHEDULE
    {
        public string CSS_OID { get; set; }
        public string CSS_SCH_OID { get; set; }
        public string CSS_CSK_OID { get; set; }
        public string CSS_CSK_OID_BOUND_NEXT { get; set; }
        public string CSS_SPS_OID { get; set; }
        public Nullable<decimal> CSS_SECTIONS_SCHEDULED { get; set; }
        public Nullable<decimal> CSS_PERIODS_PER_CYCLE { get; set; }
        public string CSS_VARIABLE_PPC_IND { get; set; }
        public Nullable<decimal> CSS_BASE_TERMS_PER_YEAR { get; set; }
        public Nullable<decimal> CSS_COVERED_TERM_PER_YEAR { get; set; }
        public string CSS_TERMS_PER_YEAR_VIEW { get; set; }
        public string CSS_SCHD_INCLUDE_IND { get; set; }
        public string CSS_PARTIAL_CONTENT_IND { get; set; }
        public string CSS_VALID_CONTENT_TERMS { get; set; }
        public Nullable<decimal> CSS_SCHEDULE_PRIORITY { get; set; }
        public Nullable<decimal> CSS_ENROLLMENT_MAX { get; set; }
        public string CSS_TERM_BALANCE_TYPE { get; set; }
        public string CSS_SECTION_BALANCE_TYPE { get; set; }
        public string CSS_ALLOW_SUBSTITUTION_IND { get; set; }
        public Nullable<decimal> CSS_REPEAT_TYPE { get; set; }
        public string CSS_PREFERRED_ROOM_EXEMPT_IND { get; set; }
        public string CSS_BALANCE_BY_TERM_IND { get; set; }
        public Nullable<decimal> CSS_LAST_MODIFIED { get; set; }
        public string CSS_WEIGHT_EXEMPT_IND { get; set; }
    }
}
