//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRICULUM_STANDARD
    {
        public string CST_OID { get; set; }
        public string CST_LST_OID { get; set; }
        public string CST_CMP_OID { get; set; }
        public string CST_CLP_OID { get; set; }
        public Nullable<decimal> CST_LAST_MODIFIED { get; set; }
    }
}
