//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_FIELD_MASK
    {
        public string MSK_OID { get; set; }
        public string MSK_PRC_OID { get; set; }
        public string MSK_NAME { get; set; }
        public string MSK_INPUT_EXPRESSION { get; set; }
        public string MSK_OUTPUT_EXPRESSION { get; set; }
        public Nullable<decimal> MSK_LAST_MODIFIED { get; set; }
    }
}
