//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_CALCULATE_FIELD_MEMBER
    {
        public string CFM_OID { get; set; }
        public string CFM_FLD_OID { get; set; }
        public string CFM_CLC_OID { get; set; }
        public Nullable<decimal> CFM_LAST_MODIFIED { get; set; }
    }
}
