//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_TABLE_CONFIG
    {
        public string TBD_OID { get; set; }
        public string TBD_TBL_OID { get; set; }
        public string TBD_ORG_OID_1 { get; set; }
        public string TBD_ORG_OID_2 { get; set; }
        public string TBD_ORG_OID_3 { get; set; }
        public string TBD_ORG_OID_4 { get; set; }
        public string TBD_ORG_OID_5 { get; set; }
        public Nullable<decimal> TBD_SEQUENCE_NUMBER { get; set; }
        public string TBD_USER_NAME { get; set; }
        public string TBD_CATEGORY { get; set; }
        public string TBD_GLOBAL_CATEGORY { get; set; }
        public Nullable<decimal> TBD_TABLE_AUDIT_TYPE { get; set; }
        public string TBD_IDENTIFYING_FIELDS { get; set; }
        public string TBD_SCHOOL_PATH { get; set; }
        public string TBD_ORGANIZATION_PATH { get; set; }
        public Nullable<decimal> TBD_LAST_MODIFIED { get; set; }
        public string TBD_AUDIT_DISPLAY_PATHS { get; set; }
        public string TBD_UNIQUE_FIELDS { get; set; }
    }
}
