//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_RELATION_PATH
    {
        public string RLP_OID { get; set; }
        public string RLP_ORG_OID_1 { get; set; }
        public string RLP_ORG_OID_2 { get; set; }
        public string RLP_ORG_OID_3 { get; set; }
        public string RLP_ORG_OID_4 { get; set; }
        public string RLP_ORG_OID_5 { get; set; }
        public string RLP_TBL_OID { get; set; }
        public string RLP_PATH { get; set; }
        public string RLP_MASK { get; set; }
        public Nullable<decimal> RLP_SEQUENCE_NUMBER { get; set; }
        public Nullable<decimal> RLP_LAST_MODIFIED { get; set; }
    }
}
