//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM_TOPIC_VIEW
    {
        public string FTV_OID { get; set; }
        public string FTV_FTO_OID { get; set; }
        public string FTV_USR_OID { get; set; }
        public Nullable<decimal> FTV_TOPIC_VIEW_TIME { get; set; }
        public Nullable<decimal> FTV_LAST_MODIFIED { get; set; }
    }
}
