//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM_TOPIC
    {
        public string FTO_OID { get; set; }
        public string FTO_GFR_OID { get; set; }
        public string FTO_USR_OID { get; set; }
        public string FTO_TOPIC_TITLE { get; set; }
        public Nullable<decimal> FTO_TOPIC_TIME { get; set; }
        public Nullable<decimal> FTO_TOPIC_VIEWS { get; set; }
        public Nullable<decimal> FTO_TOPIC_REPLIES { get; set; }
        public Nullable<decimal> FTO_TOPIC_STATUS { get; set; }
        public Nullable<decimal> FTO_TOPIC_TYPE { get; set; }
        public string FTO_FIRST_POST_OID { get; set; }
        public string FTO_LAST_POST_OID { get; set; }
        public Nullable<decimal> FTO_MODERATED_REPLIES { get; set; }
        public Nullable<decimal> FTO_HIDDEN_REPLIES { get; set; }
        public string FTO_NEEDS_MODERATION { get; set; }
        public Nullable<decimal> FTO_TOPIC_HIDDEN_POST_TIME { get; set; }
        public Nullable<decimal> FTO_LAST_MODIFIED { get; set; }
    }
}
