//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_TERM_DEFINITION
    {
        public string GTF_OID { get; set; }
        public string GTF_ORG_OID_1 { get; set; }
        public string GTF_ORG_OID_2 { get; set; }
        public string GTF_ORG_OID_3 { get; set; }
        public string GTF_ORG_OID_4 { get; set; }
        public string GTF_ORG_OID_5 { get; set; }
        public string GTF_NAME { get; set; }
        public Nullable<decimal> GTF_GRADE_TERMS_PER_YEAR { get; set; }
        public Nullable<decimal> GTF_LAST_MODIFIED { get; set; }
    }
}
