//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_SCALE_GRADE_DEFINITION
    {
        public string GSG_OID { get; set; }
        public string GSG_GRS_OID { get; set; }
        public string GSG_GRADE_CODE { get; set; }
        public string GSG_GRADE_SHORTCUT { get; set; }
        public Nullable<decimal> GSG_GRADE_VALUE { get; set; }
        public Nullable<decimal> GSG_MINIMUM_CUTOFF_VALUE { get; set; }
        public string GSG_CREDIT_IND { get; set; }
        public string GSG_NO_NUMERIC_IND { get; set; }
        public string GSG_FIELDA_001 { get; set; }
        public string GSG_FIELDA_002 { get; set; }
        public string GSG_FIELDA_003 { get; set; }
        public string GSG_FIELDA_004 { get; set; }
        public Nullable<decimal> GSG_LAST_MODIFIED { get; set; }
        public string GSG_ALIGNMENT_CODE { get; set; }
    }
}
