//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEBOOK_SCORE
    {
        public string GSC_OID { get; set; }
        public string GSC_GCD_OID { get; set; }
        public string GSC_STD_OID { get; set; }
        public string GSC_RBA_OID { get; set; }
        public string GSC_GRM_OID { get; set; }
        public string GSC_SCORE { get; set; }
        public string GSC_FOOTNOTE_CODE { get; set; }
        public string GSC_CALCULATION_OVERRIDE_IND { get; set; }
        public string GSC_ADMIN_UPDATE_IND { get; set; }
        public string GSC_EXEMPT_IND { get; set; }
        public string GSC_DROPPED_IND { get; set; }
        public string GSC_SPECIAL_CODE_IND { get; set; }
        public Nullable<decimal> GSC_LAST_MODIFIED { get; set; }
        public string GSC_GRM_OID_PRIVATE { get; set; }
    }
}
