//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADUATION_STUDENT_PROGRAM
    {
        public string GSR_OID { get; set; }
        public string GSR_GPR_OID { get; set; }
        public string GSR_STD_OID { get; set; }
        public string GSR_REQUIREMENT_WAIVER { get; set; }
        public string GSR_PRIMARY_PROGRAM_STUDY_IND { get; set; }
        public string GSR_FIELDA_001 { get; set; }
        public string GSR_FIELDA_002 { get; set; }
        public string GSR_FIELDA_003 { get; set; }
        public string GSR_FIELDA_004 { get; set; }
        public string GSR_FIELDA_005 { get; set; }
        public string GSR_FIELDA_006 { get; set; }
        public string GSR_FIELDA_007 { get; set; }
        public string GSR_FIELDA_008 { get; set; }
        public string GSR_FIELDA_009 { get; set; }
        public string GSR_FIELDA_010 { get; set; }
        public string GSR_FIELDB_001 { get; set; }
        public string GSR_FIELDB_002 { get; set; }
        public string GSR_FIELDB_003 { get; set; }
        public string GSR_FIELDB_004 { get; set; }
        public string GSR_FIELDB_005 { get; set; }
        public string GSR_FIELDC_001 { get; set; }
        public string GSR_FIELDC_002 { get; set; }
        public Nullable<decimal> GSR_LAST_MODIFIED { get; set; }
    }
}
