//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_TRANSCRIPT_DEFINITION
    {
        public string GTD_OID { get; set; }
        public string GTD_ORG_OID_1 { get; set; }
        public string GTD_ORG_OID_2 { get; set; }
        public string GTD_ORG_OID_3 { get; set; }
        public string GTD_ORG_OID_4 { get; set; }
        public string GTD_ORG_OID_5 { get; set; }
        public string GTD_GTF_OID { get; set; }
        public string GTD_GTC_OID_FINAL { get; set; }
        public string GTD_NAME { get; set; }
        public string GTD_DESCRIPTION { get; set; }
        public string GTD_FIELDA_001 { get; set; }
        public string GTD_FIELDA_002 { get; set; }
        public string GTD_FIELDA_003 { get; set; }
        public Nullable<decimal> GTD_LAST_MODIFIED { get; set; }
        public Nullable<decimal> GTD_AUDIT_TYPE { get; set; }
    }
}
