//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEBOOK_REMARK
    {
        public string GRM_OID { get; set; }
        public string GRM_TEXT { get; set; }
        public string GRM_ADMIN_UPDATE_IND { get; set; }
        public string GRM_PRIVATE_IND { get; set; }
        public Nullable<decimal> GRM_LAST_MODIFIED { get; set; }
    }
}
