//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEBOOK_COLUMN_DEFINITION
    {
        public string GCD_OID { get; set; }
        public string GCD_MST_OID { get; set; }
        public string GCD_CTX_OID { get; set; }
        public string GCD_GCT_OID { get; set; }
        public string GCD_GRS_OID { get; set; }
        public string GCD_RTB_OID { get; set; }
        public string GCD_GTC_OID { get; set; }
        public string GCD_GTM_OID { get; set; }
        public string GCD_STF_OID { get; set; }
        public string GCD_RBD_OID { get; set; }
        public string GCD_GCD_OID { get; set; }
        public string GCD_COLUMN_NAME { get; set; }
        public Nullable<decimal> GCD_COLUMN_TYPE { get; set; }
        public string GCD_COLUMN_CODE { get; set; }
        public string GCD_COLUMN_DESCRIPTION { get; set; }
        public string GCD_SUBMITTED_STUDENT_OIDS { get; set; }
        public Nullable<decimal> GCD_SEQUENCE_NUMBER { get; set; }
        public Nullable<System.DateTime> GCD_DATE_ASSIGNED { get; set; }
        public Nullable<System.DateTime> GCD_DATE_DUE { get; set; }
        public Nullable<System.DateTime> GCD_SUBMISSION_OPEN_DATE { get; set; }
        public Nullable<System.DateTime> GCD_SUBMISSION_CLOSE_DATE { get; set; }
        public Nullable<decimal> GCD_TOTAL_POINTS { get; set; }
        public Nullable<decimal> GCD_COLUMN_WEIGHT { get; set; }
        public Nullable<decimal> GCD_EXTRA_CREDIT_POINTS { get; set; }
        public string GCD_EXTRA_CREDIT_IND { get; set; }
        public Nullable<decimal> GCD_ENTRY_MODE { get; set; }
        public string GCD_SYSTEM_ONLY_IND { get; set; }
        public string GCD_DISABLE_IND { get; set; }
        public string GCD_CALCULATE_IND { get; set; }
        public string GCD_CALCULATION { get; set; }
        public string GCD_DROP_NOT_ALLOWED_IND { get; set; }
        public string GCD_FIELDA_001 { get; set; }
        public string GCD_FIELDA_002 { get; set; }
        public string GCD_FIELDA_003 { get; set; }
        public string GCD_FIELDA_004 { get; set; }
        public string GCD_FIELDA_005 { get; set; }
        public string GCD_FIELDA_006 { get; set; }
        public string GCD_FIELDA_007 { get; set; }
        public string GCD_FIELDA_008 { get; set; }
        public string GCD_FIELDB_001 { get; set; }
        public string GCD_FIELDB_002 { get; set; }
        public string GCD_FIELDB_003 { get; set; }
        public string GCD_FIELDB_004 { get; set; }
        public string GCD_FIELDC_001 { get; set; }
        public string GCD_FIELDC_002 { get; set; }
        public string GCD_FIELDD_001 { get; set; }
        public string GCD_FIELDD_002 { get; set; }
        public byte[] GCD_FIELDE_001 { get; set; }
        public byte[] GCD_FIELDE_002 { get; set; }
        public Nullable<decimal> GCD_LAST_MODIFIED { get; set; }
        public string GCD_LINK_ID { get; set; }
        public string GCD_RICH_TEXT_DESCRIPTION { get; set; }
        public string GCD_LOCK_IND { get; set; }
        public string GCD_NOT_GRADED_IND { get; set; }
        public string GCD_RECURRING_DATA { get; set; }
        public Nullable<decimal> GCD_VISIBILITY_TYPE { get; set; }
        public string GCD_CBT_OID { get; set; }
    }
}
