//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        public string GRP_OID { get; set; }
        public string GRP_ORG_OID_1 { get; set; }
        public string GRP_ORG_OID_2 { get; set; }
        public string GRP_ORG_OID_3 { get; set; }
        public string GRP_ORG_OID_4 { get; set; }
        public string GRP_ORG_OID_5 { get; set; }
        public string GRP_SKL_OID { get; set; }
        public string GRP_NAME { get; set; }
        public string GRP_ICON { get; set; }
        public string GRP_MEMBERS_VIEW { get; set; }
        public string GRP_ADMINISTRATORS_VIEW { get; set; }
        public Nullable<System.DateTime> GRP_CREATE_DATE { get; set; }
        public string GRP_USR_OID_CREATOR { get; set; }
        public string GRP_HOME_IND { get; set; }
        public string CPG_DISABLED_IND { get; set; }
        public Nullable<decimal> GRP_LAST_MODIFIED { get; set; }
        public string GRP_STF_OID { get; set; }
        public Nullable<decimal> GRP_OWNER_TYPE { get; set; }
        public string GRP_OWNER_OID { get; set; }
        public Nullable<decimal> GRP_CONTEXT_TYPE { get; set; }
        public string GRP_OBJ_CONTEXT_OID { get; set; }
        public string GRP_CATEGORY { get; set; }
        public Nullable<System.DateTime> GRP_START_DATE { get; set; }
        public Nullable<System.DateTime> GRP_END_DATE { get; set; }
        public string GRP_PAGE_LABEL { get; set; }
        public string GRP_GRZ_OID { get; set; }
        public Nullable<decimal> GRP_PAGE_STATUS { get; set; }
        public string GRP_PLANNER_IND { get; set; }
        public string GRP_PUBLIC_IND { get; set; }
        public string GRP_COLOR { get; set; }
        public string GRP_ALLOW_FOLLOWERS_IND { get; set; }
        public string GRP_FIELDA_001 { get; set; }
        public string GRP_FIELDA_002 { get; set; }
        public string GRP_FIELDA_003 { get; set; }
        public string GRP_FIELDA_004 { get; set; }
        public string GRP_FIELDA_005 { get; set; }
        public string GRP_FIELDA_006 { get; set; }
        public string GRP_FIELDA_007 { get; set; }
        public string GRP_FIELDA_008 { get; set; }
        public string GRP_FIELDA_009 { get; set; }
        public string GRP_FIELDA_010 { get; set; }
        public string GRP_FIELDB_001 { get; set; }
        public string GRP_FIELDB_002 { get; set; }
        public string GRP_FIELDB_003 { get; set; }
        public string GRP_FIELDB_004 { get; set; }
        public string GRP_FIELDB_005 { get; set; }
        public string GRP_ENABLE_LOGGING { get; set; }
    }
}
