//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEALTH_LOG_COMPLAINT
    {
        public string HLC_OID { get; set; }
        public string HLC_HLG_OID { get; set; }
        public string HLC_COMPLAINT_CODE { get; set; }
        public string HLC_PRIMARY_IND { get; set; }
        public string HLC_COMMENT { get; set; }
        public string HLC_FIELDA_001 { get; set; }
        public string HLC_FIELDA_002 { get; set; }
        public string HLC_FIELDA_003 { get; set; }
        public string HLC_FIELDA_004 { get; set; }
        public string HLC_FIELDA_005 { get; set; }
        public string HLC_FIELDB_001 { get; set; }
        public string HLC_FIELDB_002 { get; set; }
        public string HLC_FIELDB_003 { get; set; }
        public string HLC_FIELDB_004 { get; set; }
        public string HLC_FIELDB_005 { get; set; }
        public string HLC_FIELDC_001 { get; set; }
        public string HLC_FIELDC_002 { get; set; }
        public string HLC_FIELDC_003 { get; set; }
        public string HLC_FIELDC_004 { get; set; }
        public string HLC_FIELDC_005 { get; set; }
        public string HLC_FIELDD_001 { get; set; }
        public Nullable<decimal> HLC_LAST_MODIFIED { get; set; }
    }
}
