//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEALTH_IMMUNIZATION_DOSE
    {
        public string HID_OID { get; set; }
        public string HID_STD_OID { get; set; }
        public string HID_HIS_OID { get; set; }
        public string HID_VACCINE_TYPE { get; set; }
        public Nullable<System.DateTime> HID_DATE { get; set; }
        public string HID_ROUTE { get; set; }
        public string HID_ADMINISTERED_BY { get; set; }
        public string HID_SITE_ADMINISTERED { get; set; }
        public string HID_LOT_NUMBER { get; set; }
        public string HID_MANUFACTURED_BY { get; set; }
        public string HID_SKIPPED_IND { get; set; }
        public string HID_WAIVER_IND { get; set; }
        public string HID_NO_DATE_IND { get; set; }
        public string HID_COMMENT { get; set; }
        public string HID_FIELDA_001 { get; set; }
        public string HID_FIELDA_002 { get; set; }
        public string HID_FIELDA_003 { get; set; }
        public string HID_FIELDA_004 { get; set; }
        public string HID_FIELDA_005 { get; set; }
        public string HID_FIELDB_001 { get; set; }
        public string HID_FIELDB_002 { get; set; }
        public string HID_FIELDC_001 { get; set; }
        public string HID_FIELDC_002 { get; set; }
        public string HID_FIELDC_003 { get; set; }
        public string HID_FIELDC_004 { get; set; }
        public string HID_FIELDC_005 { get; set; }
        public string HID_FIELDC_006 { get; set; }
        public string HID_FIELDC_007 { get; set; }
        public string HID_FIELDC_008 { get; set; }
        public string HID_FIELDC_009 { get; set; }
        public string HID_FIELDC_010 { get; set; }
        public string HID_FIELDD_001 { get; set; }
        public string HID_FIELDD_002 { get; set; }
        public string HID_FIELDD_003 { get; set; }
        public string HID_FIELDD_004 { get; set; }
        public string HID_FIELDD_005 { get; set; }
        public Nullable<decimal> HID_LAST_MODIFIED { get; set; }
    }
}
