//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_TEAM_MEMBER
    {
        public string ITM_OID { get; set; }
        public string ITM_STD_OID { get; set; }
        public string ITM_IEP_OID { get; set; }
        public string ITM_PSN_OID { get; set; }
        public string ITM_MEMBER_ROLE_CODE { get; set; }
        public string ITM_NAME_VIEW { get; set; }
        public string ITM_CHAIRPERSON_IND { get; set; }
        public string ITM_FORM_PRIORITY { get; set; }
        public string ITM_FIELDA_001 { get; set; }
        public string ITM_FIELDA_002 { get; set; }
        public string ITM_FIELDA_003 { get; set; }
        public string ITM_FIELDB_001 { get; set; }
        public string ITM_FIELDB_002 { get; set; }
        public string ITM_FIELDB_003 { get; set; }
        public string ITM_FIELDC_001 { get; set; }
        public string ITM_FIELDC_002 { get; set; }
        public string ITM_FIELDD_001 { get; set; }
        public Nullable<decimal> ITM_LAST_MODIFIED { get; set; }
    }
}
