//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_AMENDMENT
    {
        public string IAM_OID { get; set; }
        public string IAM_STD_OID { get; set; }
        public string IAM_IEP_OID { get; set; }
        public Nullable<System.DateTime> IAM_DATE { get; set; }
        public Nullable<System.DateTime> IAM_MEETING_DATE { get; set; }
        public string IAM_FIELDA_001 { get; set; }
        public string IAM_FIELDA_002 { get; set; }
        public string IAM_FIELDA_003 { get; set; }
        public string IAM_FIELDA_004 { get; set; }
        public string IAM_FIELDA_005 { get; set; }
        public string IAM_FIELDA_006 { get; set; }
        public string IAM_FIELDA_007 { get; set; }
        public string IAM_FIELDA_008 { get; set; }
        public string IAM_FIELDA_009 { get; set; }
        public string IAM_FIELDA_010 { get; set; }
        public string IAM_FIELDB_001 { get; set; }
        public string IAM_FIELDB_002 { get; set; }
        public string IAM_FIELDB_003 { get; set; }
        public string IAM_FIELDB_004 { get; set; }
        public string IAM_FIELDB_005 { get; set; }
        public string IAM_FIELDB_006 { get; set; }
        public string IAM_FIELDB_007 { get; set; }
        public string IAM_FIELDB_008 { get; set; }
        public string IAM_FIELDB_009 { get; set; }
        public string IAM_FIELDB_010 { get; set; }
        public string IAM_FIELDC_001 { get; set; }
        public string IAM_FIELDC_002 { get; set; }
        public string IAM_FIELDC_003 { get; set; }
        public string IAM_FIELDC_004 { get; set; }
        public string IAM_FIELDC_005 { get; set; }
        public string IAM_FIELDD_001 { get; set; }
        public string IAM_FIELDD_002 { get; set; }
        public string IAM_FIELDD_003 { get; set; }
        public string IAM_FIELDD_004 { get; set; }
        public string IAM_FIELDD_005 { get; set; }
        public Nullable<decimal> IAM_LAST_MODIFIED { get; set; }
    }
}
