//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNAL_ENTRY_CREDIT
    {
        public string JEC_OID { get; set; }
        public string JEC_PSN_OID { get; set; }
        public string JEC_SKL_OID { get; set; }
        public string JEC_STF_OID { get; set; }
        public string JEC_NAME_VIEW { get; set; }
        public string JEC_REF_NUMBER { get; set; }
        public string JEC_METHOD { get; set; }
        public Nullable<System.DateTime> JEC_DATE { get; set; }
        public string JEC_DESCRIPTION { get; set; }
        public string JEC_COMMENT { get; set; }
        public Nullable<decimal> JEC_AMOUNT { get; set; }
        public Nullable<decimal> JEC_AMOUNT_APPLIED { get; set; }
        public Nullable<decimal> JEC_AMOUNT_CREDIT { get; set; }
        public Nullable<decimal> JEC_LAST_MODIFIED { get; set; }
        public string JEC_REFUNDED_IND { get; set; }
        public string JEC_JCI_OID_REFUND { get; set; }
        public string JEC_STD_OID { get; set; }
        public Nullable<decimal> JEC_TIMESTAMP { get; set; }
        public string JEC_SKL_OID_APPLY { get; set; }
        public string JEC_DELETED_IND { get; set; }
        public string JEC_DELETED_BY_NAME_VIEW { get; set; }
        public Nullable<decimal> JEC_DELETED_AMOUNT { get; set; }
        public Nullable<decimal> JEC_DELETED_TIMESTAMP { get; set; }
    }
}
