//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCAL_REPOSITORY
    {
        public string LRP_OID { get; set; }
        public string LRP_NAME { get; set; }
        public string LRP_OWNER_ID { get; set; }
        public string LRP_OWNER_TYPE { get; set; }
        public string LRP_CFR_OID_ROOT_FOLDER { get; set; }
        public string LRP_REPO_TYPE { get; set; }
        public Nullable<decimal> LRP_LAST_MODIFIED { get; set; }
    }
}
