//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_RESOURCE
    {
        public string RSM_OID { get; set; }
        public string RSM_OBJECT_OID { get; set; }
        public string RSM_LOCALE { get; set; }
        public string RSM_KEY { get; set; }
        public string RSM_VALUE { get; set; }
        public string RSM_VALUE_LONG { get; set; }
        public Nullable<decimal> RSM_LAST_MODIFIED { get; set; }
    }
}
