//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE_MENU_ITEM
    {
        public string PMI_OID { get; set; }
        public string PMI_USR_OID { get; set; }
        public string PMI_GRP_OID { get; set; }
        public Nullable<decimal> PMI_LAST_MODIFIED { get; set; }
    }
}
