//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PD_ACTIVITY_GOAL_ALIGNMENT
    {
        public string PDN_OID { get; set; }
        public string PDN_PDC_OID { get; set; }
        public string PDN_PDG_OID { get; set; }
        public string PDN_FIELDA_001 { get; set; }
        public string PDN_FIELDA_002 { get; set; }
        public string PDN_FIELDA_003 { get; set; }
        public string PDN_FIELDB_001 { get; set; }
        public Nullable<decimal> PDN_LAST_MODIFIED { get; set; }
    }
}
