//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_RACE
    {
        public string RAC_OID { get; set; }
        public string RAC_PSN_OID { get; set; }
        public string RAC_RACE_CODE { get; set; }
        public string RAC_FIELDA_001 { get; set; }
        public string RAC_FIELDA_002 { get; set; }
        public string RAC_FIELDA_003 { get; set; }
        public Nullable<decimal> RAC_LAST_MODIFIED { get; set; }
    }
}
