//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_SET_INSTANCE
    {
        public string QSI_OID { get; set; }
        public string QSI_USR_OID { get; set; }
        public string QSI_GRP_OID { get; set; }
        public string QSI_QSD_OID { get; set; }
        public string QSI_COMPLETE_IND { get; set; }
        public Nullable<decimal> QSI_LAST_MODIFIED { get; set; }
        public string QSI_OBJ_CONTEXT_OID { get; set; }
    }
}
