//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECOMMENDATION_CONTROLS
    {
        public string REC_OID { get; set; }
        public string REC_SKL_OID { get; set; }
        public Nullable<System.DateTime> REC_START_DATE { get; set; }
        public Nullable<System.DateTime> REC_END_DATE { get; set; }
        public Nullable<decimal> REC_NUMBER_OF_RECOMMENDATIONS { get; set; }
        public string REC_ALLOW_COMMENTS_IND { get; set; }
        public Nullable<decimal> REC_SELECTION_TYPE { get; set; }
        public string REC_SELECTION_DEFINITION { get; set; }
        public Nullable<decimal> REC_LAST_MODIFIED { get; set; }
    }
}
