//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECORD_SET_KEY
    {
        public string RSK_OID { get; set; }
        public string RSK_RSN_OID { get; set; }
        public string RSK_OBJ_OID { get; set; }
        public Nullable<decimal> RSK_LAST_MODIFIED { get; set; }
    }
}
