//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_TABLE
    {
        public string RTB_OID { get; set; }
        public string RTB_ORG_OID_1 { get; set; }
        public string RTB_ORG_OID_2 { get; set; }
        public string RTB_ORG_OID_3 { get; set; }
        public string RTB_ORG_OID_4 { get; set; }
        public string RTB_ORG_OID_5 { get; set; }
        public string RTB_ORG_OID_OWNER { get; set; }
        public string RTB_RTB_OID { get; set; }
        public string RTB_TBL_OID { get; set; }
        public string RTB_USER_NAME { get; set; }
        public string RTB_CATEGORY { get; set; }
        public Nullable<decimal> RTB_CODE_LENGTH { get; set; }
        public string RTB_SYSTEM_ONLY_IND { get; set; }
        public string RTB_SCHOOL_OWNED_IND { get; set; }
        public string RTB_SEQUENCE_ORDER_IND { get; set; }
        public string RTB_CODE_RECORD_DEFINITION { get; set; }
        public Nullable<decimal> RTB_LAST_MODIFIED { get; set; }
        public string RTB_VIEW_FIELDS { get; set; }
        public string RTB_DDX_OID { get; set; }
    }
}
