//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_CODE_HIDE
    {
        public string RCH_OID { get; set; }
        public string RCH_SKL_OID { get; set; }
        public string RCH_RCD_OID { get; set; }
        public Nullable<decimal> RCH_LAST_MODIFIED { get; set; }
    }
}
