//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRIC_GRADE_LEVEL
    {
        public string RBG_OID { get; set; }
        public string RBG_RBD_OID { get; set; }
        public string RBG_GRADE_LEVEL { get; set; }
        public Nullable<decimal> RBG_LAST_MODIFIED { get; set; }
    }
}
