//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRIC_CRITERION
    {
        public string RBC_OID { get; set; }
        public string RBC_RBD_OID { get; set; }
        public string RBC_RBC_OID { get; set; }
        public string RBC_RRS_OID { get; set; }
        public Nullable<decimal> RBC_SEQUENCE_NUMBER { get; set; }
        public string RBC_NAME { get; set; }
        public string RBC_REPORT_DISPLAY { get; set; }
        public string RBC_COLUMN_HEADER { get; set; }
        public string RBC_DESCRIPTION { get; set; }
        public Nullable<decimal> RBC_LEVEL { get; set; }
        public Nullable<decimal> RBC_LEVEL_COUNT { get; set; }
        public Nullable<decimal> RBC_WEIGHT { get; set; }
        public Nullable<decimal> RBC_MAX_POINTS { get; set; }
        public string RBC_COMMENT { get; set; }
        public string RBC_DISCONTINUED_IND { get; set; }
        public string RBC_PATH { get; set; }
        public string RBC_TERM_MAP { get; set; }
        public Nullable<decimal> RBC_REPORT_TYPE { get; set; }
        public string RBC_DESCRIPTION_LOCALE_1 { get; set; }
        public string RBC_DESCRIPTION_LOCALE_2 { get; set; }
        public string RBC_DESCRIPTION_LOCALE_3 { get; set; }
        public string RBC_DESCRIPTION_LOCALE_4 { get; set; }
        public string RBC_DESCRIPTION_LOCALE_5 { get; set; }
        public string RBC_FIELDA_001 { get; set; }
        public string RBC_FIELDA_002 { get; set; }
        public string RBC_FIELDA_003 { get; set; }
        public string RBC_FIELDA_004 { get; set; }
        public string RBC_FIELDB_001 { get; set; }
        public string RBC_FIELDB_002 { get; set; }
        public string RBC_FIELDB_003 { get; set; }
        public string RBC_FIELDB_004 { get; set; }
        public string RBC_FIELDC_001 { get; set; }
        public string RBC_FIELDC_002 { get; set; }
        public string RBC_FIELDC_003 { get; set; }
        public string RBC_FIELDC_004 { get; set; }
        public string RBC_FIELDD_001 { get; set; }
        public string RBC_FIELDD_002 { get; set; }
        public string RBC_FIELDD_003 { get; set; }
        public string RBC_FIELDD_004 { get; set; }
        public Nullable<decimal> RBC_LAST_MODIFIED { get; set; }
    }
}
