//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_BUILD_TEACHER
    {
        public string BLT_OID { get; set; }
        public string BLT_STF_OID { get; set; }
        public string BLT_BLM_OID { get; set; }
        public string BLT_TRM_OID { get; set; }
        public string BLT_PRIMARY_TEACHER_IND { get; set; }
        public string BLT_TEACHER_ROLE { get; set; }
        public Nullable<decimal> BLT_LAST_MODIFIED { get; set; }
        public string BLT_TERM_MAP { get; set; }
        public string BLT_SCHEDULE_MATRIX { get; set; }
        public string BLT_SCHEDULE_DISPLAY { get; set; }
    }
}
