//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_TERM
    {
        public string TRM_OID { get; set; }
        public string TRM_SCH_OID { get; set; }
        public string TRM_TERM_CODE { get; set; }
        public string TRM_TERM_NAME { get; set; }
        public Nullable<decimal> TRM_COVERED_TERM_PER_YEAR { get; set; }
        public Nullable<decimal> TRM_BASE_TERMS_PER_YEAR { get; set; }
        public string TRM_BASE_TERM_COVER_MAP { get; set; }
        public string TRM_ALL_TERM_COVER_MAP { get; set; }
        public string TRM_GRADE_TERM_COVER_MAP { get; set; }
        public string TRM_ELEMENTARY_IND { get; set; }
        public Nullable<decimal> TRM_LAST_MODIFIED { get; set; }
        public string TRM_GUID { get; set; }
    }
}
