//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        public string SCH_OID { get; set; }
        public string SCH_CTX_OID { get; set; }
        public string SCH_SKL_OID { get; set; }
        public string SCH_SCHEDULE_NAME { get; set; }
        public Nullable<decimal> SCH_TERMS { get; set; }
        public string SCH_TERM_VIEW { get; set; }
        public Nullable<decimal> SCH_DAYS { get; set; }
        public Nullable<decimal> SCH_PERIODS { get; set; }
        public Nullable<System.DateTime> SCH_START_DATE { get; set; }
        public Nullable<System.DateTime> SCH_END_DATE { get; set; }
        public Nullable<System.DateTime> SCH_COMMIT_DATE { get; set; }
        public Nullable<decimal> SCH_STUDENTS_TOTAL { get; set; }
        public Nullable<decimal> SCH_STUDENTS_SATISFIED_TOTAL { get; set; }
        public string SCH_STUDENTS_SATISFIED_PERCENT { get; set; }
        public Nullable<decimal> SCH_REQUESTS_TOTAL { get; set; }
        public Nullable<decimal> SCH_REQUESTS_SATISFIED_TOTAL { get; set; }
        public string SCH_REQUESTS_SATISFIED_PERCENT { get; set; }
        public string SCH_SCHEDULE_EXPRESSION_MASK { get; set; }
        public string SCH_ROTATED_IND { get; set; }
        public string SCH_BUILD_SCENARIO_IND { get; set; }
        public string SCH_COMMITTED_SCENARIO_IND { get; set; }
        public Nullable<decimal> SCH_LAST_BUILD_TIME { get; set; }
        public Nullable<decimal> SCH_LAST_LOAD_TIME { get; set; }
        public string SCH_COMMENT { get; set; }
        public Nullable<decimal> SCH_TIME_SEGMENTS { get; set; }
        public Nullable<System.DateTime> SCH_LUNCH_START_TIME { get; set; }
        public Nullable<System.DateTime> SCH_LUNCH_END_TIME { get; set; }
        public Nullable<decimal> SCH_LUNCH_INTERVAL { get; set; }
        public Nullable<decimal> SCH_LUNCH_TABLE_COUNTS { get; set; }
        public Nullable<decimal> SCH_LUNCH_TABLE_CAPACITY { get; set; }
        public Nullable<decimal> SCH_LUNCH_ENTRY_DOORS { get; set; }
        public string SCH_LUNCH_SIMULTANEOUS_GROUP { get; set; }
        public string SCH_FIELDA_001 { get; set; }
        public string SCH_FIELDA_002 { get; set; }
        public string SCH_FIELDA_003 { get; set; }
        public string SCH_FIELDA_004 { get; set; }
        public string SCH_FIELDA_005 { get; set; }
        public string SCH_FIELDA_006 { get; set; }
        public string SCH_FIELDA_007 { get; set; }
        public string SCH_FIELDA_008 { get; set; }
        public string SCH_FIELDA_009 { get; set; }
        public string SCH_FIELDA_010 { get; set; }
        public string SCH_FIELDB_001 { get; set; }
        public string SCH_FIELDB_002 { get; set; }
        public string SCH_FIELDB_003 { get; set; }
        public string SCH_FIELDB_004 { get; set; }
        public string SCH_FIELDB_005 { get; set; }
        public Nullable<decimal> SCH_LAST_MODIFIED { get; set; }
        public Nullable<decimal> SCH_ELEMENTARY_DAYS { get; set; }
        public Nullable<decimal> SCH_ELEMENTARY_PERIODS { get; set; }
        public Nullable<decimal> SCH_ELEMENTARY_TERMS { get; set; }
        public Nullable<decimal> SCH_SCHEDULE_MODE { get; set; }
    }
}
