//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_FEEDBACK
    {
        public string SFB_OID { get; set; }
        public string SFB_SCH_OID { get; set; }
        public string SFB_RUN_TYPE { get; set; }
        public string SFB_DATA_TYPE { get; set; }
        public string SFB_LEVEL { get; set; }
        public string SFB_MESSAGE { get; set; }
        public string SFB_CODE { get; set; }
        public string SFB_RETURN_VALUE { get; set; }
        public Nullable<decimal> SFB_TIMESTAMP { get; set; }
        public string SFB_FIXED_IND { get; set; }
        public Nullable<decimal> SFB_LAST_MODIFIED { get; set; }
    }
}
