//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_MASTER_TEACHER_MATRIX
    {
        public string TMX_OID { get; set; }
        public string TMX_MMX_OID { get; set; }
        public string TMX_MTC_OID { get; set; }
        public Nullable<decimal> TMX_LAST_MODIFIED { get; set; }
    }
}
