//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHOOL_CAPACITY
    {
        public string SCA_OID { get; set; }
        public string SCA_CTX_OID { get; set; }
        public string SCA_SKL_OID { get; set; }
        public string SCA_PROGRAM_CODE { get; set; }
        public string SCA_SORT_CODE { get; set; }
        public string SCA_GRADE_LEVEL { get; set; }
        public Nullable<decimal> SCA_CAPACITY { get; set; }
        public Nullable<decimal> SCA_ASSIGN_LIMIT { get; set; }
        public Nullable<decimal> SCA_PROJECTION { get; set; }
        public Nullable<decimal> SCA_AFRICAN_ASSIGN { get; set; }
        public Nullable<decimal> SCA_AFRICAN_ACTUAL { get; set; }
        public Nullable<decimal> SCA_AFRICAN_WAITLIST { get; set; }
        public Nullable<decimal> SCA_ASIAN_ASSIGN { get; set; }
        public Nullable<decimal> SCA_ASIAN_ACTUAL { get; set; }
        public Nullable<decimal> SCA_ASIAN_WAITLIST { get; set; }
        public Nullable<decimal> SCA_CAUCASIAN_ASSIGN { get; set; }
        public Nullable<decimal> SCA_CAUCASIAN_ACTUAL { get; set; }
        public Nullable<decimal> SCA_CAUCASIAN_WAITLIST { get; set; }
        public Nullable<decimal> SCA_NATIVE_AMERICAN_ASSIGN { get; set; }
        public Nullable<decimal> SCA_NATIVE_AMERICAN_ACTUAL { get; set; }
        public Nullable<decimal> SCA_NATIVE_AMERICAN_WAITLIST { get; set; }
        public Nullable<decimal> SCA_PACIFIC_ISLANDS_ASSIGN { get; set; }
        public Nullable<decimal> SCA_PACIFIC_ISLANDS_ACTUAL { get; set; }
        public Nullable<decimal> SCA_PACIFIC_ISLANDS_WAITLIST { get; set; }
        public Nullable<decimal> SCA_HISPANIC_ASSIGN { get; set; }
        public Nullable<decimal> SCA_HISPANIC_ACTUAL { get; set; }
        public Nullable<decimal> SCA_HISPANIC_WAITLIST { get; set; }
        public Nullable<decimal> SCA_ELD_NONE { get; set; }
        public Nullable<decimal> SCA_ELD_1 { get; set; }
        public Nullable<decimal> SCA_ELD_2 { get; set; }
        public Nullable<decimal> SCA_ELD_3 { get; set; }
        public Nullable<decimal> SCA_ELD_4 { get; set; }
        public Nullable<decimal> SCA_ELD_5 { get; set; }
        public string SCA_FIELDA_001 { get; set; }
        public string SCA_FIELDA_002 { get; set; }
        public string SCA_FIELDA_003 { get; set; }
        public string SCA_FIELDA_004 { get; set; }
        public string SCA_FIELDA_005 { get; set; }
        public string SCA_FIELDA_006 { get; set; }
        public string SCA_FIELDA_007 { get; set; }
        public string SCA_FIELDA_008 { get; set; }
        public string SCA_FIELDA_009 { get; set; }
        public string SCA_FIELDA_010 { get; set; }
        public string SCA_FIELDA_011 { get; set; }
        public string SCA_FIELDA_012 { get; set; }
        public string SCA_FIELDA_013 { get; set; }
        public string SCA_FIELDA_014 { get; set; }
        public string SCA_FIELDA_015 { get; set; }
        public string SCA_FIELDA_016 { get; set; }
        public string SCA_FIELDA_017 { get; set; }
        public string SCA_FIELDA_018 { get; set; }
        public string SCA_FIELDA_019 { get; set; }
        public string SCA_FIELDA_020 { get; set; }
        public string SCA_FIELDB_001 { get; set; }
        public string SCA_FIELDB_002 { get; set; }
        public string SCA_FIELDB_003 { get; set; }
        public string SCA_FIELDB_004 { get; set; }
        public string SCA_FIELDB_005 { get; set; }
        public string SCA_FIELDB_006 { get; set; }
        public string SCA_FIELDB_007 { get; set; }
        public string SCA_FIELDB_008 { get; set; }
        public string SCA_FIELDB_009 { get; set; }
        public string SCA_FIELDB_010 { get; set; }
        public string SCA_FIELDC_001 { get; set; }
        public string SCA_FIELDC_002 { get; set; }
        public string SCA_FIELDC_003 { get; set; }
        public string SCA_FIELDC_004 { get; set; }
        public string SCA_FIELDC_005 { get; set; }
        public string SCA_FIELDC_006 { get; set; }
        public string SCA_FIELDC_007 { get; set; }
        public string SCA_FIELDC_008 { get; set; }
        public string SCA_FIELDC_009 { get; set; }
        public string SCA_FIELDC_010 { get; set; }
        public string SCA_FIELDD_001 { get; set; }
        public string SCA_FIELDD_002 { get; set; }
        public string SCA_FIELDD_003 { get; set; }
        public string SCA_FIELDD_004 { get; set; }
        public string SCA_FIELDD_005 { get; set; }
        public byte[] SCA_FIELDE_001 { get; set; }
        public byte[] SCA_FIELDE_002 { get; set; }
        public byte[] SCA_FIELDE_003 { get; set; }
        public Nullable<decimal> SCA_LAST_MODIFIED { get; set; }
        public string SCA_DISABLE_WAITLIST_IND { get; set; }
        public Nullable<decimal> SCA_ASSIGN_TOTAL { get; set; }
        public Nullable<decimal> SCA_ACTUAL_TOTAL { get; set; }
        public Nullable<decimal> SCA_WAITLIST_TOTAL { get; set; }
        public Nullable<decimal> SCA_WALK_ZONE_COUNT { get; set; }
        public Nullable<decimal> SCA_WALK_ZONE_LIMIT { get; set; }
        public Nullable<decimal> SCA_LEP { get; set; }
        public Nullable<decimal> SCA_NEVER_LEP { get; set; }
        public Nullable<decimal> SCA_FLEP { get; set; }
        public Nullable<decimal> SCA_MULTI_RACE_ASSIGN { get; set; }
        public Nullable<decimal> SCA_MULTI_RACE_ACTUAL { get; set; }
        public Nullable<decimal> SCA_MULTI_RACE_WAITLIST { get; set; }
    }
}
