//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_TAG_FIELD
    {
        public string SUF_OID { get; set; }
        public string SUF_SUT_OID { get; set; }
        public string SUF_FDD_OID { get; set; }
        public Nullable<decimal> SUF_LAST_MODIFIED { get; set; }
        public string SUF_FDX_OID { get; set; }
    }
}
