//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_CERTIFICATION
    {
        public string SFC_OID { get; set; }
        public string SFC_STF_OID { get; set; }
        public string SFC_CERTIFICATION_NUMBER { get; set; }
        public string SFC_TYPE { get; set; }
        public string SFC_FUNCTION { get; set; }
        public string SFC_SUBJECT_CODE { get; set; }
        public string SFC_INSTRUCTIONAL_LEVEL_CODE { get; set; }
        public Nullable<System.DateTime> SFC_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> SFC_EXPIRATION_DATE { get; set; }
        public string SFC_PRIMARY_IND { get; set; }
        public string SFC_FIELDA_001 { get; set; }
        public string SFC_FIELDA_002 { get; set; }
        public string SFC_FIELDA_003 { get; set; }
        public string SFC_FIELDA_004 { get; set; }
        public string SFC_FIELDA_005 { get; set; }
        public string SFC_FIELDB_001 { get; set; }
        public string SFC_FIELDB_002 { get; set; }
        public string SFC_FIELDB_003 { get; set; }
        public string SFC_FIELDC_001 { get; set; }
        public string SFC_FIELDC_002 { get; set; }
        public string SFC_FIELDD_001 { get; set; }
        public byte[] SFC_FIELDE_001 { get; set; }
        public Nullable<decimal> SFC_LAST_MODIFIED { get; set; }
    }
}
