//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_PD_ACTIVITY_REQUEST
    {
        public string SAR_OID { get; set; }
        public string SAR_STF_OID { get; set; }
        public string SAR_SDP_OID { get; set; }
        public string SAR_PDS_OID { get; set; }
        public Nullable<System.DateTime> SAR_DATE { get; set; }
        public Nullable<System.DateTime> SAR_TIME { get; set; }
        public Nullable<decimal> SAR_STATUS { get; set; }
        public string SAR_COMMENT { get; set; }
        public string SAR_FIELDA_001 { get; set; }
        public string SAR_FIELDA_002 { get; set; }
        public string SAR_FIELDA_003 { get; set; }
        public string SAR_FIELDB_001 { get; set; }
        public string SAR_FIELDB_002 { get; set; }
        public string SAR_FIELDC_001 { get; set; }
        public Nullable<decimal> SAR_LAST_MODIFIED { get; set; }
    }
}
