//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_POSITION
    {
        public string SFP_OID { get; set; }
        public string SFP_STF_OID { get; set; }
        public string SFP_SKL_OID { get; set; }
        public Nullable<System.DateTime> SFP_START_DATE { get; set; }
        public Nullable<System.DateTime> SFP_END_DATE { get; set; }
        public string SFP_JOB_CODE { get; set; }
        public string SFP_SITE_CODE { get; set; }
        public string SFP_SUBJECT_CODE { get; set; }
        public Nullable<decimal> SFP_FTE { get; set; }
        public string SFP_FIELDA_001 { get; set; }
        public string SFP_FIELDA_002 { get; set; }
        public string SFP_FIELDA_003 { get; set; }
        public string SFP_FIELDA_004 { get; set; }
        public string SFP_FIELDA_005 { get; set; }
        public string SFP_FIELDA_006 { get; set; }
        public string SFP_FIELDA_007 { get; set; }
        public string SFP_FIELDA_008 { get; set; }
        public string SFP_FIELDA_009 { get; set; }
        public string SFP_FIELDA_010 { get; set; }
        public string SFP_FIELDA_011 { get; set; }
        public string SFP_FIELDA_012 { get; set; }
        public string SFP_FIELDA_013 { get; set; }
        public string SFP_FIELDA_014 { get; set; }
        public string SFP_FIELDA_015 { get; set; }
        public string SFP_FIELDA_016 { get; set; }
        public string SFP_FIELDA_017 { get; set; }
        public string SFP_FIELDA_018 { get; set; }
        public string SFP_FIELDA_019 { get; set; }
        public string SFP_FIELDA_020 { get; set; }
        public string SFP_FIELDB_001 { get; set; }
        public string SFP_FIELDB_002 { get; set; }
        public string SFP_FIELDB_003 { get; set; }
        public string SFP_FIELDB_004 { get; set; }
        public string SFP_FIELDB_005 { get; set; }
        public string SFP_FIELDB_006 { get; set; }
        public string SFP_FIELDB_007 { get; set; }
        public string SFP_FIELDB_008 { get; set; }
        public string SFP_FIELDB_009 { get; set; }
        public string SFP_FIELDB_010 { get; set; }
        public string SFP_FIELDB_011 { get; set; }
        public string SFP_FIELDB_012 { get; set; }
        public string SFP_FIELDB_013 { get; set; }
        public string SFP_FIELDB_014 { get; set; }
        public string SFP_FIELDB_015 { get; set; }
        public string SFP_FIELDC_001 { get; set; }
        public string SFP_FIELDC_002 { get; set; }
        public string SFP_FIELDC_003 { get; set; }
        public string SFP_FIELDC_004 { get; set; }
        public string SFP_FIELDC_005 { get; set; }
        public string SFP_FIELDC_006 { get; set; }
        public string SFP_FIELDC_007 { get; set; }
        public string SFP_FIELDC_008 { get; set; }
        public string SFP_FIELDC_009 { get; set; }
        public string SFP_FIELDC_010 { get; set; }
        public string SFP_FIELDD_001 { get; set; }
        public byte[] SFP_FIELDE_001 { get; set; }
        public byte[] SFP_FIELDE_002 { get; set; }
        public Nullable<decimal> SFP_LAST_MODIFIED { get; set; }
        public string SFP_FIELDA_021 { get; set; }
        public string SFP_FIELDA_022 { get; set; }
        public string SFP_FIELDA_023 { get; set; }
        public string SFP_FIELDA_024 { get; set; }
        public string SFP_FIELDA_025 { get; set; }
        public string SFP_FIELDA_026 { get; set; }
        public string SFP_FIELDA_027 { get; set; }
        public string SFP_FIELDA_028 { get; set; }
        public string SFP_FIELDA_029 { get; set; }
        public string SFP_FIELDA_030 { get; set; }
        public string SFP_FIELDA_031 { get; set; }
        public string SFP_FIELDA_032 { get; set; }
        public string SFP_FIELDA_033 { get; set; }
        public string SFP_FIELDA_034 { get; set; }
        public string SFP_FIELDA_035 { get; set; }
        public string SFP_FIELDB_016 { get; set; }
        public string SFP_FIELDB_017 { get; set; }
        public string SFP_FIELDB_018 { get; set; }
        public string SFP_FIELDB_019 { get; set; }
        public string SFP_FIELDB_020 { get; set; }
        public string SFP_FIELDB_021 { get; set; }
        public string SFP_FIELDB_022 { get; set; }
        public string SFP_FIELDB_023 { get; set; }
        public string SFP_FIELDB_024 { get; set; }
        public string SFP_FIELDB_025 { get; set; }
        public string SFP_FIELDC_011 { get; set; }
        public string SFP_FIELDC_012 { get; set; }
        public string SFP_FIELDC_013 { get; set; }
        public string SFP_FIELDC_014 { get; set; }
        public string SFP_FIELDC_015 { get; set; }
        public string SFP_FIELDD_002 { get; set; }
        public string SFP_FIELDD_003 { get; set; }
        public string SFP_FIELDD_004 { get; set; }
    }
}
