//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_PD_ACTIVITY
    {
        public string SDA_OID { get; set; }
        public string SDA_STF_OID { get; set; }
        public string SDA_SDP_OID { get; set; }
        public string SDA_PDC_OID { get; set; }
        public string SDA_PDS_OID { get; set; }
        public string SDA_SCW_OID { get; set; }
        public string SDA_TITLE { get; set; }
        public string SDA_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> SDA_START_DATE { get; set; }
        public Nullable<System.DateTime> SDA_DATE_COMPLETED { get; set; }
        public string SDA_FORMAT { get; set; }
        public string SDA_CONTENT_AREA { get; set; }
        public string SDA_PROVIDER { get; set; }
        public Nullable<decimal> SDA_COST { get; set; }
        public string SDA_FUNDING_SOURCE { get; set; }
        public string SDA_GRADE_EARNED { get; set; }
        public Nullable<decimal> SDA_CREDIT { get; set; }
        public string SDA_CREDIT_TYPE { get; set; }
        public Nullable<decimal> SDA_HOURS { get; set; }
        public Nullable<decimal> SDA_CONTENT_POINTS { get; set; }
        public Nullable<decimal> SDA_PEDAGOGY_POINTS { get; set; }
        public Nullable<decimal> SDA_OTHER_POINTS { get; set; }
        public string SDA_STATUS { get; set; }
        public string SDA_PRIMARY_CERTIFICATION_IND { get; set; }
        public string SDA_USER_DEFINED_IND { get; set; }
        public string SDA_ACTION_PLAN_VIEW { get; set; }
        public string SDA_APPROVAL_VIEW { get; set; }
        public string SDA_FIELDA_001 { get; set; }
        public string SDA_FIELDA_002 { get; set; }
        public string SDA_FIELDA_003 { get; set; }
        public string SDA_FIELDA_004 { get; set; }
        public string SDA_FIELDA_005 { get; set; }
        public string SDA_FIELDA_006 { get; set; }
        public string SDA_FIELDA_007 { get; set; }
        public string SDA_FIELDA_008 { get; set; }
        public string SDA_FIELDB_001 { get; set; }
        public string SDA_FIELDB_002 { get; set; }
        public string SDA_FIELDB_003 { get; set; }
        public string SDA_FIELDB_004 { get; set; }
        public string SDA_FIELDC_001 { get; set; }
        public string SDA_FIELDC_002 { get; set; }
        public string SDA_FIELDD_001 { get; set; }
        public byte[] SDA_FIELDE_001 { get; set; }
        public byte[] SDA_FIELDE_002 { get; set; }
        public Nullable<decimal> SDA_LAST_MODIFIED { get; set; }
    }
}
