//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_SCHEDULE_ATTRIBUTES
    {
        public string SAS_OID { get; set; }
        public string SAS_STF_OID { get; set; }
        public string SAS_SKL_OID { get; set; }
        public string SAS_SCH_OID { get; set; }
        public string SAS_SCHD_INCLUDE_IND { get; set; }
        public string SAS_SCHD_ALWAYS_FREE_IND { get; set; }
        public string SAS_RMS_OID { get; set; }
        public string SAS_LOCATION_CODE { get; set; }
        public Nullable<decimal> SAS_SCHD_MAX_IN_A_ROW { get; set; }
        public Nullable<decimal> SAS_SCHD_MAX_PREPS { get; set; }
        public Nullable<decimal> SAS_SCHD_MAX_ROOMS { get; set; }
        public Nullable<decimal> SAS_SCHD_MAX_LOCATIONS { get; set; }
        public string SAS_PREFERRED_ROOM_ONLY_IND { get; set; }
        public string SAS_PREFERRED_LOCAT_ONLY_IND { get; set; }
        public Nullable<decimal> SAS_SCHD_TIME_PERCENT { get; set; }
        public string SAS_FIELDA_001 { get; set; }
        public string SAS_FIELDA_002 { get; set; }
        public string SAS_FIELDA_003 { get; set; }
        public string SAS_FIELDA_004 { get; set; }
        public string SAS_FIELDA_005 { get; set; }
        public string SAS_FIELDB_001 { get; set; }
        public string SAS_FIELDB_002 { get; set; }
        public string SAS_FIELDB_003 { get; set; }
        public Nullable<decimal> SAS_LAST_MODIFIED { get; set; }
        public string SAS_BALANCE_BY_TERM_IND { get; set; }
    }
}
