//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_PD_ACTIVITY_LOG
    {
        public string SAL_OID { get; set; }
        public string SAL_STF_OID { get; set; }
        public string SAL_SDA_OID { get; set; }
        public Nullable<System.DateTime> SAL_DATE { get; set; }
        public Nullable<System.DateTime> SAL_START_TIME { get; set; }
        public string SAL_SUMMARY { get; set; }
        public string SAL_DESCRIPTION { get; set; }
        public Nullable<decimal> SAL_HOURS { get; set; }
        public string SAL_FIELDA_001 { get; set; }
        public string SAL_FIELDA_002 { get; set; }
        public string SAL_FIELDA_003 { get; set; }
        public string SAL_FIELDB_001 { get; set; }
        public string SAL_FIELDB_002 { get; set; }
        public string SAL_FIELDC_001 { get; set; }
        public Nullable<decimal> SAL_LAST_MODIFIED { get; set; }
    }
}
