//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_DEGREE
    {
        public string SFD_OID { get; set; }
        public string SFD_STF_OID { get; set; }
        public Nullable<System.DateTime> SFD_DATE { get; set; }
        public string SFD_DEGREE { get; set; }
        public string SFD_TYPE { get; set; }
        public string SFD_SUBJECT { get; set; }
        public string SFD_INSTITUTION { get; set; }
        public string SFD_DISTINCTION { get; set; }
        public string SFD_FIELDA_001 { get; set; }
        public string SFD_FIELDA_002 { get; set; }
        public string SFD_FIELDA_003 { get; set; }
        public string SFD_FIELDA_004 { get; set; }
        public string SFD_FIELDA_005 { get; set; }
        public string SFD_FIELDB_001 { get; set; }
        public string SFD_FIELDB_002 { get; set; }
        public string SFD_FIELDB_003 { get; set; }
        public string SFD_FIELDC_001 { get; set; }
        public string SFD_FIELDC_002 { get; set; }
        public string SFD_FIELDD_001 { get; set; }
        public byte[] SFD_FIELDE_001 { get; set; }
        public byte[] SFD_FIELDE_002 { get; set; }
        public Nullable<decimal> SFD_LAST_MODIFIED { get; set; }
    }
}
