//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_LEAVE
    {
        public string SFL_OID { get; set; }
        public string SFL_STF_OID { get; set; }
        public string SFL_SKL_OID { get; set; }
        public string SFL_STF_OID_SUB { get; set; }
        public Nullable<System.DateTime> SFL_START_DATE { get; set; }
        public Nullable<System.DateTime> SFL_END_DATE { get; set; }
        public string SFL_REASON_CODE { get; set; }
        public string SFL_ACCRUAL_TYPE { get; set; }
        public Nullable<decimal> SFL_CARRY_OVER { get; set; }
        public string SFL_COMMENT { get; set; }
        public string SFL_FIELDA_001 { get; set; }
        public string SFL_FIELDA_002 { get; set; }
        public string SFL_FIELDA_003 { get; set; }
        public string SFL_FIELDB_001 { get; set; }
        public string SFL_FIELDB_002 { get; set; }
        public string SFL_FIELDD_001 { get; set; }
        public Nullable<decimal> SFL_LAST_MODIFIED { get; set; }
    }
}
