//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ED_PLAN_MEETING
    {
        public string SEM_OID { get; set; }
        public string SEM_SEP_OID { get; set; }
        public Nullable<System.DateTime> SEM_DATE { get; set; }
        public Nullable<System.DateTime> SEM_TIME { get; set; }
        public string SEM_LOCATION { get; set; }
        public string SEM_DETAILS { get; set; }
        public string SEM_FIELDA_001 { get; set; }
        public string SEM_FIELDA_002 { get; set; }
        public string SEM_FIELDA_003 { get; set; }
        public string SEM_FIELDA_004 { get; set; }
        public string SEM_FIELDA_005 { get; set; }
        public string SEM_FIELDA_006 { get; set; }
        public string SEM_FIELDA_007 { get; set; }
        public string SEM_FIELDA_008 { get; set; }
        public string SEM_FIELDA_009 { get; set; }
        public string SEM_FIELDA_010 { get; set; }
        public string SEM_FIELDA_011 { get; set; }
        public string SEM_FIELDA_012 { get; set; }
        public string SEM_FIELDA_013 { get; set; }
        public string SEM_FIELDA_014 { get; set; }
        public string SEM_FIELDA_015 { get; set; }
        public string SEM_FIELDA_016 { get; set; }
        public string SEM_FIELDA_017 { get; set; }
        public string SEM_FIELDA_018 { get; set; }
        public string SEM_FIELDA_019 { get; set; }
        public string SEM_FIELDA_020 { get; set; }
        public string SEM_FIELDB_001 { get; set; }
        public string SEM_FIELDB_002 { get; set; }
        public string SEM_FIELDB_003 { get; set; }
        public string SEM_FIELDB_004 { get; set; }
        public string SEM_FIELDB_005 { get; set; }
        public string SEM_FIELDB_006 { get; set; }
        public string SEM_FIELDB_007 { get; set; }
        public string SEM_FIELDB_008 { get; set; }
        public string SEM_FIELDB_009 { get; set; }
        public string SEM_FIELDB_010 { get; set; }
        public string SEM_FIELDC_001 { get; set; }
        public string SEM_FIELDC_002 { get; set; }
        public string SEM_FIELDD_001 { get; set; }
        public string SEM_FIELDD_002 { get; set; }
        public Nullable<decimal> SEM_LAST_MODIFIED { get; set; }
    }
}
