//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_CONTACT
    {
        public string CTJ_OID { get; set; }
        public string CTJ_STD_OID { get; set; }
        public string CTJ_CNT_OID { get; set; }
        public string CTJ_RELATIONSHIP_CODE { get; set; }
        public Nullable<decimal> CTJ_EMERGENCY_PRIORITY { get; set; }
        public string CTJ_GRADE_MAIL_IND { get; set; }
        public string CTJ_CONDUCT_MAIL_IND { get; set; }
        public string CTJ_OTHER_MAIL_IND { get; set; }
        public string CTJ_RECEIVE_EMAIL_IND { get; set; }
        public string CTJ_LIVES_WITH_IND { get; set; }
        public string CTJ_PORTAL_ACCESS_IND { get; set; }
        public string CTJ_FIELDA_001 { get; set; }
        public string CTJ_FIELDA_002 { get; set; }
        public string CTJ_FIELDA_003 { get; set; }
        public string CTJ_FIELDA_004 { get; set; }
        public string CTJ_FIELDA_005 { get; set; }
        public string CTJ_FIELDA_006 { get; set; }
        public string CTJ_FIELDA_007 { get; set; }
        public string CTJ_FIELDA_008 { get; set; }
        public string CTJ_FIELDA_009 { get; set; }
        public string CTJ_FIELDA_010 { get; set; }
        public string CTJ_FIELDA_011 { get; set; }
        public string CTJ_FIELDA_012 { get; set; }
        public string CTJ_FIELDA_013 { get; set; }
        public string CTJ_FIELDA_014 { get; set; }
        public string CTJ_FIELDA_015 { get; set; }
        public string CTJ_FIELDB_001 { get; set; }
        public string CTJ_FIELDB_002 { get; set; }
        public string CTJ_FIELDB_003 { get; set; }
        public string CTJ_FIELDB_004 { get; set; }
        public string CTJ_FIELDB_005 { get; set; }
        public string CTJ_FIELDB_006 { get; set; }
        public string CTJ_FIELDB_007 { get; set; }
        public string CTJ_FIELDB_008 { get; set; }
        public string CTJ_FIELDB_009 { get; set; }
        public string CTJ_FIELDB_010 { get; set; }
        public string CTJ_FIELDC_001 { get; set; }
        public string CTJ_FIELDC_002 { get; set; }
        public string CTJ_FIELDC_003 { get; set; }
        public string CTJ_FIELDC_004 { get; set; }
        public string CTJ_FIELDC_005 { get; set; }
        public string CTJ_FIELDD_001 { get; set; }
        public Nullable<decimal> CTJ_LAST_MODIFIED { get; set; }
    }
}
