//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ACCOMMODATION
    {
        public string IAC_OID { get; set; }
        public string IAC_STD_OID { get; set; }
        public string IAC_IEP_OID { get; set; }
        public string IAC_SEP_OID { get; set; }
        public string IAC_DDX_OID { get; set; }
        public string IAC_STF_OID { get; set; }
        public Nullable<decimal> IAC_PLAN_TYPE { get; set; }
        public Nullable<System.DateTime> IAC_IMPLEMENTATION_DATE { get; set; }
        public string IAC_CONTENT_AREA { get; set; }
        public string IAC_CATEGORY { get; set; }
        public string IAC_NAME { get; set; }
        public string IAC_TYPE { get; set; }
        public string IAC_DESCRIPTION { get; set; }
        public string IAC_FIELDA_001 { get; set; }
        public string IAC_FIELDA_002 { get; set; }
        public string IAC_FIELDA_003 { get; set; }
        public string IAC_FIELDA_004 { get; set; }
        public string IAC_FIELDA_005 { get; set; }
        public string IAC_FIELDA_006 { get; set; }
        public string IAC_FIELDA_007 { get; set; }
        public string IAC_FIELDA_008 { get; set; }
        public string IAC_FIELDA_009 { get; set; }
        public string IAC_FIELDA_010 { get; set; }
        public string IAC_FIELDB_001 { get; set; }
        public string IAC_FIELDB_002 { get; set; }
        public string IAC_FIELDB_003 { get; set; }
        public string IAC_FIELDB_004 { get; set; }
        public string IAC_FIELDB_005 { get; set; }
        public string IAC_FIELDB_006 { get; set; }
        public string IAC_FIELDB_007 { get; set; }
        public string IAC_FIELDB_008 { get; set; }
        public string IAC_FIELDB_009 { get; set; }
        public string IAC_FIELDB_010 { get; set; }
        public string IAC_FIELDC_001 { get; set; }
        public string IAC_FIELDC_002 { get; set; }
        public string IAC_FIELDC_003 { get; set; }
        public string IAC_FIELDC_004 { get; set; }
        public string IAC_FIELDC_005 { get; set; }
        public string IAC_FIELDD_001 { get; set; }
        public string IAC_FIELDD_002 { get; set; }
        public Nullable<decimal> IAC_LAST_MODIFIED { get; set; }
        public string IAC_FIELDD_003 { get; set; }
        public string IAC_FIELDD_004 { get; set; }
        public string IAC_FIELDD_005 { get; set; }
    }
}
