//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_SCHEDULE_CHANGE_TERM
    {
        public string SCT_OID { get; set; }
        public string SCT_SCC_OID { get; set; }
        public string SCT_TRM_OID { get; set; }
        public Nullable<decimal> SCT_LAST_MODIFIED { get; set; }
    }
}
