//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_CONDUCT_ACTION
    {
        public string ACT_OID { get; set; }
        public string ACT_STD_OID { get; set; }
        public string ACT_SKL_OID { get; set; }
        public string ACT_CND_OID { get; set; }
        public string ACT_ACTION_CODE { get; set; }
        public Nullable<System.DateTime> ACT_START_DATE { get; set; }
        public Nullable<System.DateTime> ACT_END_DATE { get; set; }
        public Nullable<decimal> ACT_PENALTY_TIME { get; set; }
        public Nullable<decimal> ACT_SERVED_TIME { get; set; }
        public string ACT_ACTION_DESCRIPTION { get; set; }
        public string ACT_CLOSED_IND { get; set; }
        public string ACT_FIELDA_001 { get; set; }
        public string ACT_FIELDA_002 { get; set; }
        public string ACT_FIELDA_003 { get; set; }
        public string ACT_FIELDA_004 { get; set; }
        public string ACT_FIELDA_005 { get; set; }
        public string ACT_FIELDA_006 { get; set; }
        public string ACT_FIELDA_007 { get; set; }
        public string ACT_FIELDA_008 { get; set; }
        public string ACT_FIELDA_009 { get; set; }
        public string ACT_FIELDA_010 { get; set; }
        public string ACT_FIELDB_001 { get; set; }
        public string ACT_FIELDB_002 { get; set; }
        public string ACT_FIELDC_001 { get; set; }
        public Nullable<decimal> ACT_LAST_MODIFIED { get; set; }
    }
}
