//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_SCHEDULE_GROUP
    {
        public string SSG_OID { get; set; }
        public string SSG_SKL_OID { get; set; }
        public string SSG_CTX_OID { get; set; }
        public string SSG_CSK_OID { get; set; }
        public string SSG_SSG_OID { get; set; }
        public string SSG_ID { get; set; }
        public string SSG_DESCRIPTION { get; set; }
        public string SSG_FIELDA_001 { get; set; }
        public string SSG_FIELDA_002 { get; set; }
        public string SSG_FIELDA_003 { get; set; }
        public string SSG_FIELDA_004 { get; set; }
        public string SSG_FIELDA_005 { get; set; }
        public string SSG_FIELDB_001 { get; set; }
        public string SSG_FIELDB_002 { get; set; }
        public string SSG_FIELDB_003 { get; set; }
        public Nullable<decimal> SSG_LAST_MODIFIED { get; set; }
    }
}
