//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_SCHOOL_CHOICE
    {
        public string SSS_OID { get; set; }
        public string SSS_STD_OID { get; set; }
        public string SSS_STC_OID { get; set; }
        public string SSS_FIELDA_001 { get; set; }
        public string SSS_FIELDA_002 { get; set; }
        public string SSS_FIELDA_003 { get; set; }
        public string SSS_FIELDA_004 { get; set; }
        public string SSS_FIELDA_005 { get; set; }
        public string SSS_FIELDA_006 { get; set; }
        public string SSS_FIELDA_007 { get; set; }
        public string SSS_FIELDA_008 { get; set; }
        public string SSS_FIELDA_009 { get; set; }
        public string SSS_FIELDA_010 { get; set; }
        public string SSS_FIELDA_011 { get; set; }
        public string SSS_FIELDA_012 { get; set; }
        public string SSS_FIELDA_013 { get; set; }
        public string SSS_FIELDA_014 { get; set; }
        public string SSS_FIELDA_015 { get; set; }
        public string SSS_FIELDA_016 { get; set; }
        public string SSS_FIELDA_017 { get; set; }
        public string SSS_FIELDA_018 { get; set; }
        public string SSS_FIELDA_019 { get; set; }
        public string SSS_FIELDA_020 { get; set; }
        public string SSS_FIELDA_021 { get; set; }
        public string SSS_FIELDA_022 { get; set; }
        public string SSS_FIELDA_023 { get; set; }
        public string SSS_FIELDA_024 { get; set; }
        public string SSS_FIELDA_025 { get; set; }
        public string SSS_FIELDA_026 { get; set; }
        public string SSS_FIELDA_027 { get; set; }
        public string SSS_FIELDA_028 { get; set; }
        public string SSS_FIELDA_029 { get; set; }
        public string SSS_FIELDA_030 { get; set; }
        public string SSS_FIELDA_031 { get; set; }
        public string SSS_FIELDA_032 { get; set; }
        public string SSS_FIELDA_033 { get; set; }
        public string SSS_FIELDA_034 { get; set; }
        public string SSS_FIELDA_035 { get; set; }
        public string SSS_FIELDA_036 { get; set; }
        public string SSS_FIELDA_037 { get; set; }
        public string SSS_FIELDA_038 { get; set; }
        public string SSS_FIELDA_039 { get; set; }
        public string SSS_FIELDA_040 { get; set; }
        public string SSS_FIELDA_041 { get; set; }
        public string SSS_FIELDA_042 { get; set; }
        public string SSS_FIELDA_043 { get; set; }
        public string SSS_FIELDA_044 { get; set; }
        public string SSS_FIELDA_045 { get; set; }
        public string SSS_FIELDA_046 { get; set; }
        public string SSS_FIELDA_047 { get; set; }
        public string SSS_FIELDA_048 { get; set; }
        public string SSS_FIELDA_049 { get; set; }
        public string SSS_FIELDA_050 { get; set; }
        public string SSS_FIELDB_001 { get; set; }
        public string SSS_FIELDB_002 { get; set; }
        public string SSS_FIELDB_003 { get; set; }
        public string SSS_FIELDB_004 { get; set; }
        public string SSS_FIELDB_005 { get; set; }
        public string SSS_FIELDB_006 { get; set; }
        public string SSS_FIELDB_007 { get; set; }
        public string SSS_FIELDB_008 { get; set; }
        public string SSS_FIELDB_009 { get; set; }
        public string SSS_FIELDB_010 { get; set; }
        public string SSS_FIELDB_011 { get; set; }
        public string SSS_FIELDB_012 { get; set; }
        public string SSS_FIELDB_013 { get; set; }
        public string SSS_FIELDB_014 { get; set; }
        public string SSS_FIELDB_015 { get; set; }
        public string SSS_FIELDB_016 { get; set; }
        public string SSS_FIELDB_017 { get; set; }
        public string SSS_FIELDB_018 { get; set; }
        public string SSS_FIELDB_019 { get; set; }
        public string SSS_FIELDB_020 { get; set; }
        public string SSS_FIELDB_021 { get; set; }
        public string SSS_FIELDB_022 { get; set; }
        public string SSS_FIELDB_023 { get; set; }
        public string SSS_FIELDB_024 { get; set; }
        public string SSS_FIELDB_025 { get; set; }
        public string SSS_FIELDC_001 { get; set; }
        public string SSS_FIELDC_002 { get; set; }
        public string SSS_FIELDC_003 { get; set; }
        public string SSS_FIELDC_004 { get; set; }
        public string SSS_FIELDC_005 { get; set; }
        public string SSS_FIELDC_006 { get; set; }
        public string SSS_FIELDC_007 { get; set; }
        public string SSS_FIELDC_008 { get; set; }
        public string SSS_FIELDC_009 { get; set; }
        public string SSS_FIELDC_010 { get; set; }
        public string SSS_FIELDC_011 { get; set; }
        public string SSS_FIELDC_012 { get; set; }
        public string SSS_FIELDC_013 { get; set; }
        public string SSS_FIELDC_014 { get; set; }
        public string SSS_FIELDC_015 { get; set; }
        public string SSS_FIELDD_001 { get; set; }
        public string SSS_FIELDD_002 { get; set; }
        public string SSS_FIELDD_003 { get; set; }
        public string SSS_FIELDD_004 { get; set; }
        public string SSS_FIELDD_005 { get; set; }
        public string SSS_FIELDD_006 { get; set; }
        public string SSS_FIELDD_007 { get; set; }
        public string SSS_FIELDD_008 { get; set; }
        public string SSS_FIELDD_009 { get; set; }
        public string SSS_FIELDD_010 { get; set; }
        public byte[] SSS_FIELDE_001 { get; set; }
        public byte[] SSS_FIELDE_002 { get; set; }
        public byte[] SSS_FIELDE_003 { get; set; }
        public byte[] SSS_FIELDE_004 { get; set; }
        public byte[] SSS_FIELDE_005 { get; set; }
        public string SSS_FIELDO_001 { get; set; }
        public string SSS_FIELDO_002 { get; set; }
        public string SSS_FIELDO_003 { get; set; }
        public string SSS_FIELDO_004 { get; set; }
        public string SSS_FIELDO_005 { get; set; }
        public Nullable<decimal> SSS_LAST_MODIFIED { get; set; }
        public string SSS_SCA_OID { get; set; }
    }
}
