//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_QUALIFICATION_LIST
    {
        public string QLS_OID { get; set; }
        public string QLS_ORG_OID_1 { get; set; }
        public string QLS_ORG_OID_2 { get; set; }
        public string QLS_ORG_OID_3 { get; set; }
        public string QLS_ORG_OID_4 { get; set; }
        public string QLS_ORG_OID_5 { get; set; }
        public string QLS_NAME { get; set; }
        public string QLS_CATEGORY { get; set; }
        public Nullable<decimal> QLS_PRIORITY { get; set; }
        public string QLS_DEFINITION { get; set; }
        public Nullable<decimal> QLS_LAST_MODIFIED { get; set; }
    }
}
