//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_CONDUCT_ACTION_DATE
    {
        public string SCS_OID { get; set; }
        public string SCS_STD_OID { get; set; }
        public string SCS_ACT_OID { get; set; }
        public string SCS_ATT_OID { get; set; }
        public Nullable<decimal> SCS_TYPE { get; set; }
        public Nullable<System.DateTime> SCS_DATE { get; set; }
        public Nullable<System.DateTime> SCS_SCHED_DATE { get; set; }
        public string SCS_SESSION_1_IND { get; set; }
        public string SCS_SESSION_2_IND { get; set; }
        public string SCS_SESSION_3_IND { get; set; }
        public string SCS_COMMENT { get; set; }
        public string SCS_COMMENT_2 { get; set; }
        public string SCS_COMMENT_3 { get; set; }
        public Nullable<decimal> SCS_LAST_MODIFIED { get; set; }
    }
}
