//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_REQUEST_ADJUSTMENT
    {
        public string REA_OID { get; set; }
        public string REA_STD_OID { get; set; }
        public string REA_CTX_OID { get; set; }
        public string REA_SKL_OID { get; set; }
        public string REA_CSK_OID { get; set; }
        public string REA_USR_OID { get; set; }
        public Nullable<decimal> REA_TYPE_CODE { get; set; }
        public string REA_COMMENT { get; set; }
        public string REA_MST_OID_SOURCE { get; set; }
        public Nullable<decimal> REA_MST_SOURCE_COLUMN { get; set; }
        public string REA_FIELDA_001 { get; set; }
        public string REA_FIELDA_002 { get; set; }
        public string REA_FIELDA_003 { get; set; }
        public string REA_FIELDA_004 { get; set; }
        public string REA_FIELDA_005 { get; set; }
        public string REA_FIELDA_006 { get; set; }
        public string REA_FIELDA_007 { get; set; }
        public string REA_FIELDA_008 { get; set; }
        public string REA_FIELDA_009 { get; set; }
        public string REA_FIELDA_010 { get; set; }
        public string REA_FIELDB_001 { get; set; }
        public string REA_FIELDB_002 { get; set; }
        public string REA_FIELDB_003 { get; set; }
        public string REA_FIELDB_004 { get; set; }
        public string REA_FIELDB_005 { get; set; }
        public string REA_FIELDB_006 { get; set; }
        public string REA_FIELDB_007 { get; set; }
        public string REA_FIELDB_008 { get; set; }
        public string REA_FIELDB_009 { get; set; }
        public string REA_FIELDB_010 { get; set; }
        public string REA_FIELDC_001 { get; set; }
        public string REA_FIELDC_002 { get; set; }
        public string REA_FIELDC_003 { get; set; }
        public string REA_FIELDC_004 { get; set; }
        public string REA_FIELDC_005 { get; set; }
        public Nullable<decimal> REA_LAST_MODIFIED { get; set; }
    }
}
