//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_SCHEDULE_ATTRIBUTES
    {
        public string SSA_OID { get; set; }
        public string SSA_STD_OID { get; set; }
        public string SSA_SKL_OID { get; set; }
        public string SSA_SCH_OID { get; set; }
        public string SSA_SCHD_INCLUDE_IND { get; set; }
        public string SSA_SCHD_STUDY_EXCLUDE_IND { get; set; }
        public Nullable<decimal> SSA_SCHD_PRIORITY { get; set; }
        public Nullable<decimal> SSA_SCHD_WEIGHT { get; set; }
        public string SSA_SCHD_LOCK_IND { get; set; }
        public string SSA_SCHD_TEAM_CODE { get; set; }
        public string SSA_SCHD_HOUSE_CODE { get; set; }
        public string SSA_SCHD_PLATOON_CODE { get; set; }
        public string SSA_SCHD_BALANCE_CODE { get; set; }
        public string SSA_UNAVAILABLE_TERM_MAP { get; set; }
        public string SSA_UNAVAILABLE_SCHED_MATRIX { get; set; }
        public string SSA_UNAVAILABLE_SCHED_DISPLAY { get; set; }
        public string SSA_STATIC_TEAM_IND { get; set; }
        public string SSA_STATIC_HOUSE_IND { get; set; }
        public string SSA_FIELDA_001 { get; set; }
        public string SSA_FIELDA_002 { get; set; }
        public string SSA_FIELDA_003 { get; set; }
        public string SSA_FIELDA_004 { get; set; }
        public string SSA_FIELDA_005 { get; set; }
        public string SSA_FIELDB_001 { get; set; }
        public string SSA_FIELDB_002 { get; set; }
        public string SSA_FIELDB_003 { get; set; }
        public Nullable<decimal> SSA_LAST_MODIFIED { get; set; }
    }
}
