//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_SCHEDULE_CHANGE
    {
        public string SCC_OID { get; set; }
        public string SCC_STD_OID { get; set; }
        public string SCC_SCH_OID { get; set; }
        public string SCC_MST_OID { get; set; }
        public string SCC_USR_OID { get; set; }
        public string SCC_MST_OID_EXCHANGE_01 { get; set; }
        public string SCC_MST_OID_EXCHANGE_02 { get; set; }
        public Nullable<System.DateTime> SCC_DATE { get; set; }
        public string SCC_CHANGE_TYPE_CODE { get; set; }
        public string SCC_CHANGE_REASON_CODE { get; set; }
        public string SCC_SCHEDULE_DISPLAY { get; set; }
        public string SCC_USER_VIEW { get; set; }
        public Nullable<decimal> SCC_TIMESTAMP { get; set; }
        public string SCC_FIELDA_001 { get; set; }
        public string SCC_FIELDA_002 { get; set; }
        public string SCC_FIELDA_003 { get; set; }
        public string SCC_FIELDB_001 { get; set; }
        public string SCC_FIELDB_002 { get; set; }
        public Nullable<decimal> SCC_LAST_MODIFIED { get; set; }
        public string SCC_QAN_CODE { get; set; }
    }
}
