//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_DISABILITY
    {
        public string IDB_OID { get; set; }
        public string IDB_STD_OID { get; set; }
        public string IDB_IEP_OID { get; set; }
        public string IDB_SEP_OID { get; set; }
        public Nullable<decimal> IDB_PLAN_TYPE { get; set; }
        public string IDB_DISABILITY_CODE { get; set; }
        public string IDB_PRIMARY_IND { get; set; }
        public string IDB_TRANSPORTATION_IND { get; set; }
        public string IDB_FIELDA_001 { get; set; }
        public string IDB_FIELDA_002 { get; set; }
        public string IDB_FIELDA_003 { get; set; }
        public string IDB_FIELDB_001 { get; set; }
        public string IDB_FIELDB_002 { get; set; }
        public string IDB_FIELDC_001 { get; set; }
        public string IDB_FIELDD_001 { get; set; }
        public Nullable<decimal> IDB_LAST_MODIFIED { get; set; }
    }
}
