//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIPTION
    {
        public string SUB_OID { get; set; }
        public string SUB_SDF_OID { get; set; }
        public string SUB_PSN_OID { get; set; }
        public string SUB_STD_OID { get; set; }
        public string SUB_PARAMETER { get; set; }
        public string SUB_USE_EMAIL1 { get; set; }
        public string SUB_USE_EMAIL2 { get; set; }
        public Nullable<decimal> SUB_LAST_MODIFIED { get; set; }
    }
}
