//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARGET_GRADE_ADJUSTED
    {
        public string TGA_OID { get; set; }
        public string TGA_TGR_OID { get; set; }
        public string TGA_CSK_OID { get; set; }
        public string TGA_CTX_OID { get; set; }
        public string TGA_ORIG_GRADE { get; set; }
        public string TGA_ADJ_GRADE { get; set; }
        public string TGA_FIELDA_001 { get; set; }
        public string TGA_FIELDA_002 { get; set; }
        public string TGA_FIELDA_003 { get; set; }
        public string TGA_FIELDA_004 { get; set; }
        public string TGA_FIELDA_005 { get; set; }
        public string TGA_FIELDB_001 { get; set; }
        public string TGA_FIELDB_002 { get; set; }
        public string TGA_FIELDB_003 { get; set; }
        public string TGA_FIELDB_004 { get; set; }
        public string TGA_FIELDB_005 { get; set; }
        public string TGA_FIELDC_001 { get; set; }
        public string TGA_FIELDC_002 { get; set; }
        public Nullable<decimal> TGA_LAST_MODIFIED { get; set; }
    }
}
