//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ROLE_SCHOOL
    {
        public string URS_OID { get; set; }
        public string URS_URO_OID { get; set; }
        public string URS_SKL_OID { get; set; }
        public Nullable<decimal> URS_LAST_MODIFIED { get; set; }
    }
}
