//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_CONVERSION
    {
        public string ZCV_OID { get; set; }
        public string ZCV_ZJB_OID { get; set; }
        public Nullable<System.DateTime> ZCV_RUN_DATE { get; set; }
        public Nullable<System.DateTime> ZCV_RUN_TIME { get; set; }
        public Nullable<decimal> ZCV_DURATION { get; set; }
        public Nullable<decimal> ZCV_ERRORS { get; set; }
        public Nullable<decimal> ZCV_WARNINGS { get; set; }
        public Nullable<decimal> ZCV_INFOS { get; set; }
        public byte[] ZCV_COMMENTS { get; set; }
        public Nullable<decimal> ZCV_LAST_MODIFIED { get; set; }
    }
}
