//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_CONVERSION_FIELD_STAT
    {
        public string ZFS_OID { get; set; }
        public string ZFS_ZTS_OID { get; set; }
        public string ZFS_ZFM_OID { get; set; }
        public Nullable<decimal> ZFS_UNIQUE_VALUES { get; set; }
        public Nullable<decimal> ZFS_REF_CODES_ADDED { get; set; }
        public Nullable<decimal> ZFS_NON_EMPTY_VALUES { get; set; }
        public Nullable<decimal> ZFS_ORPHANS { get; set; }
        public string ZFS_MESSAGE { get; set; }
        public Nullable<decimal> ZFS_LAST_MODIFIED { get; set; }
    }
}
