//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_EXPRESSION
    {
        public string ZXL_OID { get; set; }
        public string ZXL_NAME { get; set; }
        public string ZXL_EXPRESSION { get; set; }
        public byte[] ZXL_COMMENTS { get; set; }
        public Nullable<decimal> ZXL_LAST_MODIFIED { get; set; }
    }
}
