//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Setup.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_JOB_MAP_TABLE
    {
        public string ZJT_OID { get; set; }
        public string ZJT_ZJB_OID { get; set; }
        public string ZJT_ZTM_OID { get; set; }
        public Nullable<decimal> ZJT_SEQUENCE_NUMBER { get; set; }
        public string ZJT_DISABLED_IND { get; set; }
        public Nullable<decimal> ZJT_LAST_MODIFIED { get; set; }
    }
}
