//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityFile
    {
        public Nullable<int> SCHYEAR { get; set; }
        public string ZONE { get; set; }
        public string SCH { get; set; }
        public string PROGRAMCODE { get; set; }
        public string SORTFLAG { get; set; }
        public string GRADE { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<decimal> AssignLimit { get; set; }
        public Nullable<decimal> Projection { get; set; }
        public Nullable<decimal> BlackAssign { get; set; }
        public Nullable<decimal> WhiteAssign { get; set; }
        public Nullable<decimal> HispanicAssign { get; set; }
        public Nullable<decimal> AsianAssign { get; set; }
        public Nullable<decimal> NativeAmericanAssign { get; set; }
        public Nullable<decimal> InWalkZoneAssign { get; set; }
        public Nullable<decimal> BlackActual { get; set; }
        public Nullable<decimal> WhiteActual { get; set; }
        public Nullable<decimal> AsianActual { get; set; }
        public Nullable<decimal> HispanicActual { get; set; }
        public Nullable<decimal> NativeAmericanActual { get; set; }
        public Nullable<decimal> BlackWaitlist { get; set; }
        public Nullable<decimal> WhiteWaitlist { get; set; }
        public Nullable<decimal> AsianWaitlist { get; set; }
        public Nullable<decimal> HispanicWaitlist { get; set; }
        public Nullable<decimal> NativeAmericanWaitlist { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastUpdateAction { get; set; }
        public string LastUpdateUserID { get; set; }
        public Nullable<decimal> IsLep { get; set; }
        public Nullable<decimal> IsFlep { get; set; }
        public Nullable<decimal> IsNeverLep { get; set; }
        public Nullable<decimal> ELD1 { get; set; }
        public Nullable<decimal> ELD2 { get; set; }
        public Nullable<decimal> ELD3 { get; set; }
        public Nullable<decimal> ELD4 { get; set; }
        public Nullable<decimal> ELD5 { get; set; }
        public Nullable<decimal> ELDNone { get; set; }
        public string InclusionCodes { get; set; }
    }
}
