//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoSchMatrix
    {
        public string SchYear { get; set; }
        public short Version { get; set; }
        public bool isCurrVer { get; set; }
        public string HZone { get; set; }
        public string Geo { get; set; }
        public string Grade { get; set; }
        public string Sch { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string LastUpdateAction { get; set; }
        public string LastUpdateUserID { get; set; }
    }
}
