//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetSchoolDescriptionReport
    {
        public string SchoolID { get; set; }
        public Nullable<decimal> SchoolYear { get; set; }
        public string SchoolName { get; set; }
        public string uniformpolicy { get; set; }
        public string uniformpolicydesc { get; set; }
        public string SpecialFeatures { get; set; }
    }
}
