//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogGetSchoolInterestList
    {
        public int GetSchoolInterestListID { get; set; }
        public Nullable<int> WebServiceCallID { get; set; }
        public string SchoolYear { get; set; }
        public string School { get; set; }
        public string Grade { get; set; }
        public string ProgramCode { get; set; }
        public string AssignmentWalkEligibilityStatus { get; set; }
        public string TransEligible { get; set; }
        public string Tier { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Logitude { get; set; }
        public string NumClasses { get; set; }
        public string Eligibility { get; set; }
        public Nullable<double> StraightLineDistance { get; set; }
        public string SortClause { get; set; }
        public string SchoolName { get; set; }
        public string InputSchoolYear { get; set; }
        public string InputGrade { get; set; }
        public Nullable<int> InputX { get; set; }
        public Nullable<int> InputY { get; set; }
        public string InputSiblingSchList { get; set; }
        public string InputAddressID { get; set; }
    }
}
