//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogValidSchoolChoice
    {
        public int GetSchoolChoicesID { get; set; }
        public Nullable<int> WebServiceCallID { get; set; }
        public string SchoolYear { get; set; }
        public string School { get; set; }
        public string Grade { get; set; }
        public string ProgramCode { get; set; }
        public string AssignmentWalkEligibilityStatus { get; set; }
        public string TransEligible { get; set; }
        public string Tier { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Logitude { get; set; }
        public Nullable<int> NumClasses { get; set; }
        public string Eligibility { get; set; }
        public Nullable<double> StraightLineDistance { get; set; }
        public string SortClause { get; set; }
        public string SchoolName { get; set; }
        public string InputSchoolYear { get; set; }
        public string InputGrade { get; set; }
        public string InputZipCode { get; set; }
        public Nullable<int> InputX { get; set; }
        public Nullable<int> InputY { get; set; }
        public string InputSiblingSchList { get; set; }
        public string InputStuZipCode { get; set; }
        public string WebService { get; set; }
        public string InputAddressID { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<double> WalkingDistance { get; set; }
        public Nullable<double> LineDistance { get; set; }
        public string InputStreetNumber { get; set; }
        public string InputStreet { get; set; }
        public Nullable<bool> IsExamSchool { get; set; }
        public Nullable<bool> IsSpecAdmissions { get; set; }
        public string schhours1 { get; set; }
        public string SubProgramCode { get; set; }
        public string DataKey { get; set; }
        public string SchoolYearMyBPS { get; set; }
        public string WebSiteNode { get; set; }
        public string SPVersion { get; set; }
        public bool isNotInFinalResults { get; set; }
        public string TYPE { get; set; }
    }
}
