//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogWebServiceCall
    {
        public int WebServiceCallID { get; set; }
        public string URL { get; set; }
        public Nullable<int> HTTPStatusCode { get; set; }
        public Nullable<System.DateTime> TransactionDateAndTime { get; set; }
        public string version { get; set; }
        public string WebService { get; set; }
    }
}
