//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousYear_English_Math_Grade5_Transcript
    {
        public string SchoolYear { get; set; }
        public string Studentno { get; set; }
        public string schoolid { get; set; }
        public string SchName { get; set; }
        public string Grade { get; set; }
        public string Season { get; set; }
        public string DeptCode { get; set; }
        public string CourseNumber { get; set; }
        public string SchoolCourseDescription { get; set; }
        public string RubricName { get; set; }
        public Nullable<decimal> RubricSeq { get; set; }
        public string AWC_Ind { get; set; }
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string CourseScore { get; set; }
        public decimal Score { get; set; }
        public int ScoreRounded { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
