//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundDetail
    {
        public int RND_Schyear { get; set; }
        public int RND_RoundNum { get; set; }
        public Nullable<System.DateTime> RND_RoundEndDate { get; set; }
        public int RND_RoundDetailID { get; set; }
        public Nullable<System.DateTime> RND_RoundStartDate { get; set; }
    }
}
