//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolFacility
    {
        public string schyear { get; set; }
        public string sch { get; set; }
        public Nullable<bool> hasauditorium { get; set; }
        public Nullable<bool> haslibrary { get; set; }
        public Nullable<bool> hasplayground { get; set; }
        public Nullable<bool> hasathleticfield { get; set; }
        public Nullable<bool> hassciencelab { get; set; }
        public Nullable<bool> hascomputerlab { get; set; }
        public Nullable<bool> haspool { get; set; }
        public Nullable<bool> hascafeteria { get; set; }
        public Nullable<bool> hasmusicroom { get; set; }
        public Nullable<bool> hasartroom { get; set; }
        public Nullable<bool> hasoutdoorclassroom { get; set; }
        public Nullable<bool> hasgymnasium { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public string HandicappedAccess { get; set; }
    }
}
