//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolChoicesForStudentCallRank
    {
        public System.Guid SchoolRankID { get; set; }
        public int CallID { get; set; }
        public string ProgramCode { get; set; }
        public string School { get; set; }
        public int Rank { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual SchoolChoicesForStudentCallResult SchoolChoicesForStudentCallResult { get; set; }
    }
}
