//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class schoollocation
    {
        public string sch { get; set; }
        public string schname_23 { get; set; }
        public string address { get; set; }
        public string zip { get; set; }
        public string CustomDescription { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> CityOfBostonX { get; set; }
        public Nullable<double> CityOfBostonY { get; set; }
        public Nullable<int> addressID { get; set; }
    }
}
