//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolLanguagesNew
    {
        public string SchYear { get; set; }
        public string Sch { get; set; }
        public Nullable<bool> English { get; set; }
        public Nullable<bool> Spanish { get; set; }
        public Nullable<bool> CapeVerdeanCreole { get; set; }
        public Nullable<bool> Chinese { get; set; }
        public Nullable<bool> HaitianCreole { get; set; }
        public Nullable<bool> Portugese { get; set; }
        public Nullable<bool> Somali { get; set; }
        public Nullable<bool> Vietnamese { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public string Other4 { get; set; }
        public string Other5 { get; set; }
        public string Other6 { get; set; }
        public string Other7 { get; set; }
        public string Other8 { get; set; }
    }
}
