//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchSelection
    {
        public string StudentNo { get; set; }
        public Nullable<int> SchYear { get; set; }
        public string Sch { get; set; }
        public string Grade { get; set; }
        public string ProgCode { get; set; }
        public Nullable<int> Rank { get; set; }
        public string SubProgSelections { get; set; }
        public string AppNo { get; set; }
        public string AppType { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string CaseID { get; set; }
        public Nullable<int> RoundNo { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastUpdateAction { get; set; }
        public string LastUpdateUserid { get; set; }
    }
}
