//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentneedmonitor
    {
        public string studentno { get; set; }
        public int OneToOneMonitor { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
