//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentChoiceCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentChoiceCase()
        {
            this.StudentSchoolChoices = new HashSet<StudentSchoolChoice>();
        }
    
        public int sccId { get; set; }
        public Nullable<int> sccStdId { get; set; }
        public string sccSTC_OID { get; set; }
        public string sccSTD_OID { get; set; }
        public string sccSTC_ID { get; set; }
        public string sccStudentLocalId { get; set; }
        public System.DateTime sccSTC_LAST_MODIFIED { get; set; }
        public System.DateTime sccLastUpdate { get; set; }
        public string sccRound { get; set; }
        public string sccCaseType { get; set; }
        public string sccCaseStatus { get; set; }
        public bool sccValidate { get; set; }
        public bool sccNeedChoiceRun { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSchoolChoice> StudentSchoolChoices { get; set; }
    }
}
