//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentYearForXYSetup
    {
        public string StudentNo { get; set; }
        public int SchYear { get; set; }
        public string Apt { get; set; }
        public string StreetNo { get; set; }
        public string Street { get; set; }
        public string Zip { get; set; }
        public string Geo { get; set; }
        public string Hdist { get; set; }
        public string Hzone { get; set; }
        public string DipPoints { get; set; }
        public string Food { get; set; }
        public string LangPref { get; set; }
        public string Hphone { get; set; }
        public string ParentIdA { get; set; }
        public string ParentIdB { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string LastUpdateAction { get; set; }
        public string LastUpdateUserId { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    }
}
