//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDir
    {
        public string studentno { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string sex { get; set; }
        public string race { get; set; }
        public string IsHispanic { get; set; }
        public string IsBlack { get; set; }
        public string IsWhite { get; set; }
        public string IsAsian { get; set; }
        public string IsNatAmer { get; set; }
        public string IsPacIsland { get; set; }
        public string cityofbirth { get; set; }
        public string stateofbirth { get; set; }
        public string country { get; set; }
        public Nullable<int> satid { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public string updateaction { get; set; }
        public string updateuserid { get; set; }
        public string sasid { get; set; }
    }
}
