//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentELLSchedule
    {
        public string SchYear { get; set; }
        public string Studentno { get; set; }
        public string SchoolName { get; set; }
        public string Sch { get; set; }
        public string Grade { get; set; }
        public string HomeLanguage { get; set; }
        public string Term { get; set; }
        public string CourseDescription { get; set; }
        public string Course { get; set; }
        public string Section { get; set; }
        public string CourseSection { get; set; }
        public string ScheduleDisplay { get; set; }
        public string RoomNumber { get; set; }
        public string teacherID { get; set; }
        public string teacherName { get; set; }
        public string ESLInstructionType { get; set; }
        public string ESLMinutes { get; set; }
        public string ESLSection { get; set; }
    }
}
