//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSchool
    {
        public Nullable<decimal> SchYear { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchName_f { get; set; }
        public string schname_10 { get; set; }
        public string schname_15 { get; set; }
        public string Schname { get; set; }
        public string schname_23 { get; set; }
        public string SchType { get; set; }
        public string SchLevel { get; set; }
        public string schZone { get; set; }
        public string Statecd { get; set; }
        public string bpslevelrank { get; set; }
        public int isDistrict { get; set; }
        public int isPilot { get; set; }
        public int isCharter { get; set; }
        public Nullable<int> strandspergrade { get; set; }
        public string schoolsizepergrade { get; set; }
        public string GradeGroup { get; set; }
        public string Campus1Address1 { get; set; }
        public string Campus2Address1 { get; set; }
        public string Campus1City { get; set; }
        public string Campus1State { get; set; }
        public string Campus1Zip { get; set; }
        public Nullable<int> Campus1Address2 { get; set; }
        public Nullable<int> Campus2Address2 { get; set; }
        public Nullable<int> Campus2City { get; set; }
        public Nullable<int> Campus2State { get; set; }
        public Nullable<int> Campus2Zip { get; set; }
        public string schhours1 { get; set; }
        public string schPhone { get; set; }
        public string schfax { get; set; }
        public string ocrcode { get; set; }
        public string Zone { get; set; }
        public string rc { get; set; }
        public string ELLType { get; set; }
        public string isalted { get; set; }
        public string iscitywide { get; set; }
        public string ishandicappedaccess { get; set; }
        public string ishasfulltimenurse { get; set; }
        public string triad { get; set; }
        public string Cluster { get; set; }
        public string ceebcode { get; set; }
        public string gradelevel { get; set; }
        public string mailing_cluster { get; set; }
        public string multiprimlang { get; set; }
        public string schemail { get; set; }
        public string AdminName { get; set; }
        public string AdminEmail { get; set; }
        public string Admin1Name { get; set; }
        public string Admin1Email { get; set; }
        public string admin1emplid { get; set; }
        public string admin1title { get; set; }
        public string admin1phone { get; set; }
        public string Admin2Name { get; set; }
        public string Admin2Email { get; set; }
        public string admin2emplid { get; set; }
        public string admin2title { get; set; }
        public string admin2phone { get; set; }
        public string startgrade { get; set; }
        public string EndGrade { get; set; }
        public Nullable<int> schgroup { get; set; }
        public int isAWCSchool { get; set; }
    }
}
