//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStudentSchoolChoice
    {
        public string sccSTD_OID { get; set; }
        public string sccSTC_OID { get; set; }
        public string sccSTC_ID { get; set; }
        public string sscSSS_OID { get; set; }
        public string sscSCA_OID { get; set; }
        public string SKL_OID { get; set; }
        public string CONTEXT_ID { get; set; }
        public Nullable<int> sccStdId { get; set; }
        public string STD_LocalID { get; set; }
        public System.DateTime STD_LastUpdate { get; set; }
        public string sscSchoolId { get; set; }
        public string sscProgramId { get; set; }
        public string sscGradeLevel { get; set; }
        public Nullable<int> sscRank { get; set; }
        public string sscReviewStatus { get; set; }
        public Nullable<System.DateTime> sscReviewDate { get; set; }
        public string sscSchoolEligiblity { get; set; }
        public Nullable<double> sscStraightLineDistnace { get; set; }
        public Nullable<double> sscWalkDistance { get; set; }
        public string sscTransportationEligbility { get; set; }
        public string sccRound { get; set; }
        public string sccCaseType { get; set; }
    }
}
