//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.BPSInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewContinousChoice
    {
        public string Studentno { get; set; }
        public string SchoolID { get; set; }
        public string Tier { get; set; }
        public string ProgramCode { get; set; }
        public string Grade { get; set; }
        public string SchoolType { get; set; }
        public Nullable<double> StraightLineDistance { get; set; }
        public Nullable<double> WalkDistance { get; set; }
        public string TransEligible { get; set; }
        public string Eligibility { get; set; }
    }
}
