//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESS_LOG
    {
        public string ALG_OID { get; set; }
        public Nullable<decimal> ALG_APPLICATION_CONTEXT { get; set; }
        public string ALG_CONTACT_IND { get; set; }
        public string ALG_STUDENT_IND { get; set; }
        public string ALG_STAFF_IND { get; set; }
        public string ALG_NAV_ID { get; set; }
        public Nullable<decimal> ALG_TIMESTAMP { get; set; }
        public Nullable<decimal> ALG_HITS { get; set; }
        public string ALG_HOST { get; set; }
        public Nullable<decimal> ALG_LAST_MODIFIED { get; set; }
        public string ALG_MOBILE { get; set; }
    }
}
