//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_VISIBILITY
    {
        public string CRV_OID { get; set; }
        public string CRV_CRS_OID { get; set; }
        public string CRV_SKL_OID { get; set; }
        public Nullable<decimal> CRV_LAST_MODIFIED { get; set; }
    }
}
