//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRICULUM_CONTENT
    {
        public string CCO_OID { get; set; }
        public string CCO_CTI_OID { get; set; }
        public string CCO_CNA_OID { get; set; }
        public Nullable<decimal> CCO_LAST_MODIFIED { get; set; }
    }
}
