//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_FIELD_CONFIG
    {
        public string FDD_OID { get; set; }
        public string FDD_FLD_OID { get; set; }
        public string FDD_ORG_OID_1 { get; set; }
        public string FDD_ORG_OID_2 { get; set; }
        public string FDD_ORG_OID_3 { get; set; }
        public string FDD_ORG_OID_4 { get; set; }
        public string FDD_ORG_OID_5 { get; set; }
        public string FDD_RTB_OID { get; set; }
        public Nullable<decimal> FDD_SEQUENCE_NUMBER { get; set; }
        public string FDD_USER_NAME_LONG { get; set; }
        public string FDD_USER_NAME_SHORT { get; set; }
        public string FDD_USER_TYPE { get; set; }
        public Nullable<decimal> FDD_USER_LENGTH { get; set; }
        public Nullable<decimal> FDD_USER_DECIMAL { get; set; }
        public string FDD_DEFAULT_VALUE { get; set; }
        public string FDD_VALIDATE_EXP_IDS { get; set; }
        public string FDD_ENABLED_IND { get; set; }
        public string FDD_UPDATE_IND { get; set; }
        public string FDD_REQUIRED_IND { get; set; }
        public string FDD_READ_ONLY_IND { get; set; }
        public string FDD_VALID_REF_ONLY_IND { get; set; }
        public string FDD_SPELL_CHECK_IND { get; set; }
        public Nullable<decimal> FDD_LIST_WIDTH { get; set; }
        public string FDD_LIST_CONTROL { get; set; }
        public string FDD_LIST_EDIT_IND { get; set; }
        public Nullable<decimal> FDD_DETAIL_WIDTH { get; set; }
        public string FDD_DETAIL_CONTROL { get; set; }
        public string FDD_MSK_OID_DISPLAY { get; set; }
        public string FDD_MSK_OID_SAVE { get; set; }
        public string FDD_CLC_OID { get; set; }
        public string FDD_VAL_OID { get; set; }
        public string FDD_DEPENDENCY { get; set; }
        public string FDD_ACCESS_CODE { get; set; }
        public string FDD_ALIAS { get; set; }
        public string FDD_FINAL_IND { get; set; }
        public string FDD_DEFAULT_SUFFIX { get; set; }
        public Nullable<decimal> FDD_FIELD_AUDIT_TYPE { get; set; }
        public Nullable<decimal> FDD_LAST_MODIFIED { get; set; }
        public string FDD_DESCRIPTION { get; set; }
        public string FDD_HELP_ENABLED { get; set; }
        public string FDD_CBT_OID { get; set; }
        public string FDD_LOCAL_IND { get; set; }
    }
}
