//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_FIELD_EXTENDED
    {
        public string FDX_OID { get; set; }
        public string FDX_FDD_OID { get; set; }
        public string FDX_TBX_OID { get; set; }
        public string FDX_RTB_OID { get; set; }
        public Nullable<decimal> FDX_SEQUENCE_NUMBER { get; set; }
        public string FDX_USER_NAME_LONG { get; set; }
        public string FDX_USER_NAME_SHORT { get; set; }
        public string FDX_USER_TYPE { get; set; }
        public Nullable<decimal> FDX_USER_LENGTH { get; set; }
        public Nullable<decimal> FDX_USER_DECIMAL { get; set; }
        public string FDX_DEFAULT_VALUE { get; set; }
        public string FDX_ENABLED_IND { get; set; }
        public string FDX_UPDATE_IND { get; set; }
        public string FDX_REQUIRED_IND { get; set; }
        public string FDX_READ_ONLY_IND { get; set; }
        public string FDX_VALID_REF_ONLY_IND { get; set; }
        public string FDX_SPELL_CHECK_IND { get; set; }
        public Nullable<decimal> FDX_LIST_WIDTH { get; set; }
        public string FDX_LIST_CONTROL { get; set; }
        public string FDX_LIST_EDIT_IND { get; set; }
        public Nullable<decimal> FDX_DETAIL_WIDTH { get; set; }
        public string FDX_DETAIL_CONTROL { get; set; }
        public string FDX_MSK_OID_DISPLAY { get; set; }
        public string FDX_MSK_OID_SAVE { get; set; }
        public string FDX_CLC_OID { get; set; }
        public string FDX_VAL_OID { get; set; }
        public string FDX_ACCESS_CODE { get; set; }
        public string FDX_DEPENDENCY { get; set; }
        public string FDX_ALIAS { get; set; }
        public string FDX_FINAL_IND { get; set; }
        public string FDX_FIELDA_001 { get; set; }
        public string FDX_FIELDA_002 { get; set; }
        public string FDX_FIELDA_003 { get; set; }
        public string FDX_FIELDA_004 { get; set; }
        public string FDX_FIELDA_005 { get; set; }
        public string FDX_FIELDA_006 { get; set; }
        public string FDX_FIELDA_007 { get; set; }
        public string FDX_FIELDA_008 { get; set; }
        public string FDX_FIELDA_009 { get; set; }
        public string FDX_FIELDA_010 { get; set; }
        public string FDX_FIELDA_011 { get; set; }
        public string FDX_FIELDA_012 { get; set; }
        public string FDX_FIELDA_013 { get; set; }
        public string FDX_FIELDA_014 { get; set; }
        public string FDX_FIELDA_015 { get; set; }
        public string FDX_FIELDB_001 { get; set; }
        public string FDX_FIELDB_002 { get; set; }
        public string FDX_FIELDB_003 { get; set; }
        public string FDX_FIELDB_004 { get; set; }
        public string FDX_FIELDB_005 { get; set; }
        public string FDX_FIELDB_006 { get; set; }
        public string FDX_FIELDB_007 { get; set; }
        public string FDX_FIELDB_008 { get; set; }
        public string FDX_FIELDB_009 { get; set; }
        public string FDX_FIELDB_010 { get; set; }
        public string FDX_FIELDB_011 { get; set; }
        public string FDX_FIELDB_012 { get; set; }
        public string FDX_FIELDB_013 { get; set; }
        public string FDX_FIELDB_014 { get; set; }
        public string FDX_FIELDB_015 { get; set; }
        public string FDX_FIELDC_001 { get; set; }
        public string FDX_FIELDC_002 { get; set; }
        public string FDX_FIELDC_003 { get; set; }
        public string FDX_FIELDC_004 { get; set; }
        public string FDX_FIELDC_005 { get; set; }
        public string FDX_FIELDD_001 { get; set; }
        public string FDX_FIELDD_002 { get; set; }
        public Nullable<decimal> FDX_LAST_MODIFIED { get; set; }
        public string FDX_CBT_OID { get; set; }
        public Nullable<decimal> FDX_AUDIT_TYPE { get; set; }
        public string FDX_LOCAL_IND { get; set; }
    }
}
