//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_TABLE
    {
        public string TBL_OID { get; set; }
        public Nullable<decimal> TBL_SEQUENCE_NUMBER { get; set; }
        public string TBL_DATABASE_NAME { get; set; }
        public string TBL_CLASS_NAME { get; set; }
        public string TBL_PARENT_CLASS_NAME { get; set; }
        public string TBL_XML_TAG_NAME { get; set; }
        public string TBL_OBJECT_PREFIX { get; set; }
        public string TBL_SECURITY_OBJECT_PREFIX { get; set; }
        public Nullable<decimal> TBL_LAST_MODIFIED { get; set; }
        public string TBL_UNIQUE_FIELDS { get; set; }
    }
}
