//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_CALCULATE_FIELD
    {
        public string CLC_OID { get; set; }
        public string CLC_ORG_OID_1 { get; set; }
        public string CLC_ORG_OID_2 { get; set; }
        public string CLC_ORG_OID_3 { get; set; }
        public string CLC_ORG_OID_4 { get; set; }
        public string CLC_ORG_OID_5 { get; set; }
        public string CLC_PRC_OID { get; set; }
        public string CLC_NAME { get; set; }
        public string CLC_DESCRIPTION { get; set; }
        public string CLC_CALCULATED_EXPRESSION { get; set; }
        public Nullable<decimal> CLC_LAST_MODIFIED { get; set; }
    }
}
