//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_DICTIONARY_EXTENDED
    {
        public string DDX_OID { get; set; }
        public string DDX_ORG_OID_1 { get; set; }
        public string DDX_ORG_OID_2 { get; set; }
        public string DDX_ORG_OID_3 { get; set; }
        public string DDX_ORG_OID_4 { get; set; }
        public string DDX_ORG_OID_5 { get; set; }
        public string DDX_DDX_OID { get; set; }
        public string DDX_ID { get; set; }
        public string DDX_NAME { get; set; }
        public string DDX_DESCRIPTION { get; set; }
        public string DDX_CATEGORY { get; set; }
        public Nullable<decimal> DDX_SEQUENCE_NUMBER { get; set; }
        public string DDX_HEALTH_IND { get; set; }
        public string DDX_SPED_IND { get; set; }
        public string DDX_PD_IND { get; set; }
        public string DDX_GEN_ED_PLAN_IND { get; set; }
        public string DDX_ICON_FILENAME { get; set; }
        public string DDX_FIELDA_001 { get; set; }
        public string DDX_FIELDA_002 { get; set; }
        public string DDX_FIELDA_003 { get; set; }
        public string DDX_FIELDA_004 { get; set; }
        public string DDX_FIELDA_005 { get; set; }
        public string DDX_FIELDA_006 { get; set; }
        public string DDX_FIELDA_007 { get; set; }
        public string DDX_FIELDA_008 { get; set; }
        public string DDX_FIELDA_009 { get; set; }
        public string DDX_FIELDA_010 { get; set; }
        public string DDX_FIELDA_011 { get; set; }
        public string DDX_FIELDA_012 { get; set; }
        public string DDX_FIELDA_013 { get; set; }
        public string DDX_FIELDA_014 { get; set; }
        public string DDX_FIELDA_015 { get; set; }
        public string DDX_FIELDA_016 { get; set; }
        public string DDX_FIELDA_017 { get; set; }
        public string DDX_FIELDA_018 { get; set; }
        public string DDX_FIELDA_019 { get; set; }
        public string DDX_FIELDA_020 { get; set; }
        public string DDX_FIELDB_001 { get; set; }
        public string DDX_FIELDB_002 { get; set; }
        public string DDX_FIELDB_003 { get; set; }
        public string DDX_FIELDB_004 { get; set; }
        public string DDX_FIELDB_005 { get; set; }
        public string DDX_FIELDB_006 { get; set; }
        public string DDX_FIELDB_007 { get; set; }
        public string DDX_FIELDB_008 { get; set; }
        public string DDX_FIELDB_009 { get; set; }
        public string DDX_FIELDB_010 { get; set; }
        public string DDX_FIELDB_011 { get; set; }
        public string DDX_FIELDB_012 { get; set; }
        public string DDX_FIELDB_013 { get; set; }
        public string DDX_FIELDB_014 { get; set; }
        public string DDX_FIELDB_015 { get; set; }
        public string DDX_FIELDB_016 { get; set; }
        public string DDX_FIELDB_017 { get; set; }
        public string DDX_FIELDB_018 { get; set; }
        public string DDX_FIELDB_019 { get; set; }
        public string DDX_FIELDB_020 { get; set; }
        public string DDX_FIELDC_001 { get; set; }
        public string DDX_FIELDC_002 { get; set; }
        public string DDX_FIELDC_003 { get; set; }
        public string DDX_FIELDC_004 { get; set; }
        public string DDX_FIELDC_005 { get; set; }
        public string DDX_FIELDC_006 { get; set; }
        public string DDX_FIELDC_007 { get; set; }
        public string DDX_FIELDC_008 { get; set; }
        public string DDX_FIELDD_001 { get; set; }
        public string DDX_FIELDD_002 { get; set; }
        public Nullable<decimal> DDX_LAST_MODIFIED { get; set; }
        public Nullable<decimal> DDX_AUDIT_TYPE { get; set; }
    }
}
