//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_TRANSACTION
    {
        public string DTR_OID { get; set; }
        public string DTR_ORG_OID_1 { get; set; }
        public string DTR_ORG_OID_2 { get; set; }
        public string DTR_ORG_OID_3 { get; set; }
        public string DTR_ORG_OID_4 { get; set; }
        public string DTR_ORG_OID_5 { get; set; }
        public string DTR_TBL_OID { get; set; }
        public string DTR_USR_OID { get; set; }
        public Nullable<decimal> DTR_TRANSACTION_TYPE { get; set; }
        public string DTR_TRANSACTION_NAME { get; set; }
        public string DTR_DEFINITION { get; set; }
        public string DTR_BLOB_INFORMATION { get; set; }
        public string DTR_PROCESSED_IND { get; set; }
        public Nullable<decimal> DTR_TIMESTAMP { get; set; }
        public string DTR_FIELDA_001 { get; set; }
        public string DTR_FIELDA_002 { get; set; }
        public string DTR_FIELDA_003 { get; set; }
        public string DTR_FIELDA_004 { get; set; }
        public string DTR_FIELDA_005 { get; set; }
        public string DTR_FIELDA_006 { get; set; }
        public string DTR_FIELDA_007 { get; set; }
        public string DTR_FIELDA_008 { get; set; }
        public string DTR_FIELDA_009 { get; set; }
        public string DTR_FIELDA_010 { get; set; }
        public string DTR_FIELDB_001 { get; set; }
        public string DTR_FIELDB_002 { get; set; }
        public string DTR_FIELDB_003 { get; set; }
        public string DTR_FIELDB_004 { get; set; }
        public string DTR_FIELDB_005 { get; set; }
        public string DTR_FIELDC_001 { get; set; }
        public string DTR_FIELDC_002 { get; set; }
        public Nullable<decimal> DTR_LAST_MODIFIED { get; set; }
    }
}
