//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_ROOM
    {
        public string ERM_OID { get; set; }
        public string ERM_RMS_OID { get; set; }
        public Nullable<System.DateTime> ERM_EXAM_DATE { get; set; }
        public string ERM_EXAM_SESSION_CODE { get; set; }
        public Nullable<decimal> ERM_LAST_MODIFIED { get; set; }
    }
}
