//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPORT_FORMAT_FIELD
    {
        public string EFF_OID { get; set; }
        public string EFF_EFD_OID { get; set; }
        public string EFF_RTB_OID { get; set; }
        public string EFF_FDD_OID { get; set; }
        public Nullable<decimal> EFF_POSITION { get; set; }
        public string EFF_NAME { get; set; }
        public string EFF_BEAN_PATH { get; set; }
        public string EFF_BEAN_PATH_CALC { get; set; }
        public string EFF_DEFAULT { get; set; }
        public Nullable<decimal> EFF_MIN_LENGTH { get; set; }
        public Nullable<decimal> EFF_MAX_LENGTH { get; set; }
        public Nullable<decimal> EFF_FORMAT_TYPE { get; set; }
        public string EFF_FORMAT_EXPRESSION { get; set; }
        public string EFF_VALIDATION_PATTERN { get; set; }
        public Nullable<decimal> EFF_PADDING_DIRECTION { get; set; }
        public string EFF_PADDING_CHAR { get; set; }
        public string EFF_CALCULATION_ID { get; set; }
        public string EFF_VALIDATION_ID { get; set; }
        public string EFF_CALC_PARAM { get; set; }
        public string EFF_KEY_IND { get; set; }
        public string EFF_WRITEBACK_IND { get; set; }
        public string EFF_X_PATH { get; set; }
        public Nullable<decimal> EFF_LAST_MODIFIED { get; set; }
        public Nullable<decimal> EFF_REF_MAP_TYPE { get; set; }
        public Nullable<decimal> EFF_DEPTH { get; set; }
        public Nullable<decimal> EFF_AUDIT_TYPE { get; set; }
    }
}
