//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELD_SET_MEMBER
    {
        public string FSF_OID { get; set; }
        public string FSF_FSN_OID { get; set; }
        public string FSF_OBJ_OID { get; set; }
        public Nullable<decimal> FSF_FIELD_TYPE { get; set; }
        public string FSF_RELATION { get; set; }
        public Nullable<decimal> FSF_SEQUENCE_NUMBER { get; set; }
        public Nullable<decimal> FSF_WIDTH { get; set; }
        public Nullable<decimal> FSF_LAST_MODIFIED { get; set; }
    }
}
