//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM_POST
    {
        public string FPO_OID { get; set; }
        public string FPO_FTO_OID { get; set; }
        public string FPO_USR_OID { get; set; }
        public Nullable<decimal> FPO_POST_TIME { get; set; }
        public string FPO_POSTER_IP { get; set; }
        public Nullable<decimal> FPO_EDIT_TIME { get; set; }
        public Nullable<decimal> FPO_EDIT_COUNT { get; set; }
        public string FPO_EDIT_USR_OID { get; set; }
        public Nullable<decimal> FPO_STATUS { get; set; }
        public string FPO_CONTENT { get; set; }
        public string FPO_REPORTED { get; set; }
        public string FPO_REPLY_TO_OID { get; set; }
        public Nullable<decimal> FPO_VISIBLE_TIME { get; set; }
        public Nullable<decimal> FPO_LAST_MODIFIED { get; set; }
    }
}
