//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOOGLE_DOCUMENT_INSTANCE
    {
        public string GDI_OID { get; set; }
        public string GDI_ARI_OID { get; set; }
        public string GDI_USR_OID { get; set; }
        public string GDI_GOOG_RESOURCE_ID { get; set; }
        public string GDI_URL { get; set; }
        public string GDI_PARENT_CGD_OID { get; set; }
        public Nullable<decimal> GDI_LAST_MODIFIED { get; set; }
    }
}
