//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_GPA_MEMBER_GRADE
    {
        public string GPG_OID { get; set; }
        public string GPG_GPD_OID { get; set; }
        public string GPG_GTM_OID { get; set; }
        public string GPG_GTC_OID { get; set; }
        public Nullable<decimal> GPG_COLUMN_TYPE { get; set; }
        public string GPG_TERM_CODE { get; set; }
        public Nullable<decimal> GPG_TERM_WEIGHT { get; set; }
        public string GPG_AVERAGE_GRADE_CALCULATION { get; set; }
        public string GPG_USE_CALCULATED_AVERAGE_IND { get; set; }
        public string GPG_FIELDA_001 { get; set; }
        public string GPG_FIELDA_002 { get; set; }
        public string GPG_FIELDA_003 { get; set; }
        public Nullable<decimal> GPG_LAST_MODIFIED { get; set; }
    }
}
