//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_SCALE
    {
        public string GRS_OID { get; set; }
        public string GRS_ORG_OID_1 { get; set; }
        public string GRS_ORG_OID_2 { get; set; }
        public string GRS_ORG_OID_3 { get; set; }
        public string GRS_ORG_OID_4 { get; set; }
        public string GRS_ORG_OID_5 { get; set; }
        public Nullable<decimal> GRS_OWNER_TYPE { get; set; }
        public string GRS_OWNER_OID { get; set; }
        public string GRS_NAME { get; set; }
        public Nullable<decimal> GRS_MAX_POINTS { get; set; }
        public Nullable<decimal> GRS_MIN_POINTS { get; set; }
        public Nullable<decimal> GRS_MAX_ALLOWED { get; set; }
        public Nullable<decimal> GRS_MIN_ALLOWED { get; set; }
        public Nullable<decimal> GRS_LAST_MODIFIED { get; set; }
    }
}
