//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEBOOK_COMMENT
    {
        public string GCM_OID { get; set; }
        public string GCM_GCD_OID { get; set; }
        public string GCM_STD_OID { get; set; }
        public string GCM_COMMENT { get; set; }
        public string GCM_FOOTNOTE_CODE { get; set; }
        public string GCM_ADMIN_UPDATE_IND { get; set; }
        public Nullable<decimal> GCM_LAST_MODIFIED { get; set; }
    }
}
