//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEBOOK_ACCESS_GRANT
    {
        public string GAG_OID { get; set; }
        public string GAG_USR_OID { get; set; }
        public string GAG_USR_OID_VISITOR { get; set; }
        public Nullable<System.DateTime> GAG_START_DATE { get; set; }
        public Nullable<System.DateTime> GAG_END_DATE { get; set; }
        public Nullable<decimal> GAG_LAST_MODIFIED { get; set; }
    }
}
