//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEBOOK_STUDENT_INFO
    {
        public string GST_OID { get; set; }
        public string GST_STF_OID { get; set; }
        public string GST_STD_OID { get; set; }
        public string GST_FIELDA_001 { get; set; }
        public string GST_FIELDA_002 { get; set; }
        public string GST_FIELDA_003 { get; set; }
        public string GST_FIELDA_004 { get; set; }
        public string GST_FIELDA_005 { get; set; }
        public string GST_FIELDA_006 { get; set; }
        public string GST_FIELDA_007 { get; set; }
        public string GST_FIELDA_008 { get; set; }
        public string GST_FIELDB_001 { get; set; }
        public string GST_FIELDB_002 { get; set; }
        public string GST_FIELDB_003 { get; set; }
        public string GST_FIELDB_004 { get; set; }
        public string GST_FIELDC_001 { get; set; }
        public string GST_FIELDC_002 { get; set; }
        public string GST_FIELDD_001 { get; set; }
        public Nullable<decimal> GST_LAST_MODIFIED { get; set; }
    }
}
