//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEBOOK_SEATING_CHART
    {
        public string GCH_OID { get; set; }
        public string GCH_OBJ_OID { get; set; }
        public string GCH_NAME { get; set; }
        public Nullable<decimal> GCH_WIDTH { get; set; }
        public Nullable<decimal> GCH_HEIGHT { get; set; }
        public string GCH_COMMENTS { get; set; }
        public Nullable<decimal> GCH_LAST_MODIFIED { get; set; }
    }
}
