//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADUATION_REQUIREMENT
    {
        public string GRQ_OID { get; set; }
        public string GRQ_GPR_OID { get; set; }
        public string GRQ_CODE { get; set; }
        public Nullable<decimal> GRQ_REQUIRED_UNIT { get; set; }
        public Nullable<decimal> GRQ_REQUIREMENT_TYPE { get; set; }
        public string GRQ_EVALUATION_DEFINITION { get; set; }
        public string GRQ_DESCRIPTION { get; set; }
        public string GRQ_GPR_OID_SUB_PROGRAM { get; set; }
        public string GRQ_GRQ_OID { get; set; }
        public string GRQ_FIELDA_001 { get; set; }
        public string GRQ_FIELDA_002 { get; set; }
        public string GRQ_FIELDA_003 { get; set; }
        public string GRQ_FIELDA_004 { get; set; }
        public string GRQ_FIELDA_005 { get; set; }
        public string GRQ_FIELDA_006 { get; set; }
        public string GRQ_FIELDA_007 { get; set; }
        public string GRQ_FIELDA_008 { get; set; }
        public string GRQ_FIELDA_009 { get; set; }
        public string GRQ_FIELDA_010 { get; set; }
        public string GRQ_FIELDB_001 { get; set; }
        public string GRQ_FIELDB_002 { get; set; }
        public string GRQ_FIELDB_003 { get; set; }
        public string GRQ_FIELDB_004 { get; set; }
        public string GRQ_FIELDB_005 { get; set; }
        public string GRQ_FIELDC_001 { get; set; }
        public string GRQ_FIELDC_002 { get; set; }
        public Nullable<decimal> GRQ_LAST_MODIFIED { get; set; }
        public string GRQ_EXCLUDE_FROM_TOTAL_IND { get; set; }
        public string GRQ_EVALUATION_FIELD { get; set; }
    }
}
