//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_TREND
    {
        public string GTR_OID { get; set; }
        public string GTR_ORG_OID_1 { get; set; }
        public string GTR_ORG_OID_2 { get; set; }
        public string GTR_ORG_OID_3 { get; set; }
        public string GTR_ORG_OID_4 { get; set; }
        public string GTR_ORG_OID_5 { get; set; }
        public string GTR_GRADE_COMBINATION { get; set; }
        public Nullable<decimal> GTR_GRADE_COUNT { get; set; }
        public string GTR_RESULT { get; set; }
        public Nullable<decimal> GTR_BUMP { get; set; }
        public Nullable<decimal> GTR_LAST_MODIFIED { get; set; }
    }
}
