//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_PAGE_PREFERENCE
    {
        public string GPP_OID { get; set; }
        public string GPP_GPW_OID { get; set; }
        public string GPP_USR_OID { get; set; }
        public string GPP_KEY { get; set; }
        public string GPP_VALUE { get; set; }
        public Nullable<decimal> GPP_LAST_MODIFIED { get; set; }
    }
}
