//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_MEMBER_CACHE
    {
        public string GMC_OID { get; set; }
        public string GMC_GRP_OID { get; set; }
        public string GMC_GMB_OID { get; set; }
        public string GMC_PSN_OID { get; set; }
        public string GMC_ORG_OID { get; set; }
        public string GMC_SKL_OID { get; set; }
        public string GMC_CODE_VALUE { get; set; }
        public Nullable<decimal> GMC_LAST_MODIFIED { get; set; }
    }
}
