//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEALTH_JOB
    {
        public string HJB_OID { get; set; }
        public string HJB_HMO_OID { get; set; }
        public Nullable<System.DateTime> HJB_DATE { get; set; }
        public Nullable<System.DateTime> HJB_TIME { get; set; }
        public string HJB_COMPLETE_IND { get; set; }
        public string HJB_SCHEDULED_IND { get; set; }
        public string HJB_FIELDA_001 { get; set; }
        public string HJB_FIELDA_002 { get; set; }
        public string HJB_FIELDA_003 { get; set; }
        public string HJB_FIELDA_004 { get; set; }
        public string HJB_FIELDA_005 { get; set; }
        public string HJB_FIELDA_006 { get; set; }
        public string HJB_FIELDA_007 { get; set; }
        public string HJB_FIELDA_008 { get; set; }
        public string HJB_FIELDA_009 { get; set; }
        public string HJB_FIELDA_010 { get; set; }
        public string HJB_FIELDB_001 { get; set; }
        public string HJB_FIELDB_002 { get; set; }
        public string HJB_FIELDB_003 { get; set; }
        public string HJB_FIELDB_004 { get; set; }
        public string HJB_FIELDB_005 { get; set; }
        public string HJB_FIELDB_006 { get; set; }
        public string HJB_FIELDB_007 { get; set; }
        public string HJB_FIELDB_008 { get; set; }
        public string HJB_FIELDB_009 { get; set; }
        public string HJB_FIELDB_010 { get; set; }
        public string HJB_FIELDC_001 { get; set; }
        public string HJB_FIELDC_002 { get; set; }
        public string HJB_FIELDC_003 { get; set; }
        public string HJB_FIELDC_004 { get; set; }
        public string HJB_FIELDC_005 { get; set; }
        public string HJB_FIELDD_001 { get; set; }
        public string HJB_FIELDD_002 { get; set; }
        public string HJB_FIELDD_003 { get; set; }
        public string HJB_FIELDD_004 { get; set; }
        public string HJB_FIELDD_005 { get; set; }
        public Nullable<decimal> HJB_TIMESTAMP { get; set; }
        public Nullable<decimal> HJB_LAST_MODIFIED { get; set; }
        public string HJB_HLG_OID { get; set; }
    }
}
