//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_SERVICE
    {
        public string ISV_OID { get; set; }
        public string ISV_STD_OID { get; set; }
        public string ISV_IEP_OID { get; set; }
        public string ISV_STF_OID { get; set; }
        public string ISV_SERVICE_MODE { get; set; }
        public string ISV_SERVICE_TYPE { get; set; }
        public string ISV_SERVICE_CODE { get; set; }
        public string ISV_SETTING_CODE { get; set; }
        public string ISV_PROVIDER_CODE { get; set; }
        public string ISV_SECONDARY_PROVIDER_CODE { get; set; }
        public string ISV_GOAL_VIEW { get; set; }
        public Nullable<decimal> ISV_FREQUENCY { get; set; }
        public Nullable<decimal> ISV_DURATION { get; set; }
        public string ISV_CYCLE { get; set; }
        public Nullable<decimal> ISV_DAYS_PER_CYCLE { get; set; }
        public string ISV_OTHER_INFO { get; set; }
        public Nullable<System.DateTime> ISV_START_DATE { get; set; }
        public Nullable<System.DateTime> ISV_END_DATE { get; set; }
        public string ISV_EXTENDED_YEAR_IND { get; set; }
        public string ISV_APPROVED_IND { get; set; }
        public string ISV_MED_REIMURSABLE_IND { get; set; }
        public string ISV_SERVICE_DELIVERY_CODE { get; set; }
        public string ISV_FIELDA_001 { get; set; }
        public string ISV_FIELDA_002 { get; set; }
        public string ISV_FIELDA_003 { get; set; }
        public string ISV_FIELDA_004 { get; set; }
        public string ISV_FIELDA_005 { get; set; }
        public string ISV_FIELDA_006 { get; set; }
        public string ISV_FIELDA_007 { get; set; }
        public string ISV_FIELDA_008 { get; set; }
        public string ISV_FIELDA_009 { get; set; }
        public string ISV_FIELDA_010 { get; set; }
        public string ISV_FIELDB_001 { get; set; }
        public string ISV_FIELDB_002 { get; set; }
        public string ISV_FIELDB_003 { get; set; }
        public string ISV_FIELDB_004 { get; set; }
        public string ISV_FIELDB_005 { get; set; }
        public string ISV_FIELDB_006 { get; set; }
        public string ISV_FIELDB_007 { get; set; }
        public string ISV_FIELDB_008 { get; set; }
        public string ISV_FIELDB_009 { get; set; }
        public string ISV_FIELDB_010 { get; set; }
        public string ISV_FIELDC_001 { get; set; }
        public string ISV_FIELDC_002 { get; set; }
        public string ISV_FIELDC_003 { get; set; }
        public string ISV_FIELDC_004 { get; set; }
        public string ISV_FIELDC_005 { get; set; }
        public string ISV_FIELDD_001 { get; set; }
        public string ISV_FIELDD_002 { get; set; }
        public Nullable<decimal> ISV_LAST_MODIFIED { get; set; }
        public string ISV_FIELDD_003 { get; set; }
        public string ISV_FIELDD_004 { get; set; }
        public string ISV_FIELDD_005 { get; set; }
    }
}
