//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_SERVICE_LOG
    {
        public string ISL_OID { get; set; }
        public string ISL_ISV_OID { get; set; }
        public Nullable<System.DateTime> ISL_DATE { get; set; }
        public string ISL_SERVICE_DELIVERY_CODE { get; set; }
        public string ISL_THERAPY_CODE { get; set; }
        public Nullable<System.DateTime> ISL_START_TIME { get; set; }
        public Nullable<decimal> ISL_DURATION { get; set; }
        public Nullable<decimal> ISL_PREP_DOC_TIME { get; set; }
        public string ISL_ABSENT_IND { get; set; }
        public string ISL_COMMENTS { get; set; }
        public string ISL_FIELDA_001 { get; set; }
        public string ISL_FIELDA_002 { get; set; }
        public string ISL_FIELDA_003 { get; set; }
        public string ISL_FIELDA_004 { get; set; }
        public string ISL_FIELDA_005 { get; set; }
        public string ISL_FIELDB_001 { get; set; }
        public string ISL_FIELDB_002 { get; set; }
        public string ISL_FIELDB_003 { get; set; }
        public string ISL_FIELDB_004 { get; set; }
        public string ISL_FIELDB_005 { get; set; }
        public string ISL_FIELDC_001 { get; set; }
        public string ISL_FIELDC_002 { get; set; }
        public string ISL_FIELDC_003 { get; set; }
        public string ISL_FIELDC_004 { get; set; }
        public string ISL_FIELDC_005 { get; set; }
        public Nullable<decimal> ISL_LAST_MODIFIED { get; set; }
    }
}
