//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_GOAL_PROGRESS
    {
        public string IGP_OID { get; set; }
        public string IGP_STD_OID { get; set; }
        public string IGP_IEP_OID { get; set; }
        public string IGP_IGL_OID { get; set; }
        public string IGP_STF_OID { get; set; }
        public string IGP_CTX_OID { get; set; }
        public Nullable<System.DateTime> IGP_DATE { get; set; }
        public string IGP_PROGESS_CODE { get; set; }
        public string IGP_ON_TRACK_IND { get; set; }
        public string IGP_PERFORMANCE_LEVEL { get; set; }
        public string IGP_POSTED_IND { get; set; }
        public Nullable<decimal> IGP_POSTED_TIME { get; set; }
        public string IGP_REPORT_PERIOD { get; set; }
        public string IGP_FIELDA_001 { get; set; }
        public string IGP_FIELDA_002 { get; set; }
        public string IGP_FIELDA_003 { get; set; }
        public string IGP_FIELDA_004 { get; set; }
        public string IGP_FIELDA_005 { get; set; }
        public string IGP_FIELDA_006 { get; set; }
        public string IGP_FIELDA_007 { get; set; }
        public string IGP_FIELDA_008 { get; set; }
        public string IGP_FIELDB_001 { get; set; }
        public string IGP_FIELDB_002 { get; set; }
        public string IGP_FIELDB_003 { get; set; }
        public string IGP_FIELDB_004 { get; set; }
        public string IGP_FIELDB_005 { get; set; }
        public string IGP_FIELDC_001 { get; set; }
        public string IGP_FIELDC_002 { get; set; }
        public string IGP_FIELDC_003 { get; set; }
        public string IGP_FIELDD_001 { get; set; }
        public string IGP_FIELDD_002 { get; set; }
        public Nullable<decimal> IGP_LAST_MODIFIED { get; set; }
    }
}
