//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_EXPORT_DEFINITION
    {
        public string IED_OID { get; set; }
        public string IED_ORG_OID_1 { get; set; }
        public string IED_ORG_OID_2 { get; set; }
        public string IED_ORG_OID_3 { get; set; }
        public string IED_ORG_OID_4 { get; set; }
        public string IED_ORG_OID_5 { get; set; }
        public string IED_DDX_OID { get; set; }
        public string IED_CUSTOM_HREF { get; set; }
        public string IED_MENU_GROUP { get; set; }
        public string IED_OWNER_OID { get; set; }
        public Nullable<decimal> IED_OWNER_TYPE { get; set; }
        public Nullable<decimal> IED_TYPE { get; set; }
        public string IED_ID { get; set; }
        public Nullable<decimal> IED_SEQUENCE_NUMBER { get; set; }
        public string IED_NAME { get; set; }
        public string IED_CATEGORY { get; set; }
        public Nullable<decimal> IED_SCHOOL_VISIBILITY_TYPE { get; set; }
        public Nullable<decimal> IED_ROLE_VISIBILITY_TYPE { get; set; }
        public string IED_JAVA_SOURCE { get; set; }
        public byte[] IED_JAVA_SOURCE_COMPILED { get; set; }
        public string IED_CUSTOM_JAVA_SOURCE_IND { get; set; }
        public string IED_DEFINITION { get; set; }
        public string IED_CUSTOM_DEFINITION_IND { get; set; }
        public string IED_CUSTOM_INPUT_IND { get; set; }
        public string IED_INPUT_DEFINITION { get; set; }
        public Nullable<decimal> IED_WEIGHT { get; set; }
        public string IED_COMMENT { get; set; }
        public string IED_SCHEDULE { get; set; }
        public string IED_DISABLE_AUTO_KILL { get; set; }
        public Nullable<decimal> IED_LAST_MODIFIED { get; set; }
    }
}
