//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_ENTRY
    {
        public string JOB_OID { get; set; }
        public string JOB_ORG_OID_1 { get; set; }
        public string JOB_ORG_OID_2 { get; set; }
        public string JOB_ORG_OID_3 { get; set; }
        public string JOB_ORG_OID_4 { get; set; }
        public string JOB_ORG_OID_5 { get; set; }
        public string JOB_USR_OID { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_STATUS { get; set; }
        public Nullable<decimal> JOB_TOOL_TYPE { get; set; }
        public string JOB_TOOL_OID { get; set; }
        public string JOB_TOOL_INPUT { get; set; }
        public string JOB_INPUT_DEFAULTS { get; set; }
        public Nullable<decimal> JOB_DELIV_TYPE { get; set; }
        public string JOB_DELIV_PARAM { get; set; }
        public string JOB_SAVE_RESULTS { get; set; }
        public Nullable<System.DateTime> JOB_START_DATE { get; set; }
        public Nullable<System.DateTime> JOB_END_DATE { get; set; }
        public Nullable<System.DateTime> JOB_START_TIME { get; set; }
        public Nullable<System.DateTime> JOB_END_TIME { get; set; }
        public Nullable<decimal> JOB_REPEAT_TIME { get; set; }
        public Nullable<decimal> JOB_DAY_TYPE { get; set; }
        public Nullable<decimal> JOB_DAY_SCHED { get; set; }
        public Nullable<decimal> JOB_LAST_RUN_DATE { get; set; }
        public Nullable<decimal> JOB_NEXT_RUN_DATE { get; set; }
        public Nullable<decimal> JOB_LAST_MODIFIED { get; set; }
    }
}
