//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEARNING_STANDARD
    {
        public string LST_OID { get; set; }
        public string LST_IDENTIFIER { get; set; }
        public string LST_NAME { get; set; }
        public string LST_STANDARD { get; set; }
        public string LST_START_GRADE { get; set; }
        public string LST_END_GRADE { get; set; }
        public string LST_DEPARTMENT_CODE { get; set; }
        public string LST_STRAND { get; set; }
        public string LST_FIELDA_001 { get; set; }
        public string LST_FIELDA_002 { get; set; }
        public string LST_FIELDA_003 { get; set; }
        public string LST_FIELDA_004 { get; set; }
        public string LST_FIELDA_005 { get; set; }
        public string LST_FIELDA_006 { get; set; }
        public string LST_FIELDA_007 { get; set; }
        public string LST_FIELDA_008 { get; set; }
        public string LST_FIELDA_009 { get; set; }
        public string LST_FIELDA_010 { get; set; }
        public string LST_FIELDB_001 { get; set; }
        public string LST_FIELDB_002 { get; set; }
        public string LST_FIELDB_003 { get; set; }
        public string LST_FIELDB_004 { get; set; }
        public string LST_FIELDB_005 { get; set; }
        public string LST_FIELDC_001 { get; set; }
        public string LST_FIELDC_002 { get; set; }
        public string LST_FIELDC_003 { get; set; }
        public string LST_FIELDC_004 { get; set; }
        public string LST_FIELDC_005 { get; set; }
        public string LST_FIELDD_001 { get; set; }
        public string LST_FIELDD_002 { get; set; }
        public Nullable<decimal> LST_LAST_MODIFIED { get; set; }
        public Nullable<decimal> LST_REMOTE_OID { get; set; }
        public string LST_PARENT_OID { get; set; }
        public string LST_KEYWORDS { get; set; }
        public string LST_TYPE { get; set; }
        public string LST_LOCAL { get; set; }
        public string LST_DELETED { get; set; }
        public string LST_HAS_CHILDREN_IND { get; set; }
        public string LST_DOCUMENT { get; set; }
        public string LST_CATEGORIZATION { get; set; }
    }
}
