//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION_LOCALE
    {
        public string OLC_OID { get; set; }
        public string OLC_ORG_OID { get; set; }
        public string OLC_NAME { get; set; }
        public string OLC_LOCALE { get; set; }
        public string OLC_PRIMARY_IND { get; set; }
        public string OLC_ENABLED_IND { get; set; }
        public string OLC_FIELDA_001 { get; set; }
        public string OLC_FIELDA_002 { get; set; }
        public string OLC_FIELDA_003 { get; set; }
        public string OLC_FIELDB_001 { get; set; }
        public string OLC_FIELDB_002 { get; set; }
        public Nullable<decimal> OLC_LAST_MODIFIED { get; set; }
    }
}
