//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION
    {
        public string ORG_OID { get; set; }
        public string ORG_ORD_OID { get; set; }
        public string ORG_ORG_OID_PARENT { get; set; }
        public string ORG_ORG_OID_1 { get; set; }
        public string ORG_ORG_OID_2 { get; set; }
        public string ORG_ORG_OID_3 { get; set; }
        public string ORG_ORG_OID_4 { get; set; }
        public string ORG_ORG_OID_5 { get; set; }
        public string ORG_ADR_OID { get; set; }
        public string ORG_DDX_OID { get; set; }
        public string ORG_ID { get; set; }
        public string ORG_NAME { get; set; }
        public string ORG_TYPE { get; set; }
        public string ORG_CTX_OID_CURRENT { get; set; }
        public string ORG_TIME_ZONE { get; set; }
        public string ORG_AD_OU_NAME { get; set; }
        public string ORG_DISABLED_IND { get; set; }
        public string ORG_SIF_AGENT_ID { get; set; }
        public string ORG_SIF_ZONE_ID { get; set; }
        public string ORG_SIF_VERSION { get; set; }
        public Nullable<decimal> ORG_SIF_MODE { get; set; }
        public string ORG_SIF_URL { get; set; }
        public Nullable<decimal> ORG_SIF_PORT { get; set; }
        public string ORG_FIELDA_001 { get; set; }
        public string ORG_FIELDA_002 { get; set; }
        public string ORG_FIELDA_003 { get; set; }
        public string ORG_FIELDA_004 { get; set; }
        public string ORG_FIELDA_005 { get; set; }
        public string ORG_FIELDA_006 { get; set; }
        public string ORG_FIELDA_007 { get; set; }
        public string ORG_FIELDA_008 { get; set; }
        public string ORG_FIELDA_009 { get; set; }
        public string ORG_FIELDA_010 { get; set; }
        public string ORG_FIELDB_001 { get; set; }
        public string ORG_FIELDB_002 { get; set; }
        public string ORG_FIELDB_003 { get; set; }
        public string ORG_FIELDB_004 { get; set; }
        public string ORG_FIELDB_005 { get; set; }
        public string ORG_FIELDB_006 { get; set; }
        public string ORG_FIELDB_007 { get; set; }
        public string ORG_FIELDB_008 { get; set; }
        public string ORG_FIELDB_009 { get; set; }
        public string ORG_FIELDB_010 { get; set; }
        public string ORG_FIELDC_001 { get; set; }
        public string ORG_FIELDC_002 { get; set; }
        public string ORG_FIELDC_003 { get; set; }
        public string ORG_FIELDC_004 { get; set; }
        public string ORG_FIELDC_005 { get; set; }
        public Nullable<decimal> ORG_LAST_MODIFIED { get; set; }
        public Nullable<decimal> ORG_SIF_PULL_FREQ { get; set; }
        public string ORG_FSC_CUSTOMER_ID { get; set; }
        public string ORG_CTX_OID_WAITLIST { get; set; }
        public string ORG_GUID { get; set; }
    }
}
