//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_ADDRESS
    {
        public string ADR_OID { get; set; }
        public string ADR_ORG_OID_1 { get; set; }
        public string ADR_ORG_OID_2 { get; set; }
        public string ADR_ORG_OID_3 { get; set; }
        public string ADR_ORG_OID_4 { get; set; }
        public string ADR_ORG_OID_5 { get; set; }
        public string ADR_AGC_OID { get; set; }
        public Nullable<decimal> ADR_STREET_NUMBER { get; set; }
        public string ADR_STREET_LETTER { get; set; }
        public string ADR_STREET_PRE_DIRECTION { get; set; }
        public string ADR_STREET_POST_DIRECTION { get; set; }
        public string ADR_STREET_NAME { get; set; }
        public string ADR_STREET_TYPE { get; set; }
        public string ADR_USER_VALIDATED_IND1 { get; set; }
        public string ADR_USER_VALIDATED_IND2 { get; set; }
        public string ADR_USER_VALIDATED_IND3 { get; set; }
        public string ADR_ADDRESS_LINE_01 { get; set; }
        public string ADR_ADDRESS_LINE_02 { get; set; }
        public string ADR_ADDRESS_LINE_03 { get; set; }
        public string ADR_CITY { get; set; }
        public string ADR_STATE { get; set; }
        public string ADR_POSTAL_CODE { get; set; }
        public string ADR_COUNTY { get; set; }
        public string ADR_COUNTRY { get; set; }
        public string ADR_PHONE_01 { get; set; }
        public string ADR_PHONE_02 { get; set; }
        public string ADR_MISC { get; set; }
        public string ADR_FIELDA_001 { get; set; }
        public string ADR_FIELDA_002 { get; set; }
        public string ADR_FIELDA_003 { get; set; }
        public string ADR_FIELDB_001 { get; set; }
        public string ADR_FIELDB_002 { get; set; }
        public string ADR_FIELDB_003 { get; set; }
        public string ADR_FIELDC_001 { get; set; }
        public Nullable<decimal> ADR_LAST_MODIFIED { get; set; }
        public string ADR_FIELDA_004 { get; set; }
        public string ADR_FIELDA_005 { get; set; }
        public string ADR_FIELDA_006 { get; set; }
        public string ADR_FIELDA_007 { get; set; }
        public string ADR_FIELDA_008 { get; set; }
        public string ADR_FIELDA_009 { get; set; }
        public string ADR_FIELDA_010 { get; set; }
        public string ADR_FIELDB_004 { get; set; }
        public string ADR_FIELDB_005 { get; set; }
        public string ADR_FIELDB_006 { get; set; }
        public string ADR_FIELDB_007 { get; set; }
        public string ADR_FIELDB_008 { get; set; }
        public string ADR_FIELDB_009 { get; set; }
        public string ADR_FIELDB_010 { get; set; }
        public string ADR_FIELDC_002 { get; set; }
        public string ADR_FIELDC_003 { get; set; }
        public string ADR_FIELDC_004 { get; set; }
        public string ADR_FIELDC_005 { get; set; }
        public string ADR_FIELDC_006 { get; set; }
        public string ADR_FIELDC_007 { get; set; }
        public string ADR_FIELDC_008 { get; set; }
        public string ADR_FIELDC_009 { get; set; }
        public string ADR_FIELDC_010 { get; set; }
    }
}
