//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_PHOTO
    {
        public string PHO_OID { get; set; }
        public string PHO_ORG_OID_1 { get; set; }
        public string PHO_ORG_OID_2 { get; set; }
        public string PHO_ORG_OID_3 { get; set; }
        public string PHO_ORG_OID_4 { get; set; }
        public string PHO_ORG_OID_5 { get; set; }
        public string PHO_PSN_OID { get; set; }
        public byte[] PHO_PHOTO { get; set; }
        public string PHO_FILE_EXTENSION { get; set; }
        public Nullable<decimal> PHO_LAST_MODIFIED { get; set; }
        public byte[] PHO_PHOTO_THUMBNAIL { get; set; }
    }
}
