//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANNER_APPOINTMENT
    {
        public string PLA_OID { get; set; }
        public string PLA_NAME { get; set; }
        public string PLA_DESC { get; set; }
        public string PLA_OWNER_ID { get; set; }
        public string PLA_OWNER_TYPE { get; set; }
        public Nullable<System.DateTime> PLA_START_DATE { get; set; }
        public Nullable<System.DateTime> PLA_START_TIME { get; set; }
        public Nullable<System.DateTime> PLA_END_DATE { get; set; }
        public Nullable<System.DateTime> PLA_END_TIME { get; set; }
        public Nullable<System.DateTime> PLA_VISIBLE_DATE { get; set; }
        public Nullable<System.DateTime> PLA_VISIBLE_TIME { get; set; }
        public Nullable<decimal> PLA_LAST_MODIFIED { get; set; }
    }
}
