//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCEDURE_INFO
    {
        public string PRC_OID { get; set; }
        public string PRC_ORG_OID_1 { get; set; }
        public string PRC_ORG_OID_2 { get; set; }
        public string PRC_ORG_OID_3 { get; set; }
        public string PRC_ORG_OID_4 { get; set; }
        public string PRC_ORG_OID_5 { get; set; }
        public string PRC_DDX_OID { get; set; }
        public string PRC_CUSTOM_HREF { get; set; }
        public string PRC_MENU_GROUP { get; set; }
        public string PRC_NAME { get; set; }
        public string PRC_ID { get; set; }
        public Nullable<decimal> PRC_SEQUENCE_NUMBER { get; set; }
        public Nullable<decimal> PRC_TYPE { get; set; }
        public string PRC_CATEGORY { get; set; }
        public string PRC_JAVA_SOURCE { get; set; }
        public byte[] PRC_JAVA_SOURCE_COMPILED { get; set; }
        public string PRC_PROCEDURE_INPUT { get; set; }
        public string PRC_CUSTOM_JAVA_SOURCE_IND { get; set; }
        public string PRC_CUSTOM_INPUT_IND { get; set; }
        public string PRC_SYSTEM_USE_ONLY_IND { get; set; }
        public Nullable<decimal> PRC_WEIGHT { get; set; }
        public string PRC_SCHEDULE { get; set; }
        public string PRC_COMMENT { get; set; }
        public Nullable<decimal> PRC_SCHOOL_VISIBILITY_TYPE { get; set; }
        public Nullable<decimal> PRC_ROLE_VISIBILITY_TYPE { get; set; }
        public string PRC_DISABLE_AUTO_KILL { get; set; }
        public Nullable<decimal> PRC_LAST_MODIFIED { get; set; }
    }
}
