//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_SET_DEFINITION
    {
        public string QSD_OID { get; set; }
        public string QSD_GRP_OID { get; set; }
        public string QSD_TITLE { get; set; }
        public string QSD_DESCRIPTION { get; set; }
        public string QSD_RANDOM_ORDER { get; set; }
        public string QSD_ALLOW_REVIEW { get; set; }
        public Nullable<System.DateTime> QSD_START_DATE { get; set; }
        public Nullable<System.DateTime> QSD_END_DATE { get; set; }
        public Nullable<decimal> QSD_MAX_PER_PAGE { get; set; }
        public Nullable<decimal> QSD_LAST_MODIFIED { get; set; }
    }
}
