//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_SET_ITEM
    {
        public string QST_OID { get; set; }
        public string QST_QSR_OID { get; set; }
        public string QST_QSD_OID { get; set; }
        public Nullable<decimal> QST_SEQ_NO { get; set; }
        public Nullable<decimal> QST_POINT_VALUE { get; set; }
        public Nullable<decimal> QST_LAST_MODIFIED { get; set; }
    }
}
