//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_CODE
    {
        public string RCD_OID { get; set; }
        public string RCD_RTB_OID { get; set; }
        public string RCD_SKL_OID { get; set; }
        public string RCD_DDX_OID { get; set; }
        public Nullable<decimal> RCD_SEQUENCE_NUMBER { get; set; }
        public string RCD_CODE { get; set; }
        public string RCD_DESCRIPTION { get; set; }
        public string RCD_TEMPLATE_CONTEXT { get; set; }
        public string RCD_CODE_LOCAL { get; set; }
        public string RCD_CODE_STATE { get; set; }
        public string RCD_CODE_FEDERAL { get; set; }
        public string RCD_CODE_SYSTEM { get; set; }
        public string RCD_CODE_DEPENDENT { get; set; }
        public string RCD_NO_HIDE_IND { get; set; }
        public string RCD_DISABLED_IND { get; set; }
        public string RCD_CATEGORY { get; set; }
        public string RCD_CATEGORY_IND { get; set; }
        public string RCD_DESCRIPTION_LOCALE_1 { get; set; }
        public string RCD_DESCRIPTION_LOCALE_2 { get; set; }
        public string RCD_DESCRIPTION_LOCALE_3 { get; set; }
        public string RCD_DESCRIPTION_LOCALE_4 { get; set; }
        public string RCD_DESCRIPTION_LOCALE_5 { get; set; }
        public string RCD_FIELDA_001 { get; set; }
        public string RCD_FIELDA_002 { get; set; }
        public string RCD_FIELDA_003 { get; set; }
        public string RCD_FIELDA_004 { get; set; }
        public string RCD_FIELDA_005 { get; set; }
        public string RCD_FIELDA_006 { get; set; }
        public string RCD_FIELDA_007 { get; set; }
        public string RCD_FIELDA_008 { get; set; }
        public string RCD_FIELDA_009 { get; set; }
        public string RCD_FIELDA_010 { get; set; }
        public string RCD_FIELDB_001 { get; set; }
        public string RCD_FIELDB_002 { get; set; }
        public string RCD_FIELDB_003 { get; set; }
        public string RCD_FIELDB_004 { get; set; }
        public string RCD_FIELDB_005 { get; set; }
        public string RCD_FIELDB_006 { get; set; }
        public string RCD_FIELDB_007 { get; set; }
        public string RCD_FIELDB_008 { get; set; }
        public string RCD_FIELDB_009 { get; set; }
        public string RCD_FIELDB_010 { get; set; }
        public string RCD_FIELDC_001 { get; set; }
        public string RCD_FIELDC_002 { get; set; }
        public string RCD_FIELDC_003 { get; set; }
        public string RCD_FIELDC_004 { get; set; }
        public string RCD_FIELDC_005 { get; set; }
        public string RCD_FIELDD_001 { get; set; }
        public string RCD_FIELDD_002 { get; set; }
        public string RCD_FIELDD_003 { get; set; }
        public Nullable<decimal> RCD_LAST_MODIFIED { get; set; }
    }
}
