//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGEX_LIBRARY
    {
        public string RGX_OID { get; set; }
        public string RGX_ORG_OID_1 { get; set; }
        public string RGX_ORG_OID_2 { get; set; }
        public string RGX_ORG_OID_3 { get; set; }
        public string RGX_ORG_OID_4 { get; set; }
        public string RGX_ORG_OID_5 { get; set; }
        public string RGX_ID { get; set; }
        public string RGX_SHORT_DESCRIPTION { get; set; }
        public Nullable<decimal> RGX_SOURCE_TYPE { get; set; }
        public string RGX_DESCRIPTION { get; set; }
        public string RGX_EXPRESSION { get; set; }
        public string RGX_LAYOUT { get; set; }
        public string RGX_CUSTOM_IND { get; set; }
        public Nullable<decimal> RGX_LAST_MODIFIED { get; set; }
        public string RGX_USER_DESCRIPTION { get; set; }
    }
}
