//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRIC_PERFORMANCE_DESCRIPTOR
    {
        public string RBP_OID { get; set; }
        public string RBP_RBC_OID { get; set; }
        public Nullable<decimal> RBP_SEQUENCE_NUMBER { get; set; }
        public string RBP_RATING_ID { get; set; }
        public string RBP_NAME { get; set; }
        public string RBP_DESCRIPTION { get; set; }
        public Nullable<decimal> RBP_POINTS { get; set; }
        public Nullable<decimal> RBP_CUTOFF { get; set; }
        public string RBP_PERFORMANCE_DESCRIPTORS { get; set; }
        public string RBP_PERFORMANCE_INDICATORS { get; set; }
        public string RBP_MASTERY_IND { get; set; }
        public Nullable<decimal> RBP_LAST_MODIFIED { get; set; }
    }
}
