//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_COMMIT_CONTROL
    {
        public string SMC_OID { get; set; }
        public string SMC_CTX_OID { get; set; }
        public string SMC_SKL_OID { get; set; }
        public Nullable<System.DateTime> SMC_START_DATE { get; set; }
        public Nullable<System.DateTime> SMC_END_DATE { get; set; }
        public Nullable<decimal> SMC_LAST_MODIFIED { get; set; }
    }
}
