//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_RULE
    {
        public string SRL_OID { get; set; }
        public string SRL_SCH_OID { get; set; }
        public string SRL_SRD_OID { get; set; }
        public string SRL_RULE { get; set; }
        public string SRL_SUMMARY_VIEW { get; set; }
        public Nullable<decimal> SRL_LAST_MODIFIED { get; set; }
        public string SRL_ELEMENTARY_IND { get; set; }
    }
}
