//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_BELL_DAY
    {
        public string BDY_OID { get; set; }
        public string BDY_BEL_OID { get; set; }
        public Nullable<decimal> BDY_DAY_NUMBER { get; set; }
        public string BDY_DAY_ID { get; set; }
        public string BDY_DAY_NAME { get; set; }
        public string BDY_FIELDA_001 { get; set; }
        public string BDY_FIELDA_002 { get; set; }
        public string BDY_FIELDA_003 { get; set; }
        public string BDY_FIELDB_001 { get; set; }
        public string BDY_FIELDB_002 { get; set; }
        public Nullable<decimal> BDY_LAST_MODIFIED { get; set; }
    }
}
