//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_ROTATION_MAP
    {
        public string ROM_OID { get; set; }
        public string ROM_ROT_OID { get; set; }
        public Nullable<decimal> ROM_BUILD_DAY_NUMBER { get; set; }
        public Nullable<decimal> ROM_BUILD_PERIOD_NUMBER { get; set; }
        public Nullable<decimal> ROM_ROTATED_DAY_NUMBER { get; set; }
        public Nullable<decimal> ROM_ROTATED_PERIOD_NUMBER { get; set; }
        public string ROM_TERM_MAP { get; set; }
        public Nullable<decimal> ROM_LAST_MODIFIED { get; set; }
    }
}
