//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_BELL_PERIOD
    {
        public string BPE_OID { get; set; }
        public string BPE_BEL_OID { get; set; }
        public Nullable<decimal> BPE_PERIOD_NUMBER { get; set; }
        public string BPE_PERIOD_ID { get; set; }
        public string BPE_PERIOD_NAME { get; set; }
        public Nullable<System.DateTime> BPE_START_TIME { get; set; }
        public Nullable<System.DateTime> BPE_END_TIME { get; set; }
        public string BPE_PER_OID { get; set; }
        public string BPE_DAY_OID { get; set; }
        public string BPE_FIELDA_001 { get; set; }
        public string BPE_FIELDA_002 { get; set; }
        public string BPE_FIELDA_003 { get; set; }
        public string BPE_FIELDB_001 { get; set; }
        public string BPE_FIELDB_002 { get; set; }
        public Nullable<decimal> BPE_LAST_MODIFIED { get; set; }
    }
}
