//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_BUILD_STUDENT
    {
        public string BLS_OID { get; set; }
        public string BLS_STD_OID { get; set; }
        public string BLS_SCH_OID { get; set; }
        public string BLS_BLM_OID { get; set; }
        public string BLS_TERM_VIEW { get; set; }
        public string BLS_SCHEDULE_DISPLAY { get; set; }
        public string BLS_SCHEDULE_LOCK_IND { get; set; }
        public string BLS_INCLUSION_IND { get; set; }
        public string BLS_TERM_MAP { get; set; }
        public string BLS_SCHEDULE_MATRIX { get; set; }
        public Nullable<decimal> BLS_LAST_MODIFIED { get; set; }
        public string BLS_CONTENT_TERM_CODE { get; set; }
    }
}
