//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_CLASS_MATRIX
    {
        public string CMX_OID { get; set; }
        public string CMX_CTM_OID { get; set; }
        public string CMX_MTX_OID { get; set; }
        public Nullable<decimal> CMX_ENROLLMENT_TOTAL { get; set; }
        public Nullable<decimal> CMX_LAST_MODIFIED { get; set; }
    }
}
