//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_CLASS_TERM
    {
        public string CTM_OID { get; set; }
        public string CTM_CLS_OID { get; set; }
        public string CTM_TRM_OID { get; set; }
        public Nullable<decimal> CTM_LAST_MODIFIED { get; set; }
    }
}
