//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_TAG
    {
        public string SUT_OID { get; set; }
        public string SUT_ORG_OID_1 { get; set; }
        public string SUT_ORG_OID_2 { get; set; }
        public string SUT_ORG_OID_3 { get; set; }
        public string SUT_ORG_OID_4 { get; set; }
        public string SUT_ORG_OID_5 { get; set; }
        public string SUT_TBD_OID { get; set; }
        public string SUT_TAG_NAME { get; set; }
        public Nullable<decimal> SUT_LAST_MODIFIED { get; set; }
    }
}
