//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_CONTEXT
    {
        public string SUN_OID { get; set; }
        public string SUN_SUR_OID { get; set; }
        public Nullable<decimal> SUN_APPLICATION_CONTEXT { get; set; }
        public string SUN_CONTEXT { get; set; }
        public Nullable<decimal> SUN_LAST_MODIFIED { get; set; }
    }
}
