//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_PROVIDER
    {
        public string SVP_OID { get; set; }
        public string SVP_NAME { get; set; }
        public string SVP_SPT_OID { get; set; }
        public string SVP_PROVIDER_ID { get; set; }
        public Nullable<decimal> SVP_LAST_MODIFIED { get; set; }
    }
}
