//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_PD_ACTION_PLAN
    {
        public string SAT_OID { get; set; }
        public string SAT_STF_OID { get; set; }
        public string SAT_SDP_OID { get; set; }
        public string SAT_ID { get; set; }
        public string SAT_PLAN { get; set; }
        public string SAT_GOAL_VIEW { get; set; }
        public string SAT_PRIMARY_CERTIFICATION_IND { get; set; }
        public string SAT_FIELDA_001 { get; set; }
        public string SAT_FIELDA_002 { get; set; }
        public string SAT_FIELDA_003 { get; set; }
        public string SAT_FIELDB_001 { get; set; }
        public string SAT_FIELDB_002 { get; set; }
        public string SAT_FIELDC_001 { get; set; }
        public string SAT_FIELDD_001 { get; set; }
        public string SAT_FIELDD_002 { get; set; }
        public string SAT_FIELDD_003 { get; set; }
        public string SAT_FIELDD_004 { get; set; }
        public string SAT_FIELDD_005 { get; set; }
        public string SAT_FIELDD_006 { get; set; }
        public Nullable<decimal> SAT_LAST_MODIFIED { get; set; }
    }
}
