//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_ACCRUAL
    {
        public string SFR_OID { get; set; }
        public string SFR_STF_OID { get; set; }
        public Nullable<System.DateTime> SFR_DATE { get; set; }
        public string SFR_TYPE { get; set; }
        public string SFR_REASON_CODE { get; set; }
        public Nullable<decimal> SFR_TOTAL_UNITS { get; set; }
        public string SFR_FIELDA_001 { get; set; }
        public string SFR_FIELDA_002 { get; set; }
        public string SFR_FIELDA_003 { get; set; }
        public string SFR_FIELDA_004 { get; set; }
        public string SFR_FIELDA_005 { get; set; }
        public string SFR_FIELDB_001 { get; set; }
        public string SFR_FIELDB_002 { get; set; }
        public string SFR_FIELDB_003 { get; set; }
        public string SFR_FIELDB_004 { get; set; }
        public string SFR_FIELDB_005 { get; set; }
        public string SFR_FIELDC_001 { get; set; }
        public string SFR_FIELDC_002 { get; set; }
        public string SFR_FIELDD_001 { get; set; }
        public Nullable<decimal> SFR_LAST_MODIFIED { get; set; }
    }
}
