//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_PD_ACTIVITY_ATTENDANCE
    {
        public string SAA_OID { get; set; }
        public string SAA_STF_OID { get; set; }
        public string SAA_PDM_OID { get; set; }
        public string SAA_CODE { get; set; }
        public string SAA_ABSENT_IND { get; set; }
        public Nullable<decimal> SAA_PORTION_ABSENT { get; set; }
        public string SAA_COMMENT { get; set; }
        public string SAA_FIELDA_001 { get; set; }
        public string SAA_FIELDA_002 { get; set; }
        public string SAA_FIELDA_003 { get; set; }
        public string SAA_FIELDB_001 { get; set; }
        public string SAA_FIELDB_002 { get; set; }
        public string SAA_FIELDC_001 { get; set; }
        public Nullable<decimal> SAA_LAST_MODIFIED { get; set; }
    }
}
