//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_COURSE_WORK
    {
        public string SCW_OID { get; set; }
        public string SCW_STF_OID { get; set; }
        public string SCW_COURSE_TITLE { get; set; }
        public string SCW_COURSE_DESCRIPTION { get; set; }
        public string SCW_INSTITUTION { get; set; }
        public Nullable<System.DateTime> SCW_START_DATE { get; set; }
        public Nullable<System.DateTime> SCW_DATE_COMPLETED { get; set; }
        public string SCW_FORMAT { get; set; }
        public string SCW_CONTENT_AREA { get; set; }
        public string SCW_GRADE_EARNED { get; set; }
        public Nullable<decimal> SCW_CREDIT { get; set; }
        public string SCW_CREDIT_TYPE { get; set; }
        public Nullable<decimal> SCW_CONTENT_POINTS { get; set; }
        public Nullable<decimal> SCW_PEDAGOGY_POINTS { get; set; }
        public Nullable<decimal> SCW_OTHER_POINTS { get; set; }
        public Nullable<decimal> SCW_COST { get; set; }
        public string SCW_FUNDING_SOURCE { get; set; }
        public string SCW_STATUS { get; set; }
        public string SCW_PRIMARY_CERTIFICATION_IND { get; set; }
        public string SCW_FIELDA_001 { get; set; }
        public string SCW_FIELDA_002 { get; set; }
        public string SCW_FIELDA_003 { get; set; }
        public string SCW_FIELDA_004 { get; set; }
        public string SCW_FIELDA_005 { get; set; }
        public string SCW_FIELDB_001 { get; set; }
        public string SCW_FIELDB_002 { get; set; }
        public string SCW_FIELDB_003 { get; set; }
        public string SCW_FIELDC_001 { get; set; }
        public string SCW_FIELDC_002 { get; set; }
        public string SCW_FIELDD_001 { get; set; }
        public byte[] SCW_FIELDE_001 { get; set; }
        public byte[] SCW_FIELDE_002 { get; set; }
        public Nullable<decimal> SCW_LAST_MODIFIED { get; set; }
    }
}
