//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_TRANSCRIPT_RUBRIC
    {
        public string TRR_OID { get; set; }
        public string TRR_TRN_OID { get; set; }
        public string TRR_GTC_OID { get; set; }
        public string TRR_RBA_OID { get; set; }
        public Nullable<decimal> TRR_LAST_MODIFIED { get; set; }
    }
}
