//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ASSESSMENT
    {
        public string ASM_OID { get; set; }
        public string ASM_STD_OID { get; set; }
        public string ASM_SKL_OID { get; set; }
        public string ASM_ASD_OID { get; set; }
        public Nullable<System.DateTime> ASM_DATE { get; set; }
        public Nullable<decimal> ASM_RAW_SCORE { get; set; }
        public Nullable<decimal> ASM_SCALE_SCORE { get; set; }
        public Nullable<decimal> ASM_SCORE_03 { get; set; }
        public Nullable<decimal> ASM_SCORE_04 { get; set; }
        public Nullable<decimal> ASM_SCORE_05 { get; set; }
        public Nullable<decimal> ASM_SCORE_06 { get; set; }
        public Nullable<decimal> ASM_SCORE_07 { get; set; }
        public Nullable<decimal> ASM_SCORE_08 { get; set; }
        public string ASM_PERFORMANCE_LEVEL { get; set; }
        public string ASM_GRADE_LEVEL_CODE { get; set; }
        public string ASM_FIELDA_001 { get; set; }
        public string ASM_FIELDA_002 { get; set; }
        public string ASM_FIELDA_003 { get; set; }
        public string ASM_FIELDA_004 { get; set; }
        public string ASM_FIELDA_005 { get; set; }
        public string ASM_FIELDA_006 { get; set; }
        public string ASM_FIELDA_007 { get; set; }
        public string ASM_FIELDA_008 { get; set; }
        public string ASM_FIELDA_009 { get; set; }
        public string ASM_FIELDA_010 { get; set; }
        public string ASM_FIELDA_011 { get; set; }
        public string ASM_FIELDA_012 { get; set; }
        public string ASM_FIELDA_013 { get; set; }
        public string ASM_FIELDA_014 { get; set; }
        public string ASM_FIELDA_015 { get; set; }
        public string ASM_FIELDA_016 { get; set; }
        public string ASM_FIELDA_017 { get; set; }
        public string ASM_FIELDA_018 { get; set; }
        public string ASM_FIELDA_019 { get; set; }
        public string ASM_FIELDA_020 { get; set; }
        public string ASM_FIELDA_021 { get; set; }
        public string ASM_FIELDA_022 { get; set; }
        public string ASM_FIELDA_023 { get; set; }
        public string ASM_FIELDA_024 { get; set; }
        public string ASM_FIELDA_025 { get; set; }
        public string ASM_FIELDA_026 { get; set; }
        public string ASM_FIELDA_027 { get; set; }
        public string ASM_FIELDA_028 { get; set; }
        public string ASM_FIELDA_029 { get; set; }
        public string ASM_FIELDA_030 { get; set; }
        public string ASM_FIELDA_031 { get; set; }
        public string ASM_FIELDA_032 { get; set; }
        public string ASM_FIELDA_033 { get; set; }
        public string ASM_FIELDA_034 { get; set; }
        public string ASM_FIELDA_035 { get; set; }
        public string ASM_FIELDA_036 { get; set; }
        public string ASM_FIELDA_037 { get; set; }
        public string ASM_FIELDA_038 { get; set; }
        public string ASM_FIELDA_039 { get; set; }
        public string ASM_FIELDA_040 { get; set; }
        public string ASM_FIELDA_041 { get; set; }
        public string ASM_FIELDA_042 { get; set; }
        public string ASM_FIELDA_043 { get; set; }
        public string ASM_FIELDA_044 { get; set; }
        public string ASM_FIELDA_045 { get; set; }
        public string ASM_FIELDA_046 { get; set; }
        public string ASM_FIELDA_047 { get; set; }
        public string ASM_FIELDA_048 { get; set; }
        public string ASM_FIELDA_049 { get; set; }
        public string ASM_FIELDA_050 { get; set; }
        public string ASM_FIELDA_051 { get; set; }
        public string ASM_FIELDA_052 { get; set; }
        public string ASM_FIELDA_053 { get; set; }
        public string ASM_FIELDA_054 { get; set; }
        public string ASM_FIELDA_055 { get; set; }
        public string ASM_FIELDA_056 { get; set; }
        public string ASM_FIELDA_057 { get; set; }
        public string ASM_FIELDA_058 { get; set; }
        public string ASM_FIELDA_059 { get; set; }
        public string ASM_FIELDA_060 { get; set; }
        public string ASM_FIELDA_061 { get; set; }
        public string ASM_FIELDA_062 { get; set; }
        public string ASM_FIELDA_063 { get; set; }
        public string ASM_FIELDA_064 { get; set; }
        public string ASM_FIELDA_065 { get; set; }
        public string ASM_FIELDA_066 { get; set; }
        public string ASM_FIELDA_067 { get; set; }
        public string ASM_FIELDA_068 { get; set; }
        public string ASM_FIELDA_069 { get; set; }
        public string ASM_FIELDA_070 { get; set; }
        public string ASM_FIELDA_071 { get; set; }
        public string ASM_FIELDA_072 { get; set; }
        public string ASM_FIELDA_073 { get; set; }
        public string ASM_FIELDA_074 { get; set; }
        public string ASM_FIELDA_075 { get; set; }
        public string ASM_FIELDB_001 { get; set; }
        public string ASM_FIELDB_002 { get; set; }
        public string ASM_FIELDB_003 { get; set; }
        public string ASM_FIELDB_004 { get; set; }
        public string ASM_FIELDB_005 { get; set; }
        public string ASM_FIELDB_006 { get; set; }
        public string ASM_FIELDB_007 { get; set; }
        public string ASM_FIELDB_008 { get; set; }
        public string ASM_FIELDB_009 { get; set; }
        public string ASM_FIELDB_010 { get; set; }
        public string ASM_FIELDB_011 { get; set; }
        public string ASM_FIELDB_012 { get; set; }
        public string ASM_FIELDB_013 { get; set; }
        public string ASM_FIELDB_014 { get; set; }
        public string ASM_FIELDB_015 { get; set; }
        public string ASM_FIELDB_016 { get; set; }
        public string ASM_FIELDB_017 { get; set; }
        public string ASM_FIELDB_018 { get; set; }
        public string ASM_FIELDB_019 { get; set; }
        public string ASM_FIELDB_020 { get; set; }
        public string ASM_FIELDC_001 { get; set; }
        public string ASM_FIELDC_002 { get; set; }
        public string ASM_FIELDC_003 { get; set; }
        public string ASM_FIELDC_004 { get; set; }
        public string ASM_FIELDC_005 { get; set; }
        public string ASM_FIELDC_006 { get; set; }
        public string ASM_FIELDC_007 { get; set; }
        public string ASM_FIELDC_008 { get; set; }
        public string ASM_FIELDC_009 { get; set; }
        public string ASM_FIELDC_010 { get; set; }
        public string ASM_FIELDC_011 { get; set; }
        public string ASM_FIELDC_012 { get; set; }
        public string ASM_FIELDC_013 { get; set; }
        public string ASM_FIELDC_014 { get; set; }
        public string ASM_FIELDC_015 { get; set; }
        public string ASM_FIELDD_001 { get; set; }
        public string ASM_FIELDD_002 { get; set; }
        public string ASM_FIELDD_003 { get; set; }
        public string ASM_FIELDD_004 { get; set; }
        public string ASM_FIELDD_005 { get; set; }
        public byte[] ASM_FIELDE_001 { get; set; }
        public byte[] ASM_FIELDE_002 { get; set; }
        public byte[] ASM_FIELDE_003 { get; set; }
        public byte[] ASM_FIELDE_004 { get; set; }
        public byte[] ASM_FIELDE_005 { get; set; }
        public byte[] ASM_FIELDE_006 { get; set; }
        public byte[] ASM_FIELDE_007 { get; set; }
        public byte[] ASM_FIELDE_008 { get; set; }
        public byte[] ASM_FIELDE_009 { get; set; }
        public byte[] ASM_FIELDE_010 { get; set; }
        public Nullable<decimal> ASM_LAST_MODIFIED { get; set; }
    }
}
