//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_CONDUCT_INCIDENT
    {
        public string CND_OID { get; set; }
        public string CND_STD_OID { get; set; }
        public string CND_SKL_OID { get; set; }
        public string CND_STF_OID_REFERRAL { get; set; }
        public string CND_STF_OID_OWNER { get; set; }
        public string CND_INCIDENT_ID { get; set; }
        public string CND_INCIDENT_CODE { get; set; }
        public string CND_INCIDENT_CODES_VIEW { get; set; }
        public Nullable<System.DateTime> CND_INCIDENT_DATE { get; set; }
        public Nullable<System.DateTime> CND_INCIDENT_TIME { get; set; }
        public string CND_INCIDENT_LOCATION { get; set; }
        public string CND_INCIDENT_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CND_MEETING_DATE { get; set; }
        public Nullable<System.DateTime> CND_ACTIVITY_DATE { get; set; }
        public string CND_STD_OID_VCTIM { get; set; }
        public string CND_FIELDA_001 { get; set; }
        public string CND_FIELDA_002 { get; set; }
        public string CND_FIELDA_003 { get; set; }
        public string CND_FIELDA_004 { get; set; }
        public string CND_FIELDA_005 { get; set; }
        public string CND_FIELDA_006 { get; set; }
        public string CND_FIELDA_007 { get; set; }
        public string CND_FIELDA_008 { get; set; }
        public string CND_FIELDA_009 { get; set; }
        public string CND_FIELDA_010 { get; set; }
        public string CND_FIELDA_011 { get; set; }
        public string CND_FIELDA_012 { get; set; }
        public string CND_FIELDA_013 { get; set; }
        public string CND_FIELDA_014 { get; set; }
        public string CND_FIELDA_015 { get; set; }
        public string CND_FIELDA_016 { get; set; }
        public string CND_FIELDA_017 { get; set; }
        public string CND_FIELDA_018 { get; set; }
        public string CND_FIELDA_019 { get; set; }
        public string CND_FIELDA_020 { get; set; }
        public string CND_FIELDA_021 { get; set; }
        public string CND_FIELDA_022 { get; set; }
        public string CND_FIELDA_023 { get; set; }
        public string CND_FIELDA_024 { get; set; }
        public string CND_FIELDB_001 { get; set; }
        public string CND_FIELDB_002 { get; set; }
        public string CND_FIELDB_003 { get; set; }
        public string CND_FIELDB_004 { get; set; }
        public string CND_FIELDB_005 { get; set; }
        public string CND_FIELDB_006 { get; set; }
        public string CND_FIELDB_007 { get; set; }
        public string CND_FIELDB_008 { get; set; }
        public string CND_FIELDB_009 { get; set; }
        public string CND_FIELDB_010 { get; set; }
        public string CND_FIELDB_011 { get; set; }
        public string CND_FIELDB_012 { get; set; }
        public string CND_FIELDB_013 { get; set; }
        public string CND_FIELDC_001 { get; set; }
        public string CND_FIELDC_002 { get; set; }
        public string CND_FIELDC_003 { get; set; }
        public string CND_FIELDC_004 { get; set; }
        public string CND_FIELDC_005 { get; set; }
        public string CND_FIELDC_006 { get; set; }
        public string CND_FIELDC_007 { get; set; }
        public string CND_FIELDC_008 { get; set; }
        public string CND_FIELDC_009 { get; set; }
        public string CND_FIELDC_010 { get; set; }
        public string CND_FIELDC_011 { get; set; }
        public string CND_FIELDD_001 { get; set; }
        public string CND_FIELDD_002 { get; set; }
        public string CND_FIELDD_003 { get; set; }
        public string CND_FIELDD_004 { get; set; }
        public string CND_FIELDD_005 { get; set; }
        public byte[] CND_FIELDE_001 { get; set; }
        public byte[] CND_FIELDE_002 { get; set; }
        public Nullable<decimal> CND_LAST_MODIFIED { get; set; }
        public Nullable<decimal> CND_INV_STATUS { get; set; }
        public string CND_WFL_OID { get; set; }
    }
}
