//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_CASE_PERSON
    {
        public string SCP_OID { get; set; }
        public string SCP_STC_OID { get; set; }
        public string SCP_PSN_OID { get; set; }
        public string SCP_NAME_VIEW { get; set; }
        public string SCP_FIELDA_001 { get; set; }
        public string SCP_FIELDA_002 { get; set; }
        public string SCP_FIELDA_003 { get; set; }
        public string SCP_FIELDA_004 { get; set; }
        public string SCP_FIELDA_005 { get; set; }
        public string SCP_FIELDA_006 { get; set; }
        public string SCP_FIELDA_007 { get; set; }
        public string SCP_FIELDA_008 { get; set; }
        public string SCP_FIELDA_009 { get; set; }
        public string SCP_FIELDA_010 { get; set; }
        public string SCP_FIELDA_011 { get; set; }
        public string SCP_FIELDA_012 { get; set; }
        public string SCP_FIELDA_013 { get; set; }
        public string SCP_FIELDA_014 { get; set; }
        public string SCP_FIELDA_015 { get; set; }
        public string SCP_FIELDA_016 { get; set; }
        public string SCP_FIELDA_017 { get; set; }
        public string SCP_FIELDA_018 { get; set; }
        public string SCP_FIELDA_019 { get; set; }
        public string SCP_FIELDA_020 { get; set; }
        public string SCP_FIELDA_021 { get; set; }
        public string SCP_FIELDA_022 { get; set; }
        public string SCP_FIELDA_023 { get; set; }
        public string SCP_FIELDA_024 { get; set; }
        public string SCP_FIELDA_025 { get; set; }
        public string SCP_FIELDA_026 { get; set; }
        public string SCP_FIELDA_027 { get; set; }
        public string SCP_FIELDA_028 { get; set; }
        public string SCP_FIELDA_029 { get; set; }
        public string SCP_FIELDA_030 { get; set; }
        public string SCP_FIELDA_031 { get; set; }
        public string SCP_FIELDA_032 { get; set; }
        public string SCP_FIELDA_033 { get; set; }
        public string SCP_FIELDA_034 { get; set; }
        public string SCP_FIELDA_035 { get; set; }
        public string SCP_FIELDA_036 { get; set; }
        public string SCP_FIELDA_037 { get; set; }
        public string SCP_FIELDA_038 { get; set; }
        public string SCP_FIELDA_039 { get; set; }
        public string SCP_FIELDA_040 { get; set; }
        public string SCP_FIELDA_041 { get; set; }
        public string SCP_FIELDA_042 { get; set; }
        public string SCP_FIELDA_043 { get; set; }
        public string SCP_FIELDA_044 { get; set; }
        public string SCP_FIELDA_045 { get; set; }
        public string SCP_FIELDA_046 { get; set; }
        public string SCP_FIELDA_047 { get; set; }
        public string SCP_FIELDA_048 { get; set; }
        public string SCP_FIELDA_049 { get; set; }
        public string SCP_FIELDA_050 { get; set; }
        public string SCP_FIELDB_001 { get; set; }
        public string SCP_FIELDB_002 { get; set; }
        public string SCP_FIELDB_003 { get; set; }
        public string SCP_FIELDB_004 { get; set; }
        public string SCP_FIELDB_005 { get; set; }
        public string SCP_FIELDB_006 { get; set; }
        public string SCP_FIELDB_007 { get; set; }
        public string SCP_FIELDB_008 { get; set; }
        public string SCP_FIELDB_009 { get; set; }
        public string SCP_FIELDB_010 { get; set; }
        public string SCP_FIELDB_011 { get; set; }
        public string SCP_FIELDB_012 { get; set; }
        public string SCP_FIELDB_013 { get; set; }
        public string SCP_FIELDB_014 { get; set; }
        public string SCP_FIELDB_015 { get; set; }
        public string SCP_FIELDB_016 { get; set; }
        public string SCP_FIELDB_017 { get; set; }
        public string SCP_FIELDB_018 { get; set; }
        public string SCP_FIELDB_019 { get; set; }
        public string SCP_FIELDB_020 { get; set; }
        public string SCP_FIELDB_021 { get; set; }
        public string SCP_FIELDB_022 { get; set; }
        public string SCP_FIELDB_023 { get; set; }
        public string SCP_FIELDB_024 { get; set; }
        public string SCP_FIELDB_025 { get; set; }
        public string SCP_FIELDC_001 { get; set; }
        public string SCP_FIELDC_002 { get; set; }
        public string SCP_FIELDC_003 { get; set; }
        public string SCP_FIELDC_004 { get; set; }
        public string SCP_FIELDC_005 { get; set; }
        public string SCP_FIELDC_006 { get; set; }
        public string SCP_FIELDC_007 { get; set; }
        public string SCP_FIELDC_008 { get; set; }
        public string SCP_FIELDC_009 { get; set; }
        public string SCP_FIELDC_010 { get; set; }
        public string SCP_FIELDC_011 { get; set; }
        public string SCP_FIELDC_012 { get; set; }
        public string SCP_FIELDC_013 { get; set; }
        public string SCP_FIELDC_014 { get; set; }
        public string SCP_FIELDC_015 { get; set; }
        public string SCP_FIELDD_001 { get; set; }
        public string SCP_FIELDD_002 { get; set; }
        public string SCP_FIELDD_003 { get; set; }
        public string SCP_FIELDD_004 { get; set; }
        public string SCP_FIELDD_005 { get; set; }
        public string SCP_FIELDD_006 { get; set; }
        public string SCP_FIELDD_007 { get; set; }
        public string SCP_FIELDD_008 { get; set; }
        public string SCP_FIELDD_009 { get; set; }
        public string SCP_FIELDD_010 { get; set; }
        public byte[] SCP_FIELDE_001 { get; set; }
        public byte[] SCP_FIELDE_002 { get; set; }
        public byte[] SCP_FIELDE_003 { get; set; }
        public byte[] SCP_FIELDE_004 { get; set; }
        public byte[] SCP_FIELDE_005 { get; set; }
        public string SCP_FIELDO_001 { get; set; }
        public string SCP_FIELDO_002 { get; set; }
        public string SCP_FIELDO_003 { get; set; }
        public string SCP_FIELDO_004 { get; set; }
        public string SCP_FIELDO_005 { get; set; }
        public Nullable<decimal> SCP_LAST_MODIFIED { get; set; }
        public string SCP_STC_OID_RELATED { get; set; }
    }
}
