//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ENROLLMENT
    {
        public string ENR_OID { get; set; }
        public string ENR_STD_OID { get; set; }
        public string ENR_SKL_OID { get; set; }
        public string ENR_ENROLLMENT_TYPE { get; set; }
        public Nullable<System.DateTime> ENR_ENROLLMENT_DATE { get; set; }
        public string ENR_ENROLLMENT_CODE { get; set; }
        public string ENR_ENROLLMENT_REASON_CODE { get; set; }
        public string ENR_ENROLLMENT_STATUS_CODE { get; set; }
        public Nullable<decimal> ENR_YOG { get; set; }
        public Nullable<decimal> ENR_TIMESTAMP { get; set; }
        public string ENR_FIELDA_001 { get; set; }
        public string ENR_FIELDA_002 { get; set; }
        public string ENR_FIELDA_003 { get; set; }
        public string ENR_FIELDA_004 { get; set; }
        public string ENR_FIELDA_005 { get; set; }
        public string ENR_FIELDA_006 { get; set; }
        public string ENR_FIELDA_007 { get; set; }
        public string ENR_FIELDA_008 { get; set; }
        public string ENR_FIELDA_009 { get; set; }
        public string ENR_FIELDA_010 { get; set; }
        public string ENR_FIELDB_001 { get; set; }
        public string ENR_FIELDB_002 { get; set; }
        public string ENR_FIELDB_003 { get; set; }
        public string ENR_FIELDB_004 { get; set; }
        public string ENR_FIELDB_005 { get; set; }
        public string ENR_FIELDB_006 { get; set; }
        public string ENR_FIELDB_007 { get; set; }
        public string ENR_FIELDB_008 { get; set; }
        public string ENR_FIELDB_009 { get; set; }
        public string ENR_FIELDB_010 { get; set; }
        public string ENR_FIELDC_001 { get; set; }
        public string ENR_FIELDC_002 { get; set; }
        public string ENR_FIELDC_003 { get; set; }
        public string ENR_FIELDC_004 { get; set; }
        public string ENR_FIELDC_005 { get; set; }
        public string ENR_FIELDD_001 { get; set; }
        public string ENR_FIELDD_002 { get; set; }
        public string ENR_FIELDD_003 { get; set; }
        public string ENR_FIELDD_004 { get; set; }
        public string ENR_FIELDD_005 { get; set; }
        public string ENR_FIELDD_006 { get; set; }
        public string ENR_FIELDD_007 { get; set; }
        public string ENR_FIELDD_008 { get; set; }
        public string ENR_FIELDD_009 { get; set; }
        public string ENR_FIELDD_010 { get; set; }
        public string ENR_FIELDD_011 { get; set; }
        public string ENR_FIELDD_012 { get; set; }
        public Nullable<decimal> ENR_LAST_MODIFIED { get; set; }
        public string ENR_FIELDA_011 { get; set; }
        public string ENR_FIELDA_012 { get; set; }
        public string ENR_FIELDA_013 { get; set; }
        public string ENR_FIELDA_014 { get; set; }
        public string ENR_FIELDA_015 { get; set; }
        public string ENR_FIELDB_011 { get; set; }
        public string ENR_FIELDB_012 { get; set; }
        public string ENR_FIELDB_013 { get; set; }
        public string ENR_FIELDB_014 { get; set; }
        public string ENR_FIELDB_015 { get; set; }
        public string ENR_FIELDC_006 { get; set; }
        public string ENR_FIELDC_007 { get; set; }
        public string ENR_FIELDC_008 { get; set; }
        public string ENR_FIELDC_009 { get; set; }
        public string ENR_FIELDC_010 { get; set; }
        public string ENR_ORIGINATING_CLASS { get; set; }
        public string ENR_ORIGINAL_SYNPOSIS { get; set; }
        public string ENR_FIELDA_016 { get; set; }
        public string ENR_FIELDA_017 { get; set; }
        public string ENR_FIELDA_018 { get; set; }
        public string ENR_FIELDA_019 { get; set; }
        public string ENR_FIELDA_020 { get; set; }
        public string ENR_FIELDA_021 { get; set; }
        public string ENR_FIELDA_022 { get; set; }
        public string ENR_FIELDA_023 { get; set; }
        public string ENR_FIELDA_024 { get; set; }
        public string ENR_FIELDA_025 { get; set; }
        public string ENR_FIELDA_026 { get; set; }
        public string ENR_FIELDA_027 { get; set; }
        public string ENR_FIELDA_028 { get; set; }
        public string ENR_FIELDA_029 { get; set; }
        public string ENR_FIELDA_030 { get; set; }
        public string ENR_FIELDB_016 { get; set; }
        public string ENR_FIELDB_017 { get; set; }
        public string ENR_FIELDB_018 { get; set; }
        public string ENR_FIELDB_019 { get; set; }
        public string ENR_FIELDB_020 { get; set; }
        public string ENR_FIELDB_021 { get; set; }
        public string ENR_FIELDB_022 { get; set; }
        public string ENR_FIELDB_023 { get; set; }
        public string ENR_FIELDB_024 { get; set; }
        public string ENR_FIELDB_025 { get; set; }
        public string ENR_FIELDB_026 { get; set; }
        public string ENR_FIELDB_027 { get; set; }
        public string ENR_FIELDB_028 { get; set; }
        public string ENR_FIELDB_029 { get; set; }
        public string ENR_FIELDB_030 { get; set; }
        public string ENR_FIELDC_011 { get; set; }
        public string ENR_FIELDC_012 { get; set; }
        public string ENR_FIELDC_013 { get; set; }
        public string ENR_FIELDC_014 { get; set; }
        public string ENR_FIELDC_015 { get; set; }
        public string ENR_FIELDC_016 { get; set; }
        public string ENR_FIELDC_017 { get; set; }
        public string ENR_FIELDC_018 { get; set; }
        public string ENR_FIELDC_019 { get; set; }
        public string ENR_FIELDC_020 { get; set; }
        public string ENR_BULK_INSERT_IND { get; set; }
        public string ENR_GUID { get; set; }
    }
}
