//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIPTION_DEFINITION
    {
        public string SDF_OID { get; set; }
        public string SDF_ORG_OID_1 { get; set; }
        public string SDF_ORG_OID_2 { get; set; }
        public string SDF_ORG_OID_3 { get; set; }
        public string SDF_ORG_OID_4 { get; set; }
        public string SDF_ORG_OID_5 { get; set; }
        public string SDF_PROC_ID { get; set; }
        public string SDF_NAME { get; set; }
        public string SDF_DESCRIPTION { get; set; }
        public string SDF_SUBJECT { get; set; }
        public string SDF_MEMO { get; set; }
        public string SDF_ENABLED { get; set; }
        public Nullable<System.DateTime> SDF_BEGIN_DATE { get; set; }
        public string SDF_PARAM_ENABLED { get; set; }
        public string SDF_PARAM_NAME { get; set; }
        public Nullable<decimal> SDF_LAST_RUN { get; set; }
        public Nullable<decimal> SDF_LAST_MODIFIED { get; set; }
    }
}
