//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PREFERENCE
    {
        public string PRF_OID { get; set; }
        public string PRF_PRD_OID { get; set; }
        public string PRF_VALUE { get; set; }
        public Nullable<decimal> PRF_OWNER_TYPE { get; set; }
        public string PRF_OWNER_OID { get; set; }
        public Nullable<decimal> PRF_LAST_MODIFIED { get; set; }
    }
}
