//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public string USR_OID { get; set; }
        public string USR_ORG_OID_1 { get; set; }
        public string USR_ORG_OID_2 { get; set; }
        public string USR_ORG_OID_3 { get; set; }
        public string USR_ORG_OID_4 { get; set; }
        public string USR_ORG_OID_5 { get; set; }
        public string USR_PSN_OID { get; set; }
        public string USR_NAME_VIEW { get; set; }
        public string USR_LOGIN_NAME { get; set; }
        public string USR_PASSWORD { get; set; }
        public string USR_PASSWORD_HISTORY { get; set; }
        public string USR_GENERATED_PASSWORD { get; set; }
        public Nullable<System.DateTime> USR_ACCT_START_DATE { get; set; }
        public Nullable<System.DateTime> USR_ACCT_EXPIRATION_DATE { get; set; }
        public Nullable<System.DateTime> USR_PW_EXPIRATION_DATE { get; set; }
        public Nullable<decimal> USR_TIMEOUT { get; set; }
        public Nullable<decimal> USR_INVALID_LOGIN_COUNT { get; set; }
        public Nullable<decimal> USR_ALLOW_ATTEMPTS { get; set; }
        public Nullable<decimal> USR_MAX_SESSION_COUNT { get; set; }
        public string USR_LOGIN_DISABLED_IND { get; set; }
        public string USR_ALLOW_FROM { get; set; }
        public string USR_PWDRECOVERY_QUESTION { get; set; }
        public string USR_PWDRECOVERY_ANSWER { get; set; }
        public Nullable<decimal> USR_PWDRECOVERY_INVALID_COUNT { get; set; }
        public string USR_PWDRECOVERY_DISABLED_IND { get; set; }
        public string USR_AD_AUTHENTICATE_IND { get; set; }
        public string USR_AD_ID { get; set; }
        public Nullable<System.DateTime> USR_CREATION_DATE { get; set; }
        public string USR_FIELDA_001 { get; set; }
        public string USR_FIELDA_002 { get; set; }
        public string USR_FIELDA_003 { get; set; }
        public string USR_FIELDB_001 { get; set; }
        public string USR_FIELDB_002 { get; set; }
        public string USR_FIELDC_001 { get; set; }
        public Nullable<decimal> USR_LAST_MODIFIED { get; set; }
        public Nullable<decimal> USR_QUOTA { get; set; }
        public string USR_SELF_CREATED_IND { get; set; }
        public Nullable<System.DateTime> USR_EMAIL_VERIFIED_DATE { get; set; }
        public string USR_FIELDD_001 { get; set; }
        public string USR_SECOND_PASSWORD { get; set; }
        public Nullable<decimal> USR_SCD_INVALID_LOGIN_COUNT { get; set; }
        public string USR_SCDPW_LOGIN_DISABLED_IND { get; set; }
        public string USR_SCD_PWDRECOVERY_QUESTION { get; set; }
        public string USR_SCD_PWDRECOVERY_ANSWER { get; set; }
        public Nullable<decimal> USR_SCD_PWDREC_INVALID_COUNT { get; set; }
        public string USR_SCD_PWDREC_DISABLED_IND { get; set; }
        public string USR_SCD_PASSWORD_HISTORY { get; set; }
        public string USR_SCD_GENERATED_PASSWORD { get; set; }
        public Nullable<System.DateTime> USR_SCD_PW_EXPIRATION_DATE { get; set; }
        public string USR_SSO_GUID { get; set; }
        public string USR_REQUIRE_CAC { get; set; }
        public string USR_CERTIFICATE_SIGNATURE { get; set; }
    }
}
