//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_COMPLIANCE_RULE
    {
        public string WFC_OID { get; set; }
        public string WFC_WPH_OID { get; set; }
        public string WFC_WPO_OID { get; set; }
        public string WFC_NAME { get; set; }
        public string WFC_DESCRIPTION { get; set; }
        public Nullable<decimal> WFC_DAYS_TO_COMPLETE { get; set; }
        public Nullable<decimal> WFC_WARNING_THRESHOLD { get; set; }
        public Nullable<decimal> WFC_DAY_TYPE { get; set; }
        public string WFC_DISABLED_IND { get; set; }
        public string WFC_FIELDA_001 { get; set; }
        public string WFC_FIELDA_002 { get; set; }
        public string WFC_FIELDA_003 { get; set; }
        public string WFC_FIELDA_004 { get; set; }
        public string WFC_FIELDA_005 { get; set; }
        public string WFC_FIELDA_006 { get; set; }
        public string WFC_FIELDA_007 { get; set; }
        public string WFC_FIELDA_008 { get; set; }
        public string WFC_FIELDA_009 { get; set; }
        public string WFC_FIELDA_010 { get; set; }
        public string WFC_FIELDB_001 { get; set; }
        public string WFC_FIELDB_002 { get; set; }
        public string WFC_FIELDB_003 { get; set; }
        public string WFC_FIELDB_004 { get; set; }
        public string WFC_FIELDB_005 { get; set; }
        public Nullable<decimal> WFC_LAST_MODIFIED { get; set; }
    }
}
