//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_PROGRESS_FORM
    {
        public string WFF_OID { get; set; }
        public string WFF_WFP_OID { get; set; }
        public string WFF_FMI_OID { get; set; }
        public Nullable<decimal> WFF_LAST_MODIFIED { get; set; }
    }
}
