//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_MAP_REFERENCE
    {
        public string ZRM_OID { get; set; }
        public string ZRM_RTB_OID { get; set; }
        public string ZRM_SOURCE_CODE { get; set; }
        public string ZRM_RESULT_CODE { get; set; }
        public string ZRM_DISABLED_IND { get; set; }
        public Nullable<decimal> ZRM_LAST_MODIFIED { get; set; }
    }
}
