//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACADEMIC_TRACK_COURSE
    {
        public string ACR_OID { get; set; }
        public string ACR_ATS_OID { get; set; }
        public string ACR_COURSE_NUMBER { get; set; }
        public string ACR_COURSE_DESCRIPTION { get; set; }
        public string ACR_REQUIRED_IND { get; set; }
        public string ACR_DEFAULT_IND { get; set; }
        public Nullable<decimal> ACR_SEQUENCE_NUMBER { get; set; }
        public string ACR_APPROVAL_NEEDED_IND { get; set; }
        public string ACR_COURSE_NUMBER_LINKED { get; set; }
        public string ACR_FIELDA_001 { get; set; }
        public string ACR_FIELDA_002 { get; set; }
        public string ACR_FIELDA_003 { get; set; }
        public string ACR_FIELDA_004 { get; set; }
        public string ACR_FIELDA_005 { get; set; }
        public string ACR_FIELDA_006 { get; set; }
        public string ACR_FIELDA_007 { get; set; }
        public string ACR_FIELDA_008 { get; set; }
        public string ACR_FIELDA_009 { get; set; }
        public string ACR_FIELDA_010 { get; set; }
        public string ACR_FIELDB_001 { get; set; }
        public string ACR_FIELDB_002 { get; set; }
        public string ACR_FIELDB_003 { get; set; }
        public string ACR_FIELDB_004 { get; set; }
        public string ACR_FIELDB_005 { get; set; }
        public string ACR_FIELDB_006 { get; set; }
        public string ACR_FIELDB_007 { get; set; }
        public string ACR_FIELDB_008 { get; set; }
        public string ACR_FIELDB_009 { get; set; }
        public string ACR_FIELDB_010 { get; set; }
        public string ACR_FIELDC_001 { get; set; }
        public string ACR_FIELDC_002 { get; set; }
        public string ACR_FIELDC_003 { get; set; }
        public string ACR_FIELDC_004 { get; set; }
        public string ACR_FIELDC_005 { get; set; }
        public string ACR_LAST_MODIFIED { get; set; }
    }
}
