//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR
    {
        public string CAL_OID { get; set; }
        public string CAL_ORG_OID_1 { get; set; }
        public string CAL_ORG_OID_2 { get; set; }
        public string CAL_ORG_OID_3 { get; set; }
        public string CAL_ORG_OID_4 { get; set; }
        public string CAL_ORG_OID_5 { get; set; }
        public string CAL_CTX_OID { get; set; }
        public Nullable<System.DateTime> CAL_DATE { get; set; }
        public string CAL_IN_SESSION_IND { get; set; }
        public string CAL_SCHEDULE_DAY_TYPE { get; set; }
        public string CAL_FIELDA_001 { get; set; }
        public string CAL_FIELDA_002 { get; set; }
        public string CAL_FIELDA_003 { get; set; }
        public string CAL_FIELDA_004 { get; set; }
        public string CAL_FIELDA_005 { get; set; }
        public string CAL_FIELDB_001 { get; set; }
        public string CAL_FIELDB_002 { get; set; }
        public string CAL_FIELDB_003 { get; set; }
        public Nullable<decimal> CAL_LAST_MODIFIED { get; set; }
    }
}
