//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR_SCHOOL
    {
        public string CAS_OID { get; set; }
        public string CAS_SKL_OID { get; set; }
        public string CAS_CTX_OID { get; set; }
        public string CAS_CALENDAR_ID { get; set; }
        public Nullable<decimal> CAS_DAYS_IN_SESSION { get; set; }
        public string CAS_STATIC_IND { get; set; }
        public Nullable<decimal> CAS_REQ_IN_SESSION { get; set; }
        public Nullable<decimal> CAS_LAST_MODIFIED { get; set; }
        public string CAS_FIELDA_001 { get; set; }
        public string CAS_FIELDA_002 { get; set; }
        public string CAS_FIELDA_003 { get; set; }
        public string CAS_FIELDA_004 { get; set; }
        public string CAS_FIELDA_005 { get; set; }
        public string CAS_FIELDB_001 { get; set; }
        public string CAS_FIELDB_002 { get; set; }
    }
}
