//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR_STAFF
    {
        public string CAF_OID { get; set; }
        public string CAF_CTX_OID { get; set; }
        public string CAF_STAFF_CALENDAR_ID { get; set; }
        public Nullable<decimal> CAF_DAYS_IN_SESSION { get; set; }
        public string CAF_ROLLED_OVER_IND { get; set; }
        public Nullable<decimal> CAF_LAST_MODIFIED { get; set; }
    }
}
