//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR_SCHOOL_DATE
    {
        public string CSD_OID { get; set; }
        public string CSD_CAS_OID { get; set; }
        public Nullable<System.DateTime> CSD_DATE { get; set; }
        public string CSD_SCHEDULE_DAY_TYPE { get; set; }
        public Nullable<decimal> CSD_SCHEDULE_DAY_NUMBER { get; set; }
        public string CSD_BEL_OID { get; set; }
        public string CSD_IN_SESSION_IND { get; set; }
        public string CSD_FIELDA_001 { get; set; }
        public string CSD_FIELDA_002 { get; set; }
        public string CSD_FIELDA_003 { get; set; }
        public string CSD_FIELDA_004 { get; set; }
        public string CSD_FIELDA_005 { get; set; }
        public string CSD_FIELDB_001 { get; set; }
        public string CSD_FIELDB_002 { get; set; }
        public string CSD_FIELDB_003 { get; set; }
        public Nullable<decimal> CSD_LAST_MODIFIED { get; set; }
    }
}
