//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT_BANK_CODE
    {
        public string CBC_OID { get; set; }
        public string CBC_CBT_OID { get; set; }
        public string CBC_USR_OID_OWNER { get; set; }
        public string CBC_ID { get; set; }
        public string CBC_CODE { get; set; }
        public string CBC_PREVIEW { get; set; }
        public Nullable<decimal> CBC_SEQUENCE_NUMBER { get; set; }
        public string CBC_CATEGORY_1 { get; set; }
        public string CBC_CATEGORY_2 { get; set; }
        public string CBC_CATEGORY_3 { get; set; }
        public string CBC_DISABLED_IND { get; set; }
        public string CBC_FIELDA_001 { get; set; }
        public string CBC_FIELDA_002 { get; set; }
        public string CBC_FIELDA_003 { get; set; }
        public string CBC_FIELDA_004 { get; set; }
        public string CBC_FIELDA_005 { get; set; }
        public string CBC_FIELDB_001 { get; set; }
        public string CBC_FIELDB_002 { get; set; }
        public string CBC_FIELDB_003 { get; set; }
        public string CBC_FIELDB_004 { get; set; }
        public string CBC_FIELDB_005 { get; set; }
        public string CBC_FIELDC_001 { get; set; }
        public string CBC_FIELDC_002 { get; set; }
        public string CBC_FIELDC_003 { get; set; }
        public string CBC_FIELDC_004 { get; set; }
        public string CBC_FIELDC_005 { get; set; }
        public Nullable<decimal> CBC_LAST_MODIFIED { get; set; }
    }
}
