//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT_MERCURY
    {
        public string CMY_OID { get; set; }
        public string CMY_URL { get; set; }
        public Nullable<decimal> CMY_LAST_MODIFIED { get; set; }
    }
}
