//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_REQUISITE
    {
        public string CRU_OID { get; set; }
        public string CRU_CRS_OID { get; set; }
        public string CRU_CRU_OID { get; set; }
        public Nullable<decimal> CRU_TYPE { get; set; }
        public string CRU_MIN_PERFORMANCE_LEVEL { get; set; }
        public string CRU_COURSE_ID { get; set; }
        public string CRU_COMPOUND_IND { get; set; }
        public string CRU_REQUISITE_DEFINITION { get; set; }
        public string CRU_FIELDA_001 { get; set; }
        public string CRU_FIELDA_002 { get; set; }
        public string CRU_FIELDA_003 { get; set; }
        public string CRU_FIELDA_004 { get; set; }
        public string CRU_FIELDA_005 { get; set; }
        public string CRU_FIELDA_006 { get; set; }
        public string CRU_FIELDA_007 { get; set; }
        public string CRU_FIELDA_008 { get; set; }
        public string CRU_FIELDA_009 { get; set; }
        public string CRU_FIELDA_010 { get; set; }
        public string CRU_FIELDB_001 { get; set; }
        public string CRU_FIELDB_002 { get; set; }
        public string CRU_FIELDB_003 { get; set; }
        public string CRU_FIELDB_004 { get; set; }
        public string CRU_FIELDB_005 { get; set; }
        public string CRU_FIELDB_006 { get; set; }
        public string CRU_FIELDB_007 { get; set; }
        public string CRU_FIELDB_008 { get; set; }
        public string CRU_FIELDB_009 { get; set; }
        public string CRU_FIELDB_010 { get; set; }
        public string CRU_FIELDC_001 { get; set; }
        public string CRU_FIELDC_002 { get; set; }
        public string CRU_FIELDC_003 { get; set; }
        public string CRU_FIELDC_004 { get; set; }
        public string CRU_FIELDC_005 { get; set; }
        public Nullable<decimal> CRU_LAST_MODIFIED { get; set; }
    }
}
