//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRICULUM_INSTANCE
    {
        public string CIN_OID { get; set; }
        public string CIN_CMP_OID { get; set; }
        public string CIN_CLP_OID { get; set; }
        public string CIN_NOTES { get; set; }
        public Nullable<decimal> CIN_LAST_MODIFIED { get; set; }
        public string CIN_STF_OID { get; set; }
        public Nullable<decimal> CIN_START_DAY { get; set; }
        public Nullable<decimal> CIN_DURATION { get; set; }
        public Nullable<decimal> CIN_UPDATED_TIME { get; set; }
    }
}
