//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_RELATION_DISTRICT
    {
        public string RLD_OID { get; set; }
        public string RLD_REL_OID { get; set; }
        public string RLD_ORG_OID_1 { get; set; }
        public string RLD_ORG_OID_2 { get; set; }
        public string RLD_ORG_OID_3 { get; set; }
        public string RLD_ORG_OID_4 { get; set; }
        public string RLD_ORG_OID_5 { get; set; }
        public string RLD_USER_NAME_LONG { get; set; }
        public string RLD_USER_NAME_SHORT { get; set; }
        public string RLD_SHOW_RELATION_NAME_IND { get; set; }
        public string RLD_CASCADE_DELETE_WARN_IND { get; set; }
        public Nullable<decimal> RLD_LAST_MODIFIED { get; set; }
        public string RLD_DESCRIPTION { get; set; }
        public string RLD_HELP_ENABLED { get; set; }
    }
}
