//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_TABLE_EXTENDED
    {
        public string TBX_OID { get; set; }
        public string TBX_TBD_OID { get; set; }
        public string TBX_DDX_OID { get; set; }
        public string TBX_USER_NAME { get; set; }
        public Nullable<decimal> TBX_SEQUENCE_NUMBER { get; set; }
        public Nullable<decimal> TBX_LAST_MODIFIED { get; set; }
        public Nullable<decimal> TBX_AUDIT_TYPE { get; set; }
    }
}
