//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_VALIDATION_RULE
    {
        public string DVR_OID { get; set; }
        public string DVR_TBD_OID { get; set; }
        public string DVR_TBX_OID { get; set; }
        public string DVR_FDD_OID { get; set; }
        public string DVR_FDX_OID { get; set; }
        public string DVR_ID { get; set; }
        public string DVR_DESCRIPTION { get; set; }
        public string DVR_CONDITION { get; set; }
        public string DVR_EXPRESSION { get; set; }
        public string DVR_METHOD_ID { get; set; }
        public string DVR_QUERY { get; set; }
        public string DVR_COMMENTS { get; set; }
        public string DVR_ERROR_MESSAGE { get; set; }
        public string DVR_DISABLED_IND { get; set; }
        public string DVR_MASS_UPDATE_IND { get; set; }
        public string DVR_LIST_EDIT_IND { get; set; }
        public Nullable<decimal> DVR_LAST_MODIFIED { get; set; }
    }
}
