//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_FIELD
    {
        public string FLD_OID { get; set; }
        public string FLD_TBL_OID { get; set; }
        public Nullable<decimal> FLD_SEQUENCE_NUMBER { get; set; }
        public string FLD_DATABASE_NAME { get; set; }
        public string FLD_DATABASE_TYPE { get; set; }
        public Nullable<decimal> FLD_DATABASE_LENGTH { get; set; }
        public Nullable<decimal> FLD_DATABASE_DECIMAL { get; set; }
        public string FLD_JAVA_NAME { get; set; }
        public string FLD_JAVA_TYPE { get; set; }
        public string FLD_JDBC_TYPE { get; set; }
        public string FLD_XML_TAG_NAME { get; set; }
        public string FLD_SYSTEM_USE_ONLY_IND { get; set; }
        public string FLD_READ_ONLY_IND { get; set; }
        public Nullable<decimal> FLD_LAST_MODIFIED { get; set; }
    }
}
