//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public string EVT_OID { get; set; }
        public string EVT_OWNER_OID { get; set; }
        public Nullable<decimal> EVT_OWNER_TYPE { get; set; }
        public Nullable<System.DateTime> EVT_DATE { get; set; }
        public Nullable<System.DateTime> EVT_TIME { get; set; }
        public string EVT_SUMMARY { get; set; }
        public string EVT_LOCATION { get; set; }
        public string EVT_DESCRIPTION { get; set; }
        public Nullable<decimal> EVT_LAST_MODIFIED { get; set; }
    }
}
