//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_ENTRY_EXPORT
    {
        public string ENE_OID { get; set; }
        public string ENE_STD_OID { get; set; }
        public string ENE_SER_OID { get; set; }
        public Nullable<decimal> ENE_LAST_MODIFIED { get; set; }
    }
}
