//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_TIMETABLE
    {
        public string ETM_OID { get; set; }
        public string ETM_COM_OID { get; set; }
        public Nullable<System.DateTime> ETM_EXAM_TIME { get; set; }
        public string ETM_ROOM_VIEW { get; set; }
        public string ETM_PROCTOR_VIEW { get; set; }
        public string ETM_NOTES { get; set; }
        public string ETM_FIELDA_001 { get; set; }
        public string ETM_FIELDA_002 { get; set; }
        public string ETM_FIELDA_003 { get; set; }
        public string ETM_FIELDA_004 { get; set; }
        public string ETM_FIELDA_005 { get; set; }
        public string ETM_FIELDB_001 { get; set; }
        public string ETM_FIELDB_002 { get; set; }
        public string ETM_FIELDC_001 { get; set; }
        public Nullable<decimal> ETM_LAST_MODIFIED { get; set; }
    }
}
