//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_ENTRY
    {
        public string ENT_OID { get; set; }
        public string ENT_STD_OID { get; set; }
        public string ENT_OPT_OID { get; set; }
        public string ENT_FIELDA_001 { get; set; }
        public string ENT_FIELDA_002 { get; set; }
        public string ENT_FIELDA_003 { get; set; }
        public string ENT_FIELDA_004 { get; set; }
        public string ENT_FIELDA_005 { get; set; }
        public string ENT_FIELDA_006 { get; set; }
        public string ENT_FIELDA_007 { get; set; }
        public string ENT_FIELDA_008 { get; set; }
        public string ENT_FIELDA_009 { get; set; }
        public string ENT_FIELDA_010 { get; set; }
        public string ENT_FIELDB_001 { get; set; }
        public string ENT_FIELDB_002 { get; set; }
        public string ENT_FIELDB_003 { get; set; }
        public string ENT_FIELDB_004 { get; set; }
        public string ENT_FIELDB_005 { get; set; }
        public string ENT_FIELDB_006 { get; set; }
        public string ENT_FIELDB_007 { get; set; }
        public string ENT_FIELDB_008 { get; set; }
        public string ENT_FIELDB_009 { get; set; }
        public string ENT_FIELDB_010 { get; set; }
        public string ENT_FIELDC_001 { get; set; }
        public string ENT_FIELDC_002 { get; set; }
        public string ENT_FIELDC_003 { get; set; }
        public string ENT_FIELDC_004 { get; set; }
        public string ENT_FIELDC_005 { get; set; }
        public string ENT_FIELDD_001 { get; set; }
        public string ENT_FIELDD_002 { get; set; }
        public Nullable<decimal> ENT_LAST_MODIFIED { get; set; }
        public string ENT_FORECAST_GRADE { get; set; }
        public string ENT_ETR_OID { get; set; }
        public string ENT_ABSENT_IND { get; set; }
        public string ENT_ABSENT_REASON_CODE { get; set; }
        public string ENT_SYSTEM_CREATED_IND { get; set; }
    }
}
