//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_TRANSFER_FILE
    {
        public string TRF_OID { get; set; }
        public string TRF_FILENAME { get; set; }
        public Nullable<System.DateTime> TRF_DATETIME { get; set; }
        public string TRF_DATA_TYPE { get; set; }
        public string TRF_EXAM_SERIES { get; set; }
        public string TRF_YEAR { get; set; }
        public string TRF_LANGUAGE { get; set; }
        public string TRF_AWB_IDENTIFIER { get; set; }
        public string TRF_SEQUENCE_NUMBER { get; set; }
        public Nullable<decimal> TRF_LAST_MODIFIED { get; set; }
    }
}
