//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_OPTION
    {
        public string OPT_OID { get; set; }
        public string OPT_SYL_OID { get; set; }
        public string OPT_AWARDING_BODY { get; set; }
        public string OPT_SER_OID { get; set; }
        public string OPT_OPTION_ENTRY_CODE { get; set; }
        public string OPT_SYLLABUS_CODE { get; set; }
        public string OPT_EXAM_TYPE_QUAL_CERT { get; set; }
        public string OPT_EXAM_TYPE_LEVEL_CERT { get; set; }
        public string OPT_EXAM_TYPE_ITEM_CODE { get; set; }
        public string OPT_EXAM_TYPE_QUAL_UNIT { get; set; }
        public string OPT_EXAM_TYPE_LEVEL_UNIT { get; set; }
        public string OPT_EXAM_TYPE_PROCESS_CODE { get; set; }
        public string OPT_QCA_CLASSIFICATION_CODE { get; set; }
        public string OPT_QCA_ACCREDITATION_NUMBER { get; set; }
        public string OPT_TITLE { get; set; }
        public string OPT_FEE_DEFINED { get; set; }
        public Nullable<decimal> OPT_EXAMINATION_FEE { get; set; }
        public string OPT_FIRST_FORECAST_GRADESET { get; set; }
        public string OPT_SECOND_FORECAST_GRADESET { get; set; }
        public string OPT_RESULT_TYPE { get; set; }
        public string OPT_FIRST_GRADE { get; set; }
        public string OPT_SECOND_GRADE { get; set; }
        public string OPT_FIRST_GRADE_ENDORSEMENT { get; set; }
        public string OPT_SECOND_GRADE_ENDORSEMENT { get; set; }
        public Nullable<decimal> OPT_MAX_MARK_OR_UMS { get; set; }
        public Nullable<decimal> OPT_COMPONENT_COUNT { get; set; }
        public string OPT_FIELDA_001 { get; set; }
        public string OPT_FIELDA_002 { get; set; }
        public string OPT_FIELDA_003 { get; set; }
        public string OPT_FIELDA_004 { get; set; }
        public string OPT_FIELDA_005 { get; set; }
        public string OPT_FIELDA_006 { get; set; }
        public string OPT_FIELDA_007 { get; set; }
        public string OPT_FIELDA_008 { get; set; }
        public string OPT_FIELDA_009 { get; set; }
        public string OPT_FIELDA_010 { get; set; }
        public string OPT_FIELDA_011 { get; set; }
        public string OPT_FIELDA_012 { get; set; }
        public string OPT_FIELDA_013 { get; set; }
        public string OPT_FIELDA_014 { get; set; }
        public string OPT_FIELDA_015 { get; set; }
        public string OPT_FIELDA_016 { get; set; }
        public string OPT_FIELDA_017 { get; set; }
        public string OPT_FIELDA_018 { get; set; }
        public string OPT_FIELDA_019 { get; set; }
        public string OPT_FIELDA_020 { get; set; }
        public string OPT_FIELDB_001 { get; set; }
        public string OPT_FIELDB_002 { get; set; }
        public string OPT_FIELDB_003 { get; set; }
        public string OPT_FIELDB_004 { get; set; }
        public string OPT_FIELDB_005 { get; set; }
        public string OPT_FIELDB_006 { get; set; }
        public string OPT_FIELDB_007 { get; set; }
        public string OPT_FIELDB_008 { get; set; }
        public string OPT_FIELDB_009 { get; set; }
        public string OPT_FIELDB_010 { get; set; }
        public string OPT_FIELDB_011 { get; set; }
        public string OPT_FIELDB_012 { get; set; }
        public string OPT_FIELDB_013 { get; set; }
        public string OPT_FIELDB_014 { get; set; }
        public string OPT_FIELDB_015 { get; set; }
        public string OPT_FIELDB_016 { get; set; }
        public string OPT_FIELDB_017 { get; set; }
        public string OPT_FIELDB_018 { get; set; }
        public string OPT_FIELDB_019 { get; set; }
        public string OPT_FIELDB_020 { get; set; }
        public string OPT_FIELDC_001 { get; set; }
        public string OPT_FIELDC_002 { get; set; }
        public string OPT_FIELDC_003 { get; set; }
        public string OPT_FIELDC_004 { get; set; }
        public string OPT_FIELDC_005 { get; set; }
        public string OPT_FIELDC_006 { get; set; }
        public string OPT_FIELDC_007 { get; set; }
        public string OPT_FIELDC_008 { get; set; }
        public string OPT_FIELDC_009 { get; set; }
        public string OPT_FIELDC_010 { get; set; }
        public string OPT_FIELDD_001 { get; set; }
        public string OPT_FIELDD_002 { get; set; }
        public string OPT_FIELDD_003 { get; set; }
        public string OPT_FIELDD_004 { get; set; }
        public Nullable<decimal> OPT_LAST_MODIFIED { get; set; }
        public string OPT_DISABLED_IND { get; set; }
    }
}
