//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_ENTRY_CONTROL
    {
        public string EEC_OID { get; set; }
        public string EEC_SKL_OID { get; set; }
        public string EEC_SES_OID { get; set; }
        public Nullable<System.DateTime> EEC_START_DATE { get; set; }
        public Nullable<System.DateTime> EEC_END_DATE { get; set; }
        public string EEC_FIELDA_001 { get; set; }
        public string EEC_FIELDA_002 { get; set; }
        public string EEC_FIELDA_003 { get; set; }
        public string EEC_FIELDB_001 { get; set; }
        public string EEC_FIELDB_002 { get; set; }
        public Nullable<decimal> EEC_LAST_MODIFIED { get; set; }
    }
}
