//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELD_SET
    {
        public string FSN_OID { get; set; }
        public string FSN_OWNER_OID { get; set; }
        public Nullable<decimal> FSN_OWNER_TYPE { get; set; }
        public string FSN_DDX_OID { get; set; }
        public string FSN_NAME { get; set; }
        public string FSN_CONTEXT { get; set; }
        public string FSN_VIRTUAL_INDICATOR { get; set; }
        public string FSN_VIRTUAL_SOURCE { get; set; }
        public Nullable<decimal> FSN_LAST_MODIFIED { get; set; }
    }
}
