//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLDER_FILE
    {
        public string FIL_OID { get; set; }
        public string FIL_ORG_OID_1 { get; set; }
        public string FIL_ORG_OID_2 { get; set; }
        public string FIL_ORG_OID_3 { get; set; }
        public string FIL_ORG_OID_4 { get; set; }
        public string FIL_ORG_OID_5 { get; set; }
        public Nullable<decimal> FIL_OWNER_TYPE { get; set; }
        public string FIL_OWNER_OID { get; set; }
        public string FIL_STD_OID { get; set; }
        public string FIL_USR_OID_CREATOR { get; set; }
        public string FIL_USR_OID_MODIFY { get; set; }
        public string FIL_FIL_OID { get; set; }
        public string FIL_NAME { get; set; }
        public string FIL_PATH { get; set; }
        public string FIL_DESCRIPTION { get; set; }
        public string FIL_KEY_WORDS { get; set; }
        public string FIL_FILENAME { get; set; }
        public string FIL_FILE_EXT { get; set; }
        public Nullable<decimal> FIL_SIZE { get; set; }
        public Nullable<decimal> FIL_DOWNLOAD_COUNT { get; set; }
        public Nullable<System.DateTime> FIL_CREATE_DATE { get; set; }
        public Nullable<System.DateTime> FIL_EXPIRE_DATE { get; set; }
        public string FIL_FOLDER_IND { get; set; }
        public string FIL_PUBLIC_IND { get; set; }
        public byte[] FIL_FILE { get; set; }
        public Nullable<decimal> FIL_UPLOAD_TIME { get; set; }
        public Nullable<decimal> FIL_LAST_MODIFIED { get; set; }
    }
}
