//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUTURE_STUDENT_CAPACITY
    {
        public string FSC_OID { get; set; }
        public string FSC_STD_OID { get; set; }
        public string FSC_CTX_OID { get; set; }
        public string FSC_FIELDA_001 { get; set; }
        public string FSC_FIELDA_002 { get; set; }
        public string FSC_FIELDA_003 { get; set; }
        public string FSC_FIELDA_004 { get; set; }
        public string FSC_FIELDA_005 { get; set; }
        public string FSC_FIELDA_006 { get; set; }
        public string FSC_FIELDA_007 { get; set; }
        public string FSC_FIELDA_008 { get; set; }
        public string FSC_FIELDA_009 { get; set; }
        public string FSC_FIELDA_010 { get; set; }
        public string FSC_FIELDA_011 { get; set; }
        public string FSC_FIELDA_012 { get; set; }
        public string FSC_FIELDA_013 { get; set; }
        public string FSC_FIELDA_014 { get; set; }
        public string FSC_FIELDA_015 { get; set; }
        public string FSC_FIELDA_016 { get; set; }
        public string FSC_FIELDA_017 { get; set; }
        public string FSC_FIELDA_018 { get; set; }
        public string FSC_FIELDA_019 { get; set; }
        public string FSC_FIELDA_020 { get; set; }
        public string FSC_FIELDB_001 { get; set; }
        public string FSC_FIELDB_002 { get; set; }
        public string FSC_FIELDB_003 { get; set; }
        public string FSC_FIELDB_004 { get; set; }
        public string FSC_FIELDB_005 { get; set; }
        public string FSC_FIELDB_006 { get; set; }
        public string FSC_FIELDB_007 { get; set; }
        public string FSC_FIELDB_008 { get; set; }
        public string FSC_FIELDB_009 { get; set; }
        public string FSC_FIELDB_010 { get; set; }
        public string FSC_FIELDB_011 { get; set; }
        public string FSC_FIELDB_012 { get; set; }
        public string FSC_FIELDB_013 { get; set; }
        public string FSC_FIELDB_014 { get; set; }
        public string FSC_FIELDB_015 { get; set; }
        public string FSC_FIELDB_016 { get; set; }
        public string FSC_FIELDB_017 { get; set; }
        public string FSC_FIELDB_018 { get; set; }
        public string FSC_FIELDB_019 { get; set; }
        public string FSC_FIELDB_020 { get; set; }
        public string FSC_FIELDC_001 { get; set; }
        public string FSC_FIELDC_002 { get; set; }
        public string FSC_FIELDC_003 { get; set; }
        public string FSC_FIELDC_004 { get; set; }
        public string FSC_FIELDC_005 { get; set; }
        public string FSC_FIELDC_006 { get; set; }
        public string FSC_FIELDC_007 { get; set; }
        public string FSC_FIELDC_008 { get; set; }
        public string FSC_FIELDC_009 { get; set; }
        public string FSC_FIELDC_010 { get; set; }
        public Nullable<decimal> FSC_LAST_MODIFIED { get; set; }
    }
}
