//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEBOOK_STUDENT_SUBMISSION
    {
        public string GSS_OID { get; set; }
        public string GSS_GCD_OID { get; set; }
        public string GSS_STD_OID { get; set; }
        public Nullable<decimal> GSS_TIME_SUBMITTED { get; set; }
        public byte[] GSS_FILE { get; set; }
        public Nullable<decimal> GSS_FILE_SIZE { get; set; }
        public string GSS_EXTENSION { get; set; }
        public Nullable<decimal> GSS_LAST_MODIFIED { get; set; }
        public string GSS_ASSIGNMENT_STATUS { get; set; }
        public string GSS_ARI_OID { get; set; }
    }
}
