//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_TERM
    {
        public string GTM_OID { get; set; }
        public string GTM_GTF_OID { get; set; }
        public Nullable<decimal> GTM_GRADE_TERM_NUM { get; set; }
        public string GTM_GRADE_TERM_ID { get; set; }
        public Nullable<decimal> GTM_LAST_MODIFIED { get; set; }
    }
}
