//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_TRANS_COLUMN_DEFINITION
    {
        public string GTC_OID { get; set; }
        public string GTC_GTD_OID { get; set; }
        public string GTC_GTM_OID { get; set; }
        public string GTC_GRS_OID { get; set; }
        public string GTC_RTB_OID { get; set; }
        public string GTC_FDD_OID { get; set; }
        public string GTC_GRADE_NAME { get; set; }
        public string GTC_GRADE_COLUMN_HEADER { get; set; }
        public Nullable<decimal> GTC_SEQUENCE_NUMBER { get; set; }
        public Nullable<decimal> GTC_COMMENT_LENGTH { get; set; }
        public Nullable<decimal> GTC_REPORT_TYPE { get; set; }
        public Nullable<decimal> GTC_COLUMN_TYPE { get; set; }
        public Nullable<decimal> GTC_COLLECTION_TYPE { get; set; }
        public string GTC_CALCULATION { get; set; }
        public string GTC_COLUMN_ID { get; set; }
        public string GTC_COLUMN_ALIGNMENT_ID { get; set; }
        public string GTC_GRADEBOOK_AVERAGE_IND { get; set; }
        public string GTC_UPDATE_CREDITS_IND { get; set; }
        public string GTC_AUTO_RECALC_IND { get; set; }
        public Nullable<decimal> GTC_ENTRY_MODE { get; set; }
        public string GTC_FIELDA_001 { get; set; }
        public string GTC_FIELDA_002 { get; set; }
        public string GTC_FIELDA_003 { get; set; }
        public Nullable<decimal> GTC_LAST_MODIFIED { get; set; }
        public string GTC_CBT_OID { get; set; }
        public Nullable<decimal> GTC_AUDIT_TYPE { get; set; }
    }
}
