//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEBOOK_SPECIAL_CODE
    {
        public string GCO_OID { get; set; }
        public string GCO_STF_OID { get; set; }
        public string GCO_CODE { get; set; }
        public string GCO_SHORTCUT { get; set; }
        public Nullable<decimal> GCO_BEHAVIOR { get; set; }
        public string GCO_COLOR { get; set; }
        public string GCO_MISSING_IND { get; set; }
        public Nullable<decimal> GCO_LAST_MODIFIED { get; set; }
    }
}
