//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_PAGE_LOG
    {
        public string GPL_OID { get; set; }
        public string GPL_GRP_OID { get; set; }
        public string GPL_USR_OID { get; set; }
        public Nullable<System.DateTime> GPL_DATE { get; set; }
        public Nullable<System.DateTime> GPL_TIME { get; set; }
        public Nullable<decimal> GPL_LAST_MODIFIED { get; set; }
    }
}
