//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_MEMBER
    {
        public string GMB_OID { get; set; }
        public string GMB_GRP_OID { get; set; }
        public Nullable<decimal> GMB_TYPE { get; set; }
        public string GMB_OBJ_OID { get; set; }
        public string GMB_MEMBER_VIEW { get; set; }
        public Nullable<decimal> GMB_LAST_MODIFIED { get; set; }
        public string GMB_FIELDA_001 { get; set; }
        public string GMB_FIELDA_002 { get; set; }
        public string GMB_FIELDA_003 { get; set; }
        public string GMB_FIELDA_004 { get; set; }
        public string GMB_FIELDA_005 { get; set; }
        public string GMB_FIELDA_006 { get; set; }
        public string GMB_FIELDA_007 { get; set; }
        public string GMB_FIELDA_008 { get; set; }
        public string GMB_FIELDA_009 { get; set; }
        public string GMB_FIELDA_010 { get; set; }
        public Nullable<decimal> GMB_MANAGEMENT_TYPE { get; set; }
    }
}
