//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_SET
    {
        public string GRZ_OID { get; set; }
        public Nullable<decimal> GRZ_CONTEXT_TYPE { get; set; }
        public string GRZ_OBJ_CONTEXT_OID { get; set; }
        public string GRZ_NAME { get; set; }
        public Nullable<decimal> GRZ_LAST_MODIFIED { get; set; }
    }
}
