//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_PAGE_BANNER
    {
        public string GPB_OID { get; set; }
        public string GPB_USR_OID { get; set; }
        public string GPB_GPW_OID { get; set; }
        public string GPB_CONTENT { get; set; }
        public Nullable<decimal> GPB_LAST_MODIFIED { get; set; }
    }
}
