//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEALTH_INVENTORY_TRANSACTION
    {
        public string HIT_OID { get; set; }
        public string HIT_HJB_OID { get; set; }
        public string HIT_HMO_OID { get; set; }
        public Nullable<decimal> HIT_TRANSACTION_TYPE { get; set; }
        public Nullable<decimal> HIT_AMOUNT { get; set; }
        public Nullable<decimal> HIT_NEW_BALANCE { get; set; }
        public Nullable<System.DateTime> HIT_DATE { get; set; }
        public Nullable<System.DateTime> HIT_TIME { get; set; }
        public string HIT_COMMENT { get; set; }
        public string HIT_FIELDA_001 { get; set; }
        public string HIT_FIELDA_002 { get; set; }
        public string HIT_FIELDA_003 { get; set; }
        public string HIT_FIELDB_001 { get; set; }
        public string HIT_FIELDB_002 { get; set; }
        public string HIT_FIELDC_001 { get; set; }
        public string HIT_FIELDD_001 { get; set; }
        public string HIT_FIELDD_002 { get; set; }
        public string HIT_FIELDD_003 { get; set; }
        public string HIT_FIELDD_004 { get; set; }
        public string HIT_FIELDD_005 { get; set; }
        public Nullable<decimal> HIT_TIMESTAMP { get; set; }
        public Nullable<decimal> HIT_LAST_MODIFIED { get; set; }
    }
}
