//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEALTH_LOG_ACTION
    {
        public string HLA_OID { get; set; }
        public string HLA_HLG_OID { get; set; }
        public string HLA_ACTION_CODE { get; set; }
        public string HLA_COMMENT { get; set; }
        public string HLA_PRIMARY_IND { get; set; }
        public string HLA_FIELDA_001 { get; set; }
        public string HLA_FIELDA_002 { get; set; }
        public string HLA_FIELDA_003 { get; set; }
        public string HLA_FIELDA_004 { get; set; }
        public string HLA_FIELDA_005 { get; set; }
        public string HLA_FIELDB_001 { get; set; }
        public string HLA_FIELDB_002 { get; set; }
        public string HLA_FIELDB_003 { get; set; }
        public string HLA_FIELDB_004 { get; set; }
        public string HLA_FIELDB_005 { get; set; }
        public string HLA_FIELDC_001 { get; set; }
        public string HLA_FIELDC_002 { get; set; }
        public string HLA_FIELDC_003 { get; set; }
        public string HLA_FIELDC_004 { get; set; }
        public string HLA_FIELDC_005 { get; set; }
        public string HLA_FIELDD_001 { get; set; }
        public Nullable<decimal> HLA_LAST_MODIFIED { get; set; }
    }
}
