//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_OTHER_SERVICE
    {
        public string IOS_OID { get; set; }
        public string IOS_STD_OID { get; set; }
        public string IOS_IEP_OID { get; set; }
        public string IOS_DDX_OID { get; set; }
        public string IOS_SERVICE_TYPE { get; set; }
        public Nullable<System.DateTime> IOS_START_DATE { get; set; }
        public Nullable<System.DateTime> IOS_END_DATE { get; set; }
        public string IOS_FIELDA_001 { get; set; }
        public string IOS_FIELDA_002 { get; set; }
        public string IOS_FIELDA_003 { get; set; }
        public string IOS_FIELDA_004 { get; set; }
        public string IOS_FIELDA_005 { get; set; }
        public string IOS_FIELDA_006 { get; set; }
        public string IOS_FIELDA_007 { get; set; }
        public string IOS_FIELDA_008 { get; set; }
        public string IOS_FIELDA_009 { get; set; }
        public string IOS_FIELDA_010 { get; set; }
        public string IOS_FIELDB_001 { get; set; }
        public string IOS_FIELDB_002 { get; set; }
        public string IOS_FIELDB_003 { get; set; }
        public string IOS_FIELDB_004 { get; set; }
        public string IOS_FIELDB_005 { get; set; }
        public string IOS_FIELDB_006 { get; set; }
        public string IOS_FIELDB_007 { get; set; }
        public string IOS_FIELDB_008 { get; set; }
        public string IOS_FIELDB_009 { get; set; }
        public string IOS_FIELDB_010 { get; set; }
        public string IOS_FIELDC_001 { get; set; }
        public string IOS_FIELDC_002 { get; set; }
        public string IOS_FIELDC_003 { get; set; }
        public string IOS_FIELDC_004 { get; set; }
        public string IOS_FIELDC_005 { get; set; }
        public string IOS_FIELDD_001 { get; set; }
        public string IOS_FIELDD_002 { get; set; }
        public Nullable<decimal> IOS_LAST_MODIFIED { get; set; }
    }
}
