//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_PLACEMENT
    {
        public string IPA_OID { get; set; }
        public string IPA_IPP_OID { get; set; }
        public string IPA_IEP_OID { get; set; }
        public Nullable<System.DateTime> IPA_START_DATE { get; set; }
        public Nullable<System.DateTime> IPA_SIGNED_DATE { get; set; }
        public Nullable<decimal> IPA_STATUS { get; set; }
        public string IPA_FIELDA_001 { get; set; }
        public string IPA_FIELDA_002 { get; set; }
        public string IPA_FIELDA_003 { get; set; }
        public string IPA_FIELDA_004 { get; set; }
        public string IPA_FIELDA_005 { get; set; }
        public string IPA_FIELDA_006 { get; set; }
        public string IPA_FIELDA_007 { get; set; }
        public string IPA_FIELDA_008 { get; set; }
        public string IPA_FIELDA_009 { get; set; }
        public string IPA_FIELDA_010 { get; set; }
        public string IPA_FIELDA_011 { get; set; }
        public string IPA_FIELDA_012 { get; set; }
        public string IPA_FIELDA_013 { get; set; }
        public string IPA_FIELDA_014 { get; set; }
        public string IPA_FIELDA_015 { get; set; }
        public string IPA_FIELDA_016 { get; set; }
        public string IPA_FIELDA_017 { get; set; }
        public string IPA_FIELDA_018 { get; set; }
        public string IPA_FIELDA_019 { get; set; }
        public string IPA_FIELDA_020 { get; set; }
        public string IPA_FIELDB_001 { get; set; }
        public string IPA_FIELDB_002 { get; set; }
        public string IPA_FIELDB_003 { get; set; }
        public string IPA_FIELDB_004 { get; set; }
        public string IPA_FIELDB_005 { get; set; }
        public string IPA_FIELDB_006 { get; set; }
        public string IPA_FIELDB_007 { get; set; }
        public string IPA_FIELDB_008 { get; set; }
        public string IPA_FIELDB_009 { get; set; }
        public string IPA_FIELDB_010 { get; set; }
        public string IPA_FIELDC_001 { get; set; }
        public string IPA_FIELDC_002 { get; set; }
        public string IPA_FIELDC_003 { get; set; }
        public string IPA_FIELDC_004 { get; set; }
        public string IPA_FIELDC_005 { get; set; }
        public string IPA_FIELDC_006 { get; set; }
        public string IPA_FIELDD_001 { get; set; }
        public string IPA_FIELDD_002 { get; set; }
        public string IPA_FIELDD_003 { get; set; }
        public Nullable<decimal> IPA_LAST_MODIFIED { get; set; }
    }
}
