//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_AMENDMENT_DETAIL
    {
        public string IAD_OID { get; set; }
        public string IAD_IAM_OID { get; set; }
        public string IAD_TYPE { get; set; }
        public string IAD_DESCRIPTION { get; set; }
        public string IAD_REASON { get; set; }
        public Nullable<decimal> IAD_SEQUENCE_NUMBER { get; set; }
        public string IAD_FIELDA_001 { get; set; }
        public string IAD_FIELDA_002 { get; set; }
        public string IAD_FIELDA_003 { get; set; }
        public string IAD_FIELDA_004 { get; set; }
        public string IAD_FIELDA_005 { get; set; }
        public string IAD_FIELDB_001 { get; set; }
        public string IAD_FIELDB_002 { get; set; }
        public string IAD_FIELDB_003 { get; set; }
        public string IAD_FIELDB_004 { get; set; }
        public string IAD_FIELDB_005 { get; set; }
        public string IAD_FIELDC_001 { get; set; }
        public string IAD_FIELDC_002 { get; set; }
        public string IAD_FIELDC_003 { get; set; }
        public string IAD_FIELDD_001 { get; set; }
        public string IAD_FIELDD_002 { get; set; }
        public Nullable<decimal> IAD_LAST_MODIFIED { get; set; }
    }
}
