//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PD_ACTIVITY_SECTION
    {
        public string PDS_OID { get; set; }
        public string PDS_PDC_OID { get; set; }
        public string PDS_STF_OID { get; set; }
        public Nullable<decimal> PDS_SECTION_NUMBER { get; set; }
        public Nullable<System.DateTime> PDS_START_DATE { get; set; }
        public Nullable<System.DateTime> PDS_END_DATE { get; set; }
        public string PDS_INSTRUCTOR { get; set; }
        public string PDS_MEETING_TIME_VIEW { get; set; }
        public string PDS_LOCATION_VIEW { get; set; }
        public Nullable<decimal> PDS_ENROLLMENT_MAX { get; set; }
        public Nullable<decimal> PDS_ENROLLMENT_TOTAL { get; set; }
        public Nullable<decimal> PDS_ENROLLMENT_TYPE { get; set; }
        public Nullable<System.DateTime> PDS_ENROLLMENT_OPEN_DATE { get; set; }
        public Nullable<System.DateTime> PDS_ENROLLMENT_CLOSE_DATE { get; set; }
        public string PDS_FIELDA_001 { get; set; }
        public string PDS_FIELDA_002 { get; set; }
        public string PDS_FIELDA_003 { get; set; }
        public string PDS_FIELDA_004 { get; set; }
        public string PDS_FIELDA_005 { get; set; }
        public string PDS_FIELDB_001 { get; set; }
        public string PDS_FIELDB_002 { get; set; }
        public string PDS_FIELDB_003 { get; set; }
        public string PDS_FIELDC_001 { get; set; }
        public string PDS_FIELDC_002 { get; set; }
        public string PDS_FIELDD_001 { get; set; }
        public Nullable<decimal> PDS_LAST_MODIFIED { get; set; }
    }
}
