//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_APPOINTMENT
    {
        public string APT_OID { get; set; }
        public string APT_PSN_OID_OWNER { get; set; }
        public string APT_PSN_OID_APPOINTMENT { get; set; }
        public Nullable<System.DateTime> APT_DATE { get; set; }
        public Nullable<System.DateTime> APT_START_TIME { get; set; }
        public Nullable<System.DateTime> APT_END_TIME { get; set; }
        public string APT_BOOKED_IND { get; set; }
        public string APT_COMMENT { get; set; }
        public string APT_SUMMARY_VIEW { get; set; }
        public string APT_TYPE { get; set; }
        public string APT_FIELDA_001 { get; set; }
        public string APT_FIELDA_002 { get; set; }
        public string APT_FIELDA_003 { get; set; }
        public string APT_FIELDA_004 { get; set; }
        public string APT_FIELDA_005 { get; set; }
        public string APT_FIELDA_006 { get; set; }
        public string APT_FIELDA_007 { get; set; }
        public string APT_FIELDA_008 { get; set; }
        public string APT_FIELDA_009 { get; set; }
        public string APT_FIELDA_010 { get; set; }
        public string APT_FIELDB_001 { get; set; }
        public string APT_FIELDB_002 { get; set; }
        public string APT_FIELDB_003 { get; set; }
        public string APT_FIELDB_004 { get; set; }
        public string APT_FIELDB_005 { get; set; }
        public string APT_FIELDB_006 { get; set; }
        public string APT_FIELDB_007 { get; set; }
        public string APT_FIELDB_008 { get; set; }
        public string APT_FIELDB_009 { get; set; }
        public string APT_FIELDB_010 { get; set; }
        public string APT_FIELDC_001 { get; set; }
        public string APT_FIELDC_002 { get; set; }
        public string APT_FIELDC_003 { get; set; }
        public string APT_FIELDC_004 { get; set; }
        public string APT_FIELDC_005 { get; set; }
        public string APT_FIELDD_001 { get; set; }
        public string APT_FIELDD_002 { get; set; }
        public string APT_FIELDD_003 { get; set; }
        public string APT_FIELDD_004 { get; set; }
        public string APT_FIELDD_005 { get; set; }
        public byte[] APT_FIELDE_001 { get; set; }
        public Nullable<decimal> APT_LAST_MODIFIED { get; set; }
    }
}
