//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTAL_LINK
    {
        public string PTL_OID { get; set; }
        public string PTL_OWNER_OID { get; set; }
        public Nullable<decimal> PTL_OWNER_TYPE { get; set; }
        public Nullable<decimal> PTL_SEQUENCE_NUMBER { get; set; }
        public string PTL_NAME { get; set; }
        public string PTL_DESCRIPTION { get; set; }
        public string PTL_CATEGORY { get; set; }
        public string PTL_LINK { get; set; }
        public Nullable<decimal> PTL_LAST_MODIFIED { get; set; }
    }
}
