//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTAL_NOTICE
    {
        public string PTN_OID { get; set; }
        public Nullable<decimal> PTN_SEQUENCE_NUMBER { get; set; }
        public Nullable<System.DateTime> PTN_START_DATE { get; set; }
        public Nullable<System.DateTime> PTN_END_DATE { get; set; }
        public string PTN_CONTENT { get; set; }
        public Nullable<decimal> PTN_VIEW_VISIBILITY { get; set; }
        public Nullable<decimal> PTN_LAST_MODIFIED { get; set; }
    }
}
