//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION_SET_QUESTION
    {
        public string QSR_OID { get; set; }
        public string QSR_QSD_OID { get; set; }
        public string QSR_QUESTION { get; set; }
        public string QSR_REQUIRED { get; set; }
        public string QSR_TYPE { get; set; }
        public Nullable<decimal> QSR_SEQ_NO { get; set; }
        public Nullable<decimal> QSR_POINT_VALUE { get; set; }
        public Nullable<decimal> QSR_LAST_MODIFIED { get; set; }
        public string QSR_ANSWER { get; set; }
        public string QSR_QSR_OID { get; set; }
        public string QSR_OWNER_OID { get; set; }
        public Nullable<decimal> QSR_OWNER_TYPE { get; set; }
        public string QSR_GRADE_LEVEL { get; set; }
        public string QSR_SUBJECT { get; set; }
        public string QSR_EXCLUDE_FROM_ITEM_BANK { get; set; }
        public string QSR_LOCKED { get; set; }
        public string QSR_USE_TYPE { get; set; }
        public Nullable<decimal> QSR_TIME_LIMIT { get; set; }
        public Nullable<decimal> QSR_PERCENT_CORRECT { get; set; }
        public Nullable<decimal> QSR_AVERAGE_TIME { get; set; }
        public Nullable<decimal> QSR_CORRECT_COUNT { get; set; }
        public Nullable<decimal> QSR_RATING { get; set; }
        public Nullable<decimal> QSR_ATTEMPTS { get; set; }
        public string QSR_DIFFICULTY_LEVEL { get; set; }
    }
}
