//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECORD_SET
    {
        public string RSN_OID { get; set; }
        public string RSN_TBL_OID { get; set; }
        public string RSN_OWNER_OID { get; set; }
        public Nullable<decimal> RSN_OWNER_TYPE { get; set; }
        public string RSN_NAME { get; set; }
        public string RSN_CATEGORY { get; set; }
        public Nullable<decimal> RSN_LAST_MODIFIED { get; set; }
    }
}
