//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_CODE_REQUIRED_FIELD
    {
        public string RCR_OID { get; set; }
        public string RCR_RCD_OID { get; set; }
        public string RCR_FDD_OID { get; set; }
        public string RCR_REQUIRED_FIELD { get; set; }
        public string RCR_FIELDA_001 { get; set; }
        public string RCR_FIELDA_002 { get; set; }
        public string RCR_FIELDA_003 { get; set; }
        public string RCR_FIELDA_004 { get; set; }
        public string RCR_FIELDA_005 { get; set; }
        public string RCR_FIELDA_006 { get; set; }
        public string RCR_FIELDA_007 { get; set; }
        public string RCR_FIELDA_008 { get; set; }
        public string RCR_FIELDA_009 { get; set; }
        public string RCR_FIELDA_010 { get; set; }
        public string RCR_FIELDB_001 { get; set; }
        public string RCR_FIELDB_002 { get; set; }
        public string RCR_FIELDB_003 { get; set; }
        public string RCR_FIELDB_004 { get; set; }
        public string RCR_FIELDB_005 { get; set; }
        public string RCR_FIELDC_001 { get; set; }
        public string RCR_FIELDC_002 { get; set; }
        public string RCR_FIELDC_003 { get; set; }
        public string RCR_FIELDC_004 { get; set; }
        public string RCR_FIELDC_005 { get; set; }
        public Nullable<decimal> RCR_LAST_MODIFIED { get; set; }
    }
}
