//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_QAN_CODE
    {
        public string QAN_OID { get; set; }
        public string QAN_CODE { get; set; }
        public string QAN_DISCOUNT_CODE { get; set; }
        public string QAN_AB_IDENTIFIER { get; set; }
        public string QAN_QUALIFICATION_TYPE { get; set; }
        public string QAN_QUALIFICATION_TITLE { get; set; }
        public string QAN_QUALIFICATION_SHORT_TITLE { get; set; }
        public string QAN_SSFT_1 { get; set; }
        public string QAN_SSFT_2 { get; set; }
        public string QAN_NQF { get; set; }
        public string QAN_MAP { get; set; }
        public string QAN_DISABLED_IND { get; set; }
        public string QAN_FIELDA_001 { get; set; }
        public string QAN_FIELDA_002 { get; set; }
        public string QAN_FIELDA_003 { get; set; }
        public string QAN_FIELDA_004 { get; set; }
        public string QAN_FIELDA_005 { get; set; }
        public string QAN_FIELDB_001 { get; set; }
        public string QAN_FIELDB_002 { get; set; }
        public string QAN_FIELDB_003 { get; set; }
        public Nullable<decimal> QAN_LAST_MODIFIED { get; set; }
    }
}
