//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public string RPT_OID { get; set; }
        public string RPT_ORG_OID_1 { get; set; }
        public string RPT_ORG_OID_2 { get; set; }
        public string RPT_ORG_OID_3 { get; set; }
        public string RPT_ORG_OID_4 { get; set; }
        public string RPT_ORG_OID_5 { get; set; }
        public string RPT_PRC_OID { get; set; }
        public string RPT_DDX_OID { get; set; }
        public string RPT_REPORT_ID { get; set; }
        public string RPT_NAME { get; set; }
        public string RPT_CATEGORY { get; set; }
        public string RPT_MENU_GROUP { get; set; }
        public Nullable<decimal> RPT_SEQUENCE_NUMBER { get; set; }
        public string RPT_JAVA_SOURCE { get; set; }
        public byte[] RPT_JAVA_SOURCE_COMPILED { get; set; }
        public string RPT_REPORT_INPUT { get; set; }
        public string RPT_FORMAT { get; set; }
        public byte[] RPT_FORMAT_COMPILED { get; set; }
        public Nullable<decimal> RPT_SCHOOL_VISIBILITY_TYPE { get; set; }
        public Nullable<decimal> RPT_ROLE_VISIBILITY_TYPE { get; set; }
        public string RPT_CUSTOM_JAVA_SOURCE_IND { get; set; }
        public string RPT_CUSTOM_INPUT_IND { get; set; }
        public string RPT_CUSTOM_FORMAT_IND { get; set; }
        public Nullable<decimal> RPT_WEIGHT { get; set; }
        public string RPT_CUSTOM_HREF { get; set; }
        public string RPT_DISABLED_IND { get; set; }
        public string RPT_ENGINE_VERSION { get; set; }
        public string RPT_COMMENT { get; set; }
        public string RPT_SCHEDULE { get; set; }
        public string RPT_DISABLE_AUTO_KILL { get; set; }
        public string RPT_PUBLISHABLE_IND { get; set; }
        public string RPT_DEFAULT_PUBLISHED_MESSAGE { get; set; }
        public string RPT_DEFAULT_PUBLISHED_SUBJECT { get; set; }
        public Nullable<decimal> RPT_LAST_MODIFIED { get; set; }
    }
}
