//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRIC_RATING_SCALE_POINTS
    {
        public string RRP_OID { get; set; }
        public string RRP_RRS_OID { get; set; }
        public Nullable<decimal> RRP_SEQUENCE_NUMBER { get; set; }
        public string RRP_RATING_ID { get; set; }
        public string RRP_NAME { get; set; }
        public string RRP_DESCRIPTION { get; set; }
        public Nullable<decimal> RRP_POINTS { get; set; }
        public Nullable<decimal> RRP_CUTOFF { get; set; }
        public string RRP_MASTERY_IND { get; set; }
        public Nullable<decimal> RRP_LAST_MODIFIED { get; set; }
    }
}
