//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRIC_DEFINITION
    {
        public string RBD_OID { get; set; }
        public string RBD_ORG_OID_1 { get; set; }
        public string RBD_ORG_OID_2 { get; set; }
        public string RBD_ORG_OID_3 { get; set; }
        public string RBD_ORG_OID_4 { get; set; }
        public string RBD_ORG_OID_5 { get; set; }
        public string RBD_RRS_OID { get; set; }
        public string RBD_OWNER_OID { get; set; }
        public Nullable<decimal> RBD_OWNER_TYPE { get; set; }
        public string RBD_RUBRIC_ID { get; set; }
        public string RBD_NAME { get; set; }
        public string RBD_REPORT_DISPLAY { get; set; }
        public string RBD_DESCRIPTION { get; set; }
        public string RBD_SUBJECT_CODE { get; set; }
        public string RBD_SOURCE { get; set; }
        public string RBD_GRADE_LEVEL_RANGE_VIEW { get; set; }
        public string RBD_COMMENT { get; set; }
        public string RBD_DEFINITION { get; set; }
        public Nullable<decimal> RBD_LEVEL_COUNT { get; set; }
        public Nullable<decimal> RBD_CRITERIA_COUNT { get; set; }
        public Nullable<decimal> RBD_MAX_POINTS { get; set; }
        public Nullable<decimal> RBD_SCORE_DECIMALS { get; set; }
        public string RBD_LOCKED_IND { get; set; }
        public string RBD_SHOW_CALCULATED_IND { get; set; }
        public string RBD_CALCULATION_OVERRIDE_IND { get; set; }
        public string RBD_TERM_RESTRICTIONS_IND { get; set; }
        public Nullable<decimal> RBD_NUMBER_OF_TERMS { get; set; }
        public string RBD_DESCRIPTION_LOCALE_1 { get; set; }
        public string RBD_DESCRIPTION_LOCALE_2 { get; set; }
        public string RBD_DESCRIPTION_LOCALE_3 { get; set; }
        public string RBD_DESCRIPTION_LOCALE_4 { get; set; }
        public string RBD_DESCRIPTION_LOCALE_5 { get; set; }
        public string RBD_FIELDA_001 { get; set; }
        public string RBD_FIELDA_002 { get; set; }
        public string RBD_FIELDA_003 { get; set; }
        public string RBD_FIELDB_001 { get; set; }
        public string RBD_FIELDB_002 { get; set; }
        public Nullable<decimal> RBD_LAST_MODIFIED { get; set; }
    }
}
