//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_PATTERN_LIBRARY
    {
        public string SPL_OID { get; set; }
        public string SPL_SKL_OID { get; set; }
        public string SPL_SPS_OID { get; set; }
        public Nullable<decimal> SPL_DAYS { get; set; }
        public Nullable<decimal> SPL_PERIODS { get; set; }
        public string SPL_SCHEDULE_PATTERN_TYPE { get; set; }
        public Nullable<decimal> SPL_BASE_TERMS_PER_YEAR { get; set; }
        public Nullable<decimal> SPL_COVERED_TERMS_PER_YEAR { get; set; }
        public string SPL_TERMS_PER_YEAR_VIEW { get; set; }
        public Nullable<decimal> SPL_PERIODS_PER_CYCLE { get; set; }
        public string SPL_TERM_MAP { get; set; }
        public string SPL_SCHEDULE_MATRIX { get; set; }
        public string SPL_PATTERN_VIEW { get; set; }
        public string SPL_HIDE_IND { get; set; }
        public Nullable<decimal> SPL_LAST_MODIFIED { get; set; }
        public Nullable<decimal> SPL_SCHEDULE_PATTERN_STYLE { get; set; }
    }
}
