//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_RULE_OBJECT_DEF
    {
        public string SOD_OID { get; set; }
        public string SOD_SRD_OID { get; set; }
        public string SOD_TBL_OID { get; set; }
        public string SOD_OBJECT_ID { get; set; }
        public string SOD_SUMMARY_MASK { get; set; }
        public string SOD_REQUIRED_IND { get; set; }
        public Nullable<decimal> SOD_LAST_MODIFIED { get; set; }
    }
}
