//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_BUILD_MASTER
    {
        public string BLM_OID { get; set; }
        public string BLM_SCH_OID { get; set; }
        public string BLM_CSK_OID { get; set; }
        public string BLM_TRM_OID { get; set; }
        public string BLM_BLC_OID { get; set; }
        public string BLM_STF_OID_PRIMARY { get; set; }
        public string BLM_RMS_OID_PRIMARY { get; set; }
        public string BLM_SECTION_NUMBER { get; set; }
        public string BLM_TEAM_CODE { get; set; }
        public string BLM_HOUSE_CODE { get; set; }
        public string BLM_PLATOON_CODE { get; set; }
        public Nullable<decimal> BLM_ROOM_STATUS { get; set; }
        public string BLM_ROT_OID { get; set; }
        public string BLM_SECTION_TYPE_CODE { get; set; }
        public string BLM_INCLUSION_IND { get; set; }
        public Nullable<decimal> BLM_TEAM_SCHEDULE_MODE { get; set; }
        public Nullable<decimal> BLM_HOUSE_SCHEDULE_MODE { get; set; }
        public Nullable<decimal> BLM_SECTION_TYPE_SCHEDULE_MODE { get; set; }
        public Nullable<decimal> BLM_PLATOON_SCHEDULE_MODE { get; set; }
        public string BLM_SYSTEM_PLATOON_IND { get; set; }
        public string BLM_CONTENT_TERM_CODES { get; set; }
        public Nullable<decimal> BLM_ENROLLMENT_TOTAL { get; set; }
        public Nullable<decimal> BLM_ENROLLMENT_WEIGHT_TOTAL { get; set; }
        public Nullable<decimal> BLM_ENROLLMENT_MAX { get; set; }
        public string BLM_ENROLLMENT_MAX_CLOSE_IND { get; set; }
        public string BLM_ENROLLMENT_DETAIL_COUNTS { get; set; }
        public string BLM_STUDY_CRITERIA { get; set; }
        public string BLM_SECTION_LOCK_IND { get; set; }
        public string BLM_PRESCHEDULED_TERM_IND { get; set; }
        public string BLM_PRESCHEDULED_SCHEDULE_IND { get; set; }
        public string BLM_PRESCHEDULED_ROOM_IND { get; set; }
        public string BLM_BUILD_EXCLUDE_IND { get; set; }
        public string BLM_COURSE_VIEW { get; set; }
        public string BLM_STAFF_VIEW { get; set; }
        public string BLM_ROOM_VIEW { get; set; }
        public string BLM_TERM_VIEW { get; set; }
        public string BLM_SCHEDULE_DISPLAY { get; set; }
        public string BLM_UNROTATED_SCHEDULE_DISPLAY { get; set; }
        public string BLM_SCHEDULE_TRACK_ID { get; set; }
        public string BLM_DESCRIPTION { get; set; }
        public string BLM_TERM_MAP { get; set; }
        public string BLM_SCHEDULE_MATRIX { get; set; }
        public Nullable<decimal> BLM_SYSTEM_RANK { get; set; }
        public Nullable<decimal> BLM_USER_RANK_ADJUSTMENT { get; set; }
        public string BLM_ELEMENTARY_IND { get; set; }
        public string BLM_FIELDA_001 { get; set; }
        public string BLM_FIELDA_002 { get; set; }
        public string BLM_FIELDA_003 { get; set; }
        public string BLM_FIELDB_001 { get; set; }
        public string BLM_FIELDB_002 { get; set; }
        public Nullable<decimal> BLM_LAST_MODIFIED { get; set; }
        public string BLM_SPLIT_TEACHER_IND { get; set; }
        public string BLM_SPLIT_ROOM_IND { get; set; }
        public string BLM_DYN_ASSIGN_TEACHER_IND { get; set; }
        public string BLM_SPLIT_STAFF_OPTIONS { get; set; }
        public Nullable<decimal> BLM_SPLIT_RESOURCE_MODE { get; set; }
    }
}
