//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHOOL_ROOM
    {
        public string RMS_OID { get; set; }
        public string RMS_SKL_OID { get; set; }
        public string RMS_ROOM_NUMBER { get; set; }
        public string RMS_DEPARTMENT_CODE { get; set; }
        public string RMS_TYPE { get; set; }
        public string RMS_BUILDING_CODE { get; set; }
        public Nullable<decimal> RMS_MAX_CAPACITY { get; set; }
        public string RMS_SCHD_INCLUDE_IND { get; set; }
        public Nullable<decimal> RMS_SCHD_USE_TYPE { get; set; }
        public string RMS_LOCATION_CODE { get; set; }
        public string RMS_FIELDA_001 { get; set; }
        public string RMS_FIELDA_002 { get; set; }
        public string RMS_FIELDA_003 { get; set; }
        public string RMS_FIELDA_004 { get; set; }
        public string RMS_FIELDA_005 { get; set; }
        public string RMS_FIELDA_006 { get; set; }
        public string RMS_FIELDA_007 { get; set; }
        public string RMS_FIELDA_008 { get; set; }
        public string RMS_FIELDA_009 { get; set; }
        public string RMS_FIELDA_010 { get; set; }
        public string RMS_FIELDB_001 { get; set; }
        public string RMS_FIELDB_002 { get; set; }
        public string RMS_FIELDB_003 { get; set; }
        public string RMS_FIELDB_004 { get; set; }
        public string RMS_FIELDB_005 { get; set; }
        public string RMS_FIELDC_001 { get; set; }
        public string RMS_FIELDC_002 { get; set; }
        public Nullable<decimal> RMS_LAST_MODIFIED { get; set; }
        public string RMS_EXAM_INCLUDE_IND { get; set; }
    }
}
