//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHOOL
    {
        public string SKL_OID { get; set; }
        public string SKL_ORG_OID_1 { get; set; }
        public string SKL_ORG_OID_2 { get; set; }
        public string SKL_ORG_OID_3 { get; set; }
        public string SKL_ORG_OID_4 { get; set; }
        public string SKL_ORG_OID_5 { get; set; }
        public string SKL_CTX_OID_BUILD { get; set; }
        public string SKL_SKX_OID_ACTIV { get; set; }
        public string SKL_ADR_OID { get; set; }
        public string SKL_STF_OID_ADMIN1 { get; set; }
        public string SKL_STF_OID_ADMIN2 { get; set; }
        public string SKL_STF_OID_ADMIN3 { get; set; }
        public string SKL_STF_OID_ADMIN4 { get; set; }
        public string SKL_STF_OID_ADMIN5 { get; set; }
        public string SKL_SCHOOL_ID { get; set; }
        public string SKL_SCHOOL_NAME { get; set; }
        public string SKL_SCHOOL_TYPE_CODE { get; set; }
        public string SKL_SCHOOL_LEVEL_CODE { get; set; }
        public string SKL_INACTIVE_IND { get; set; }
        public string SKL_ARCHIVE_IND { get; set; }
        public Nullable<decimal> SKL_START_GRADE { get; set; }
        public Nullable<decimal> SKL_NUMBER_OF_GRADES { get; set; }
        public string SKL_GTD_OID_DEFAULT { get; set; }
        public string SKL_AD_OU_NAME { get; set; }
        public string SKL_FIELDA_001 { get; set; }
        public string SKL_FIELDA_002 { get; set; }
        public string SKL_FIELDA_003 { get; set; }
        public string SKL_FIELDA_004 { get; set; }
        public string SKL_FIELDA_005 { get; set; }
        public string SKL_FIELDA_006 { get; set; }
        public string SKL_FIELDA_007 { get; set; }
        public string SKL_FIELDA_008 { get; set; }
        public string SKL_FIELDA_009 { get; set; }
        public string SKL_FIELDA_010 { get; set; }
        public string SKL_FIELDB_001 { get; set; }
        public string SKL_FIELDB_002 { get; set; }
        public string SKL_FIELDB_003 { get; set; }
        public string SKL_FIELDB_004 { get; set; }
        public string SKL_FIELDB_005 { get; set; }
        public string SKL_FIELDB_006 { get; set; }
        public string SKL_FIELDB_007 { get; set; }
        public string SKL_FIELDB_008 { get; set; }
        public string SKL_FIELDB_009 { get; set; }
        public string SKL_FIELDB_010 { get; set; }
        public string SKL_FIELDB_011 { get; set; }
        public string SKL_FIELDB_012 { get; set; }
        public string SKL_FIELDB_013 { get; set; }
        public string SKL_FIELDB_014 { get; set; }
        public string SKL_FIELDB_015 { get; set; }
        public string SKL_FIELDB_016 { get; set; }
        public string SKL_FIELDB_017 { get; set; }
        public string SKL_FIELDB_018 { get; set; }
        public string SKL_FIELDB_019 { get; set; }
        public string SKL_FIELDB_020 { get; set; }
        public string SKL_FIELDB_021 { get; set; }
        public string SKL_FIELDB_022 { get; set; }
        public string SKL_FIELDB_023 { get; set; }
        public string SKL_FIELDB_024 { get; set; }
        public string SKL_FIELDB_025 { get; set; }
        public string SKL_FIELDB_026 { get; set; }
        public string SKL_FIELDB_027 { get; set; }
        public string SKL_FIELDB_028 { get; set; }
        public string SKL_FIELDB_029 { get; set; }
        public string SKL_FIELDB_030 { get; set; }
        public string SKL_FIELDC_001 { get; set; }
        public string SKL_FIELDC_002 { get; set; }
        public string SKL_FIELDC_003 { get; set; }
        public string SKL_FIELDC_004 { get; set; }
        public string SKL_FIELDC_005 { get; set; }
        public string SKL_FIELDC_006 { get; set; }
        public string SKL_FIELDC_007 { get; set; }
        public string SKL_FIELDC_008 { get; set; }
        public string SKL_FIELDC_009 { get; set; }
        public string SKL_FIELDC_010 { get; set; }
        public string SKL_FIELDC_011 { get; set; }
        public string SKL_FIELDC_012 { get; set; }
        public string SKL_FIELDC_013 { get; set; }
        public string SKL_FIELDC_014 { get; set; }
        public string SKL_FIELDC_015 { get; set; }
        public string SKL_FIELDC_016 { get; set; }
        public string SKL_FIELDC_017 { get; set; }
        public string SKL_FIELDC_018 { get; set; }
        public string SKL_FIELDC_019 { get; set; }
        public string SKL_FIELDC_020 { get; set; }
        public string SKL_FIELDD_001 { get; set; }
        public Nullable<decimal> SKL_LAST_MODIFIED { get; set; }
        public string SKL_FSC_CUSTOMER_ID { get; set; }
        public string SKL_FIELDA_011 { get; set; }
        public string SKL_FIELDA_012 { get; set; }
        public string SKL_FIELDA_013 { get; set; }
        public string SKL_FIELDA_014 { get; set; }
        public string SKL_FIELDA_015 { get; set; }
        public string SKL_FIELDA_016 { get; set; }
        public string SKL_FIELDA_017 { get; set; }
        public string SKL_FIELDA_018 { get; set; }
        public string SKL_FIELDA_019 { get; set; }
        public string SKL_FIELDA_020 { get; set; }
        public string SKL_FIELDB_031 { get; set; }
        public string SKL_FIELDB_032 { get; set; }
        public string SKL_FIELDB_033 { get; set; }
        public string SKL_FIELDB_034 { get; set; }
        public string SKL_FIELDB_035 { get; set; }
        public string SKL_FIELDB_036 { get; set; }
        public string SKL_FIELDB_037 { get; set; }
        public string SKL_FIELDB_038 { get; set; }
        public string SKL_FIELDB_039 { get; set; }
        public string SKL_FIELDB_040 { get; set; }
        public string SKL_FIELDC_021 { get; set; }
        public string SKL_FIELDC_022 { get; set; }
        public string SKL_FIELDC_023 { get; set; }
        public string SKL_FIELDC_024 { get; set; }
        public string SKL_FIELDC_025 { get; set; }
        public string SKL_FIELDC_026 { get; set; }
        public string SKL_FIELDC_027 { get; set; }
        public string SKL_FIELDC_028 { get; set; }
        public string SKL_FIELDC_029 { get; set; }
        public string SKL_FIELDC_030 { get; set; }
        public string SKL_FIELDD_002 { get; set; }
        public string SKL_FIELDD_003 { get; set; }
        public string SKL_FIELDD_004 { get; set; }
        public string SKL_DISABLE_WAITLIST_IND { get; set; }
        public string SKL_ZONE { get; set; }
        public Nullable<decimal> SKL_WALK_ZONE_PERCENT { get; set; }
        public string SKL_GUID { get; set; }
    }
}
