//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_TAG_ACCESS
    {
        public string SUC_OID { get; set; }
        public string SUC_SUT_OID { get; set; }
        public string SUC_SUR_OID { get; set; }
        public Nullable<decimal> SUC_ACCESS_TYPE { get; set; }
        public Nullable<decimal> SUC_LAST_MODIFIED { get; set; }
    }
}
