//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELECTION_OBJECT
    {
        public Nullable<decimal> SEO_LAST_MODIFIED { get; set; }
        public string SEO_OID { get; set; }
        public string SEO_SEL_OID { get; set; }
        public string SEO_OBJ_OID { get; set; }
    }
}
