//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_SCHOOL
    {
        public string SFS_OID { get; set; }
        public string SFS_STF_OID { get; set; }
        public string SFS_SKL_OID { get; set; }
        public string SFS_CTX_OID { get; set; }
        public string SFS_JOB_CODE { get; set; }
        public string SFS_SUBJECT_CODE { get; set; }
        public Nullable<decimal> SFS_FTE { get; set; }
        public string SFS_FIELDA_001 { get; set; }
        public string SFS_FIELDA_002 { get; set; }
        public string SFS_FIELDA_003 { get; set; }
        public string SFS_FIELDB_001 { get; set; }
        public string SFS_FIELDB_002 { get; set; }
        public Nullable<decimal> SFS_LAST_MODIFIED { get; set; }
    }
}
