//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_PD_ACTION_GOAL_ALIGN
    {
        public string SAG_OID { get; set; }
        public string SAG_SAT_OID { get; set; }
        public string SAG_SDG_OID { get; set; }
        public string SAG_FIELDA_001 { get; set; }
        public string SAG_FIELDA_002 { get; set; }
        public string SAG_FIELDA_003 { get; set; }
        public string SAG_FIELDB_001 { get; set; }
        public string SAG_FIELDB_002 { get; set; }
        public string SAG_FIELDC_001 { get; set; }
        public Nullable<decimal> SAG_LAST_MODIFIED { get; set; }
    }
}
