//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_REQUEST_TRANSACTION
    {
        public string RET_OID { get; set; }
        public string RET_STD_OID { get; set; }
        public string RET_CTX_OID { get; set; }
        public Nullable<decimal> RET_LAST_POSTED_TIME { get; set; }
        public Nullable<decimal> RET_APPROVED_TIME { get; set; }
        public string RET_NOTES { get; set; }
        public Nullable<decimal> RET_LAST_MODIFIED { get; set; }
    }
}
