//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_PERIOD_ATTENDANCE
    {
        public string PAT_OID { get; set; }
        public string PAT_STD_OID { get; set; }
        public string PAT_SKL_OID { get; set; }
        public string PAT_MST_OID { get; set; }
        public Nullable<System.DateTime> PAT_DATE { get; set; }
        public string PAT_CODE_VIEW { get; set; }
        public string PAT_PERIOD_VIEW { get; set; }
        public string PAT_ABSENT_IND { get; set; }
        public string PAT_TARDY_IND { get; set; }
        public string PAT_DISMISSED_IND { get; set; }
        public string PAT_REASON_CODE { get; set; }
        public Nullable<System.DateTime> PAT_TIME_IN { get; set; }
        public Nullable<System.DateTime> PAT_TIME_OUT { get; set; }
        public string PAT_EXCUSED_IND { get; set; }
        public string PAT_OTHER_CODE { get; set; }
        public string PAT_OTHER_CODE_02 { get; set; }
        public string PAT_COMMENT { get; set; }
        public string PAT_FIELDA_001 { get; set; }
        public string PAT_FIELDA_002 { get; set; }
        public string PAT_FIELDB_001 { get; set; }
        public Nullable<decimal> PAT_LAST_MODIFIED { get; set; }
    }
}
