//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ATTENDANCE_TIME
    {
        public string ATM_OID { get; set; }
        public string ATM_ATT_OID { get; set; }
        public Nullable<System.DateTime> ATM_TIME { get; set; }
        public string ATM_ARRIVAL_IND { get; set; }
        public string ATM_REASON_CODE { get; set; }
        public string ATM_EXCUSED_IND { get; set; }
        public Nullable<decimal> ATM_LAST_MODIFIED { get; set; }
    }
}
