//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ED_PLAN_MEETING_PART
    {
        public string SEA_OID { get; set; }
        public string SEA_SEM_OID { get; set; }
        public string SEA_PSN_OID { get; set; }
        public string SEA_NAME_VIEW { get; set; }
        public string SEA_ROLE_CODE { get; set; }
        public string SEA_FIELDA_001 { get; set; }
        public string SEA_FIELDA_002 { get; set; }
        public string SEA_FIELDA_003 { get; set; }
        public string SEA_FIELDB_001 { get; set; }
        public string SEA_FIELDB_002 { get; set; }
        public string SEA_FIELDB_003 { get; set; }
        public string SEA_FIELDC_001 { get; set; }
        public string SEA_FIELDC_002 { get; set; }
        public string SEA_FIELDD_001 { get; set; }
        public Nullable<decimal> SEA_LAST_MODIFIED { get; set; }
    }
}
