//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ATTENDANCE_BATCH
    {
        public string ATB_OID { get; set; }
        public string ATB_STD_OID { get; set; }
        public string ATB_SKL_OID { get; set; }
        public Nullable<System.DateTime> ATB_DATE { get; set; }
        public string ATB_CODE_VIEW { get; set; }
        public string ATB_ABSENT_IND { get; set; }
        public string ATB_TARDY_IND { get; set; }
        public string ATB_DISMISSED_IND { get; set; }
        public string ATB_REASON_CODE { get; set; }
        public string ATB_EXCUSED_IND { get; set; }
        public Nullable<System.DateTime> ATB_TIME_IN { get; set; }
        public Nullable<System.DateTime> ATB_TIME_OUT { get; set; }
        public Nullable<decimal> ATB_PORTION_ABSENT { get; set; }
        public string ATB_OTHER_CODE { get; set; }
        public string ATB_OTHER_CODE_02 { get; set; }
        public string ATB_COMMENT { get; set; }
        public string ATB_FIELDA_001 { get; set; }
        public string ATB_FIELDA_002 { get; set; }
        public string ATB_FIELDB_001 { get; set; }
        public Nullable<decimal> ATB_LAST_MODIFIED { get; set; }
        public string ATB_REASON_CODE_02 { get; set; }
        public string ATB_COMMENT_02 { get; set; }
    }
}
