//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_FEE
    {
        public string FEE_OID { get; set; }
        public string FEE_STD_OID { get; set; }
        public string FEE_SKL_OID { get; set; }
        public string FEE_CTX_OID { get; set; }
        public Nullable<System.DateTime> FEE_DATE { get; set; }
        public string FEE_TYPE { get; set; }
        public string FEE_DESCRIPTION { get; set; }
        public Nullable<decimal> FEE_AMOUNT { get; set; }
        public string FEE_PAYMENT_IND { get; set; }
        public string FEE_COMMENT { get; set; }
        public string FEE_FIELDA_001 { get; set; }
        public string FEE_FIELDA_002 { get; set; }
        public string FEE_FIELDA_003 { get; set; }
        public string FEE_FIELDA_004 { get; set; }
        public string FEE_FIELDA_005 { get; set; }
        public string FEE_FIELDA_006 { get; set; }
        public string FEE_FIELDA_007 { get; set; }
        public string FEE_FIELDA_008 { get; set; }
        public string FEE_FIELDA_009 { get; set; }
        public string FEE_FIELDA_010 { get; set; }
        public string FEE_FIELDB_001 { get; set; }
        public string FEE_FIELDB_002 { get; set; }
        public string FEE_FIELDB_003 { get; set; }
        public string FEE_FIELDB_004 { get; set; }
        public string FEE_FIELDB_005 { get; set; }
        public string FEE_FIELDB_006 { get; set; }
        public string FEE_FIELDB_007 { get; set; }
        public string FEE_FIELDB_008 { get; set; }
        public string FEE_FIELDB_009 { get; set; }
        public string FEE_FIELDB_010 { get; set; }
        public string FEE_FIELDC_001 { get; set; }
        public string FEE_FIELDC_002 { get; set; }
        public string FEE_FIELDC_003 { get; set; }
        public string FEE_FIELDC_004 { get; set; }
        public string FEE_FIELDC_005 { get; set; }
        public string FEE_FIELDC_006 { get; set; }
        public string FEE_FIELDC_007 { get; set; }
        public string FEE_FIELDC_008 { get; set; }
        public string FEE_FIELDC_009 { get; set; }
        public string FEE_FIELDC_010 { get; set; }
        public string FEE_FIELDD_001 { get; set; }
        public string FEE_FIELDD_002 { get; set; }
        public Nullable<decimal> FEE_LAST_MODIFIED { get; set; }
    }
}
