//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ATTENDANCE
    {
        public string ATT_OID { get; set; }
        public string ATT_STD_OID { get; set; }
        public string ATT_SKL_OID { get; set; }
        public Nullable<System.DateTime> ATT_DATE { get; set; }
        public string ATT_CODE_VIEW { get; set; }
        public string ATT_TIME_VIEW { get; set; }
        public string ATT_ABSENT_IND { get; set; }
        public string ATT_TARDY_IND { get; set; }
        public string ATT_DISMISSED_IND { get; set; }
        public string ATT_REASON_CODE { get; set; }
        public string ATT_EXCUSED_IND { get; set; }
        public Nullable<decimal> ATT_PORTION_ABSENT { get; set; }
        public string ATT_OTHER_CODE { get; set; }
        public string ATT_OTHER_CODE_02 { get; set; }
        public string ATT_COMMENT { get; set; }
        public Nullable<decimal> ATT_TIMESTAMP { get; set; }
        public string ATT_FIELDA_001 { get; set; }
        public string ATT_FIELDA_002 { get; set; }
        public string ATT_FIELDB_001 { get; set; }
        public Nullable<decimal> ATT_LAST_MODIFIED { get; set; }
        public string ATT_ABSENT_IND_02 { get; set; }
        public string ATT_TARDY_IND_02 { get; set; }
        public string ATT_DISMISSED_IND_02 { get; set; }
        public string ATT_REASON_CODE_02 { get; set; }
        public string ATT_EXCUSED_IND_02 { get; set; }
        public string ATT_COMMENT_02 { get; set; }
        public string ATT_RESPONSE { get; set; }
        public string ATT_RESPONSE_02 { get; set; }
    }
}
