//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ASSESSMENT_RESPONSE
    {
        public string ASR_OID { get; set; }
        public string ASR_SKL_OID { get; set; }
        public string ASR_STD_OID { get; set; }
        public string ASR_ASM_OID { get; set; }
        public string ASR_ARD_OID { get; set; }
        public string ASR_RESPONSE { get; set; }
        public Nullable<decimal> ASR_LAST_MODIFIED { get; set; }
        public string ASR_FIELDA_001 { get; set; }
        public string ASR_FIELDA_002 { get; set; }
        public string ASR_FIELDA_003 { get; set; }
        public string ASR_FIELDA_004 { get; set; }
        public string ASR_FIELDA_005 { get; set; }
        public string ASR_FIELDA_006 { get; set; }
        public string ASR_FIELDA_007 { get; set; }
        public string ASR_FIELDA_008 { get; set; }
        public string ASR_FIELDA_009 { get; set; }
        public string ASR_FIELDA_010 { get; set; }
        public string ASR_FIELDB_001 { get; set; }
        public string ASR_FIELDB_002 { get; set; }
        public string ASR_FIELDB_003 { get; set; }
        public string ASR_FIELDB_004 { get; set; }
        public string ASR_FIELDB_005 { get; set; }
        public string ASR_FIELDB_006 { get; set; }
        public string ASR_FIELDB_007 { get; set; }
        public string ASR_FIELDB_008 { get; set; }
        public string ASR_FIELDB_009 { get; set; }
        public string ASR_FIELDB_010 { get; set; }
        public string ASR_FIELDC_001 { get; set; }
        public string ASR_FIELDC_002 { get; set; }
        public string ASR_FIELDC_003 { get; set; }
        public string ASR_FIELDC_004 { get; set; }
        public string ASR_FIELDC_005 { get; set; }
        public string ASR_FIELDC_006 { get; set; }
        public string ASR_FIELDC_007 { get; set; }
        public string ASR_FIELDC_008 { get; set; }
        public string ASR_FIELDC_009 { get; set; }
        public string ASR_FIELDC_010 { get; set; }
        public string ASR_FIELDD_001 { get; set; }
        public byte[] ASR_FIELDE_001 { get; set; }
    }
}
