//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_VERSION_HISTORY
    {
        public string SVH_OID { get; set; }
        public string SVH_STD_OID { get; set; }
        public string SVH_FIELDA_001 { get; set; }
        public string SVH_FIELDA_002 { get; set; }
        public string SVH_FIELDA_003 { get; set; }
        public string SVH_FIELDA_004 { get; set; }
        public string SVH_FIELDA_005 { get; set; }
        public string SVH_FIELDA_006 { get; set; }
        public string SVH_FIELDA_007 { get; set; }
        public string SVH_FIELDA_008 { get; set; }
        public string SVH_FIELDA_009 { get; set; }
        public string SVH_FIELDA_010 { get; set; }
        public string SVH_FIELDB_001 { get; set; }
        public string SVH_FIELDB_002 { get; set; }
        public string SVH_FIELDB_003 { get; set; }
        public string SVH_FIELDB_004 { get; set; }
        public string SVH_FIELDB_005 { get; set; }
        public string SVH_FIELDB_006 { get; set; }
        public string SVH_FIELDB_007 { get; set; }
        public string SVH_FIELDB_008 { get; set; }
        public string SVH_FIELDB_009 { get; set; }
        public string SVH_FIELDB_010 { get; set; }
        public string SVH_FIELDC_001 { get; set; }
        public string SVH_FIELDC_002 { get; set; }
        public string SVH_FIELDC_003 { get; set; }
        public string SVH_FIELDC_004 { get; set; }
        public string SVH_FIELDC_005 { get; set; }
        public Nullable<System.DateTime> SVH_DATE { get; set; }
        public Nullable<decimal> SVH_LAST_MODIFIED { get; set; }
    }
}
