//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CONFIG
    {
        public string CFG_OID { get; set; }
        public string CFG_NEXT_HIGH_VALUE { get; set; }
        public string CFG_VERSION { get; set; }
        public Nullable<decimal> CFG_LAST_MODIFIED { get; set; }
    }
}
