//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOL_NAV
    {
        public string TLN_OID { get; set; }
        public string TLN_TOOL_OID { get; set; }
        public string TLN_NAV_ID { get; set; }
        public string TLN_ORG1_APP_IND { get; set; }
        public string TLN_ORG2_APP_IND { get; set; }
        public string TLN_ORG3_APP_IND { get; set; }
        public string TLN_ORG4_APP_IND { get; set; }
        public string TLN_ORG5_APP_IND { get; set; }
        public string TLN_SKL_APP_IND { get; set; }
        public string TLN_STF_APP_IND { get; set; }
        public string TLN_STD_APP_IND { get; set; }
        public string TLN_FAM_APP_IND { get; set; }
        public string TLN_BLD_APP_IND { get; set; }
        public string TLN_HTH_APP_IND { get; set; }
        public string TLN_PSN_APP_IND { get; set; }
        public string TLN_IEP_APP_IND { get; set; }
        public Nullable<decimal> TLN_SEQUENCE_NUMBER { get; set; }
        public string TLN_INSERT_SEPARATOR_IND { get; set; }
        public string TLN_CUSTOM_REPORT_IND { get; set; }
        public Nullable<decimal> TLN_TOOL_TYPE { get; set; }
        public Nullable<decimal> TLN_LAST_MODIFIED { get; set; }
    }
}
