//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ROLE
    {
        public string URO_OID { get; set; }
        public string URO_USR_OID { get; set; }
        public string URO_SUR_OID { get; set; }
        public Nullable<decimal> URO_LAST_MODIFIED { get; set; }
        public Nullable<decimal> URO_SCHOOL_VISIBILITY_TYPE { get; set; }
    }
}
