//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TEMPLATE
    {
        public string VWT_OID { get; set; }
        public string VWT_OWNER_OID { get; set; }
        public Nullable<decimal> VWT_OWNER_TYPE { get; set; }
        public string VWT_DDX_OID { get; set; }
        public string VWT_NAME { get; set; }
        public string VWT_CONTEXT { get; set; }
        public string VWT_VIEW_DEFINITION { get; set; }
        public string VWT_CUSTOM_IND { get; set; }
        public string VWT_HIDE_IND { get; set; }
        public Nullable<decimal> VWT_LAST_MODIFIED { get; set; }
        public string VWT_DESCRIPTION { get; set; }
        public string VWT_HELP_ENABLED { get; set; }
        public string VWT_PROCEDURE_ID { get; set; }
        public Nullable<decimal> VWT_SCHOOL_VISIBILITY_TYPE { get; set; }
        public Nullable<decimal> VWT_ROLE_VISIBILITY_TYPE { get; set; }
    }
}
