//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_DEFINITION
    {
        public string WFD_OID { get; set; }
        public string WFD_ORG_OID_1 { get; set; }
        public string WFD_ORG_OID_2 { get; set; }
        public string WFD_ORG_OID_3 { get; set; }
        public string WFD_ORG_OID_4 { get; set; }
        public string WFD_ORG_OID_5 { get; set; }
        public string WFD_TBD_OID_OWNER { get; set; }
        public string WFD_TBD_OID_SELECTION { get; set; }
        public string WFD_WPH_OID_FIRST { get; set; }
        public string WFD_FDD_OID_OWNER { get; set; }
        public string WFD_ID { get; set; }
        public string WFD_NAME { get; set; }
        public string WFD_CATEGORY { get; set; }
        public string WFD_SPED_IND { get; set; }
        public string WFD_PD_IND { get; set; }
        public string WFD_DESCRIPTION { get; set; }
        public string WFD_ALIGNED { get; set; }
        public string WFD_SELECTION_QUERY { get; set; }
        public string WFD_PROCEDURE_ID { get; set; }
        public Nullable<decimal> WFD_LAST_MODIFIED { get; set; }
        public Nullable<decimal> WFD_SELECT_TYPE { get; set; }
        public string WFD_DISABLED { get; set; }
        public string WFD_COMMENT { get; set; }
        public string WFD_CUSTOM_HREF { get; set; }
        public string WFD_MENU_GROUP { get; set; }
        public Nullable<decimal> WFD_SCHOOL_VISIBILITY_TYPE { get; set; }
        public Nullable<decimal> WFD_ROLE_VISIBILITY_TYPE { get; set; }
        public Nullable<decimal> WFD_SEQUENCE_NUMBER { get; set; }
    }
}
