//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_PHASE_OUTCOME
    {
        public string WPO_OID { get; set; }
        public string WPO_WPH_OID { get; set; }
        public string WPO_WPH_OID_NEXT { get; set; }
        public string WPO_ID { get; set; }
        public string WPO_OUTCOME { get; set; }
        public string WPO_STANDARD_IND { get; set; }
        public string WPO_DISCONTINUED_IND { get; set; }
        public string WPO_RULE { get; set; }
        public string WPO_DETAIL_ACTION { get; set; }
        public string WPO_METHOD_ID { get; set; }
        public string WPO_ALIGNMENT_ID { get; set; }
        public string WPO_CONDITIONAL_BRANCH_IND { get; set; }
        public Nullable<decimal> WPO_LAST_MODIFIED { get; set; }
        public string WPO_ANONYMOUS_IND { get; set; }
    }
}
