//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_PHASE
    {
        public string WPH_OID { get; set; }
        public string WPH_WFD_OID { get; set; }
        public string WPH_PRC_OID { get; set; }
        public string WPH_WPO_OID_STANDARD { get; set; }
        public string WPH_ID { get; set; }
        public string WPH_NAME { get; set; }
        public string WPH_INSTRUCTION { get; set; }
        public string WPH_REDIRECT { get; set; }
        public string WPH_EDIT_PRIVS { get; set; }
        public Nullable<decimal> WPH_SEQUENCE_NUMBER { get; set; }
        public string WPH_DESCRIPTION { get; set; }
        public string WPH_UNCONSECUTIVE_IND { get; set; }
        public string WPH_PORTLET_IND { get; set; }
        public Nullable<decimal> WPH_LAST_MODIFIED { get; set; }
        public string WPH_ANONYMOUS_IND { get; set; }
        public string WPH_INITIALIZE_IND { get; set; }
    }
}
