//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_CONVERSION_TABLE_STAT
    {
        public string ZTS_OID { get; set; }
        public string ZTS_ZCV_OID { get; set; }
        public string ZTS_ZTM_OID { get; set; }
        public Nullable<decimal> ZTS_SOURCE_COUNT { get; set; }
        public Nullable<decimal> ZTS_QUERY_COUNT { get; set; }
        public Nullable<decimal> ZTS_RECORDS_INSERTED { get; set; }
        public Nullable<decimal> ZTS_DUPLICATES { get; set; }
        public string ZTS_MESSAGE { get; set; }
        public Nullable<decimal> ZTS_DURATION { get; set; }
        public Nullable<decimal> ZTS_LAST_MODIFIED { get; set; }
    }
}
