//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_JOB_PROCEDURE
    {
        public string ZJP_OID { get; set; }
        public string ZJP_ZJB_OID { get; set; }
        public string ZJP_ZPR_OID { get; set; }
        public Nullable<decimal> ZJP_SEQUENCE_NUMBER { get; set; }
        public string ZJP_DISABLED_IND { get; set; }
        public Nullable<decimal> ZJP_LAST_MODIFIED { get; set; }
    }
}
