//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAutoAssignment.Entities.ExtractAspen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_PROCEDURE
    {
        public string ZPR_OID { get; set; }
        public string ZPR_NAME { get; set; }
        public byte[] ZPR_PROCEDURE_SOURCE { get; set; }
        public Nullable<decimal> ZPR_SOURCE_TYPE { get; set; }
        public Nullable<decimal> ZPR_RUN_TYPE { get; set; }
        public byte[] ZPR_COMMENTS { get; set; }
        public Nullable<decimal> ZPR_LAST_MODIFIED { get; set; }
    }
}
